### ISSUE TITLE
SCSB endpoint should return 404 when it his suppressed records

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1046]
SCSB will ask for suppressed records because sometimes these are sent to Recap. We can't get them from the Alma API, though. In the code, we get the item and the holdings but then the request for the bib record returns an error (e.g. https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/9958708973506421?apikey=)

We can return a 404 for this; distinguishing between this and the other 404s wouldn’t be helpful.

honeybadger issue is 
https://app.honeybadger.io/projects/54497/faults/74759178

### Use case background

When Recap staff receive an item and scan it into the the SCSB system (aka “accession” it), their system hits the bibdata scsb endpoint to pull in the data. If there’s any problem at this point the item will have status “incomplete”. If the problem was a 500 or other error from bibdata, it gets “Dummy Title” and “Dummy Author” as the data values.

Recap staff regularly pull up and investigate the report of incomplete records, so there is already workflow around handling errors.

The records should clear from incomplete status once #1049 is implemented because Recap staff will re-save the records that don't look right to get them to re-export to SCSB.

**Comment by tpendragon** [comment]
@eliotjordan @hackartisan Is this closed? I see that linked PR (#1077), but no history of this auto-closing.

**Comment by hackartisan** [comment]
@tpendragon sorry; because it merged to a non-default branch it doesn't auto-close. We have to remember to close issues when we merge.
