### ISSUE TITLE
Enable copy number test with new alma fixture

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1071]
https://github.com/pulibrary/bibdata/blob/9a9e6ea96019abc180dd83f4ad03289d211562b9/spec/marc_to_solr/lib/princeton_marc_spec.rb#L686

**Comment by hackartisan** [comment]
https://github.com/pulibrary/bibdata/blob/808a4d7809a48e49c61c138f3629dd577f195b5a/spec/marc_to_solr/lib/princeton_marc_spec.rb#L685

Otherwise, this may be resolved as part of #1202

**Comment by tpendragon** [comment]
In production: https://catalog.princeton.edu/catalog/1414145/raw In holdings_1display, the MFHD ID has copy_number.

This record is not indexed in catalog-alma-qa.

**Comment by christinach** [comment]
`852$t` is not included in the Data enrichment. We can't add it now since there is a configuration freeze but do we want to add it later so that we can enable this test? @mzelesky ?

**Comment by christinach** [comment]
It seems that copy id is in 876 (item level) and this is what we are using. 876$t. I will update the description unless the copy number is information that we also need in 852$t. @mzelesky ?

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/bibdata/pull/1491

**Comment by hackartisan** [comment]
close this in favor of https://github.com/pulibrary/bibdata/issues/1488, which was resolved by https://github.com/pulibrary/bibdata/pull/1491
