### ISSUE TITLE
Resume marc_liberation:recap_dump

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1078]
https://github.com/pulibrary/marc_liberation/blob/cd7226c1e3b97a630c5e334dc1004916e985d0ef/config/schedule.rb#L75

**Comment by mzelesky** [comment]
There is a PR out for review to fix the problem with the SCSB exports. Once the voyager_helpers PR is merged, updates need to be gotten from today's date (February 17, 2021).

**Comment by christinach** [comment]
Following on @mzelesky comment ^ when we update the voyager helpers in marc_liberation, ran the rake task with `02-17-2021` timestamp. 
Then uncomment the rake task and let it run daily. https://github.com/pulibrary/marc_liberation/blob/cd7226c1e3b97a630c5e334dc1004916e985d0ef/config/schedule.rb#L75

**Comment by christinach** [comment]
This was tested and resumed. Now it's paused again because of alma migration.
