### ISSUE TITLE
Populate location table flags

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1103]
Follow-on to https://github.com/pulibrary/marc_liberation/issues/964

https://github.com/pulibrary/marc_liberation/blob/alma/app/services/location_data_service.rb uses the Alma API to pull the new libraries and locations into the locations database tables. However no flags have been set.

If these flags can be set via the Alma API, we need specifications for doing so. If they can't, they must be set directly, either by mapping existing locations to alma locations and reading the values from current production, or by hand in the bibdata-alma-staging UI.

Question: Will there be new locations added to Alma? Previously we were told no, those were locked, but recently there was talk of new Marquand locations. If there are new locations that is relevant here because the code that syncs the locations from Alma deletes / repopulates the table, so it would wipe out any flags that had been updated if it were re-run.

**Comment by kevinreiss** [comment]
If we add a new code in Voyager we will add it to Alma at the same time, so it should be in the data pulled out from Alma. We have been asked to add one location for Marquand due to a late breaking change for their closure next month. That should be the only one.

**Comment by kevinreiss** [comment]
We need to do an audit of the flags that one can set it Alma and see we can set these flags in Alma rather than here. It appears Alma has some extensible features in this space.

**Comment by kevinreiss** [comment]
@hackartisan what's the best way to manage the bulk updating of the location flags mapped to their new alma location codes in the bibdata alma environment?  I will also add the two locations need for processing scsb records, scsbnypl and scsbcul, to the data.

**Comment by hackartisan** [comment]
@kevinreiss probably a rake task that reads the mappings directly into the database, that we then run on the server. What do you think @eliotjordan ?

**Comment by christinach** [comment]
For anyone who will work on this issue when checking how locations/flags display in orangelight, remember to clear the cache in the catalog-alma-orangelight box. https://github.com/pulibrary/orangelight/blob/6f35623fb747934e4ef2bd428ed725787390c0f8/app/services/bibdata.rb#L40 There is a rake task to clear the cache in orangelight.https://github.com/pulibrary/orangelight/blob/6f35623fb747934e4ef2bd428ed725787390c0f8/lib/tasks/cache.rake#L3
