### ISSUE TITLE
Account for eresources in catalog_date

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/bibdata#1117]
The current implementation for `get_catalog_date` in the AlmaAdapter does not take into account eresources (AVE fields). See https://github.com/pulibrary/marc_liberation/pull/1112

We decided to delay the processing of AVE fields until the Alma API has a mechanism to get the "activation_date" for AVE records in one API call rather than one call per portfolio. ExLibris has indicated that they will add this feature around May/2021 (see https://3.basecamp.com/3765443/buckets/20717908/messages/3475344037). 

In the meantime this ticket is marked as blocked.

See original ticket https://github.com/pulibrary/marc_liberation/issues/925 for more details.

**Comment by hackartisan** [comment]
I'm removing the block label because according to the timeline exlibris would have released the update we required; anyone picking up the ticket will need to check!

**Comment by hackartisan** [comment]
closing in favor of #1478
