### ISSUE TITLE
Provide pagination for the bibliographic#availability_holding endpoint

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1121]
Alma's API only returns 100 items at a time. Reports run in the past revealed ~1,000 records with > 100 items, with the max having around 4,000 items. Note that we don't collect all items at once anymore, though, only all the items on a single holding. New stats might be helpful.

We may be able to reduce Alma API calls by rewriting the front-end of the requests app to paginate directly from javascript. Our endpoint would need to pass-through pagination and searching params to support that.

**Comment by tpendragon** [comment]
Is https://github.com/tulibraries/alma_rb/blob/a01d04cea8283348802c3c33b9c8c07b7dde6dcf/lib/alma/bib_item_set.rb#L52-L72 relevant?

**Comment by hackartisan** [comment]
The requests app won't do a front-end rewrite at this time. Closing the issue for now.
