### ISSUE TITLE
Add 773 fields to constituent records of some bound-with materials

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1123]
We need to add 773 fields to constituent records of bound-withs in Alma to test that the indexing works properly for them.

**Comment by christinach** [comment]
We will also index them and see how they display in catalog-alma-qa.

**Comment by christinach** [comment]
this is done https://docs.google.com/document/d/1SCmO78lh164fXCfQA9u4PzCbigb4c_JumakLxsRaKvs/edit. 
We added 773s; exported the records and will include them as fixtures for the availability check.
