### ISSUE TITLE
Update MarcCleanup (marc_cleanup gem)

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1124]
The current release is 0.9.0 and our version in use is 0.7.0.

The version we're using includes a bug that overrides `map` for `NilClass`. It seems like that's been resolved, or at least the method has been renamed. This is the source of the weird `f` arrays that are added to each response in the bib items endpoint.

I'm not sure what parts of this gem are used in bibdata, but we'll need to identify them and check for backwards incompatabilities

```
[4] pry(#<BibliographicController>)> show-source NilClass.map

From: .asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/marc_cleanup-523cf5432c14/lib/marc_cleanup/rubymarc_methods.rb @ line 1731:
Owner: MarcCleanup
Visibility: public
Number of lines: 3

def map
  %w[ea eb ec ed ei em es fa fb fc fd fi fm fs]
end
```

**Comment by christinach** [comment]
related issue https://github.com/pulibrary/marc_liberation/issues/724
