### ISSUE TITLE
patron endpoint errors on netid

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1144]
Works fine when given a barcode

**Comment by pmgreen** [comment]
NetIDs have been manually added for only a few staff: https://github.com/pulibrary/bibdata/issues/932#issuecomment-763957859
NetIDs will be added for other users when the patron feed is updated (currently scheduled for March).

**Comment by hackartisan** [comment]
@pmgreen that's true but this happened with my account, which works fine with the netid directly to alma. It's something in the ruby code I think.

**Comment by hackartisan** [comment]
Not sure what was wrong before. It's working now with my netid, barcode, or patron id.
