### ISSUE TITLE
Create a list of MARC fields that are included in the keyword index of Blacklight

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1150]

**Comment by christinach** [comment]
The keyword search is searching across all_fields. To see these fields please see what we index in traject. https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb

**Comment by christinach** [comment]
I will also create a google doc and add the link here.

**Comment by kevinreiss** [comment]
I believe we have done this. Please confirm.

**Comment by christinach** [comment]
@mzelesky and I added detailed documentation about the marc fields we index in Orangelight. 

Phrase searches generally take precedence in keyword searches.
General order of priority for keyword searching:
1. Title
2. Author
3. Subject
4. Standard numbers

Documentation links: https://lib-confluence.princeton.edu/display/ALMA/Alma+-+Blacklight
https://lib-confluence.princeton.edu/display/ALMA/MARC+fields+indexed+in+Blacklight
https://lib-confluence.princeton.edu/display/ALMA/MARC+fields+used+for+facets
