### ISSUE TITLE
Rename the publishing jobs in alma and in bibdata

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1155]
The publishing jobs in Alma are named: 
'General Publishing via FTP', '
Incremental Publishing via FTP'.

We would like to rename them before we launch Alma and remove 'via FTP'. 
Also we will have to update https://github.com/pulibrary/bibdata/blob/a99a46bfc66c3bfe59d9ff56ef0b8221efe3e245/config/alma.yml#L10-16 where it references the name of the jobs.

**Comment by hackartisan** [comment]
WIP branch https://github.com/pulibrary/bibdata/tree/alma-issues-1155-jrgriffiniii-rename-jobs
