### ISSUE TITLE
JSONLD missing notes

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/bibdata#116]
E.g.
https://bibdata.princeton.edu/bibliographic/4732989/

https://bibdata.princeton.edu/bibliographic/4732989/jsonld

The JSON only has the first 505, and doesn't have the 510 (Citation/References), 520 (Summary), 541 (Source of Acquisition),  561 (Ownership and History), 563 (Binding Information).

Audit all of the notes, and consider rendering them with labels that are more specific. See https://www.loc.gov/marc/bibliographic/bd5xx.html. It may actually be easier to just assume that most or all of these will surface at some point.

I think there are one or two that should **not** be rendered. @tampakis do you remember?

**Comment by tampakis** [comment]
The 5xx fields mentioned above (and others) are included in the [traject config](https://github.com/pulibrary/marc_liberation/blob/development/lib/traject_config.rb#L404-L525). However Don wanted us to make some changes specified in pulibrary/orangelight#325.
