### ISSUE TITLE
Remove the Hours Location feature

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1165]
https://bibdata.princeton.edu/locations/hours_locations

The Hours Location is a nice feature that we never actually implemented and is not used in the catalog. 
Do we want to implement it? If not can we remove it?

**Comment by kevinreiss** [comment]
I think we can remove this. If we ever wanted to make a feature where we'd display or link to the current hours for a location or Library we could do this differently without storing so much data in the bibdata.

**Comment by christinach** [comment]
Thanks @kevinreiss !
