### ISSUE TITLE
Rename 'Rare Books and Special Collections' to 'Special Collections'

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1166]
This was changed in Blacklight but stayed with the old name in voyager. 
We should change it in Alma.

Update 'Rare Books and Special Collections' to 'Special Collections'.

**Comment by regineheberlein** [comment]
I changed the Organization Unit Name for now. 

What does the location prefix "Rare Books:" relate to? Is it shorthand for "Rare Books and Special Collections"? In that case, we should change it to "Special Collections:".

Or does it mean the umbrella collection "ex" (=rare books)? In that case, some of them need correcting, e.g. "hsvm" (=manuscripts high security vault) : "Rare Books: South East (MSS)"

**Comment by christinach** [comment]
Thank you for changing the name @regineheberlein.

Your questions make a lot of sense. @kevinreiss @mzelesky who is the right person/group of people to answer these questions?

**Comment by christinach** [comment]
Thank you!

**Comment by regineheberlein** [comment]
Per conversation with Alexis:
1. Change external name to human readable expanded string
2. Change internal name to code + abbreviated human readable string
3. remove all prefixes

I'll get started now.

**Comment by regineheberlein** [comment]
Also pinged Joshua about the East Asian location labels (currently all "East Asian Rare")

**Comment by regineheberlein** [comment]
@mzelesky @kevinreiss Can we delete the location "UNASSIGNED"?

**Comment by regineheberlein** [comment]
@christinach What gets displayed in Blacklight, Name or External Name?

**Comment by mzelesky** [comment]
We cannot delete the location "UNASSIGNED"; it's used for migration purposes. At least, that's my understanding. If there is nothing in the locations after go-live we can delete. In general, we cannot delete any locations prior to go-live unless those locations are also deleted in Voyager.

**Comment by christinach** [comment]
@regineheberlein we use 'name', not the 'external_name'

**Comment by christinach** [comment]
@regineheberlein but we can change it to the 'external_name' if that makes more sense.

**Comment by regineheberlein** [comment]
@christinach Yes please. There is a difference between what staff need to see in the UI and what we want patrons to see in Blacklight, so change the source to external_name would be great.

**Comment by christinach** [comment]
@regineheberlein I will! Thank you.

**Comment by regineheberlein** [comment]
@christinach Thank you! I'm making a new ticket for it now.

**Comment by regineheberlein** [comment]
Now reaching out to Martin per Joshua

**Comment by regineheberlein** [comment]
Martin confirms that the labels for EA rare, while all the same, are good as is.
