### ISSUE TITLE
Remove the duplicate substring from the location code

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1167]
Some of the location codes include the library name. 
Remove the library name from the location code if it exists. 
https://github.com/pulibrary/bibdata/blob/alma/marc_to_solr/translation_maps/locations.rb.tmpl

**Comment by christinach** [comment]
I will continue with this issue when #1178 is done.

**Comment by christinach** [comment]
The full reindex started t 2:46pm. I did not include the UPDATE_LOCATIONS=true flag because of https://github.com/pulibrary/bibdata/issues/1187. There are records with no holdings but the ones that have locations are indexed as expected. 
The holding locations have duplicate or triple strings because we updated the location to use the external_name. When https://github.com/pulibrary/bibdata/issues/1178 is done then we can proceed improving the location names https://github.com/pulibrary/bibdata/issues/1167.

**Comment by christinach** [comment]
@kevinreiss @mzelesky can you review https://bibdata-alma-staging.princeton.edu/locations/holding_locations ? It has the updated external_name from https://github.com/pulibrary/bibdata/issues/1178.
 Do we still need to remove the substring when it is a duplicate of the Library name? 
For example do we want to change the display in the catalog to be: 
`Engineering Library - Engineering Library - Serials` 
vs 
`Engineering Library - Engineering Library - Engineering Library: Serials` ? 
Or would it be better to be: `Engineering Library - Serials`

**Comment by kevinreiss** [comment]
I think the last option is best for display purposes. @mzelesky I know why we keep the Library name in the location with Alma's configuration, but stripping it out for display purposes in Blacklight makes for less repetitive, cluttered UI.
