### ISSUE TITLE
Add 876$l and 876$k to barcode endpoint and Submit Collection records

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1170]
I just learned about a change to the SCSB MarcXML schema. We need to add a subfield l with a value of 'RECAP' to every 876 field in the SubmitCollection files we send. https://htcrecap.atlassian.net/wiki/spaces/RTG/pages/27692276/Ongoing+Accession+Submit+Collection+through+API

876$k is a new requirement that's not in the documentation yet. It should be the owning library code, e.g. firestone.

**Comment by hackartisan** [comment]
@mzelesky once we're on Alma, can the publishing job be configured to add this? We've implemented the code that just pushes those dump files straight to s3.

**Comment by hackartisan** [comment]
This value may be optional

**Comment by mzelesky** [comment]
There is also the need to retrieve the bib records for any 774 field on the record before sending the file to SCSB.

**Comment by hackartisan** [comment]
Go ahead and put this in since we're in there anyway and it's a static string.
