### ISSUE TITLE
Pagination: Ensure we're getting all holdings or items from the alma API

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1177]
- [x] `get_items_for_bib` https://github.com/pulibrary/bibdata/blob/alma/app/adapters/alma_adapter.rb#L63
- [x] AvailabilityStatus#holding_item_data https://github.com/pulibrary/bibdata/blob/1fbf110c3fc595d301b1ed0a592bbd8aff1f407c/app/adapters/alma_adapter/availability_status.rb#L123
- [x] AvailabilityStatus#item_data https://github.com/pulibrary/bibdata/blob/1fbf110c3fc595d301b1ed0a592bbd8aff1f407c/app/adapters/alma_adapter/availability_status.rb#L95

**Comment by tpendragon** [comment]
Relevant:

https://github.com/tulibraries/alma_rb/blob/a01d04cea8283348802c3c33b9c8c07b7dde6dcf/lib/alma/bib_item_set.rb#L52-L72

**Comment by hackartisan** [comment]
We're still discussing the implications that serials checkins will have on this issue. A new item record is created each time an issue is checked in. Generally these are added to existing holdings so the serials record may have, e.g., 7 holdings with up to 700 items on a holding.

Does holdings/ALL/items paginate on the number of holdings? I.e. it will return every item on each holding no matter what, but paginate through holdings? We need to confirm exactly how this scenario is negotiated by Alma's pagination.

**Comment by hectorcorrea** [comment]
> Does holdings/ALL/items paginate on the number of holdings? 
> I.e. it will return every item on each holding no matter what, but paginate through holdings? 
> We need to confirm exactly how this scenario is negotiated by Alma's pagination.
Yes, it does. 

See notes for 4/28 [here](https://docs.google.com/document/d/1sq_DmkRVLWEQdwf0YY1Dl3KGYlPd_0ldCYYc6PTcOuY/edit#)
