### ISSUE TITLE
Update in Alma system the location external_name field

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1178]
https://github.com/pulibrary/bibdata/blob/alma/marc_to_solr/translation_maps/locations.rb.tmpl

example: https://github.com/pulibrary/bibdata/blob/03d31fbf7bf3aedc3ef676a09272a89059e8d44f/marc_to_solr/translation_maps/locations.rb.tmpl#L170 
should be as in production https://github.com/pulibrary/bibdata/blob/26a21f36629906417a7a195fe6503bd426d8360d/marc_to_solr/translation_maps/locations.rb.tmpl#L232

@kevinreiss will discuss this with the team.

**Comment by christinach** [comment]
@mzelesky @regineheberlein you mentioned yesterday in the DSSG that you will update the external_name. Can you please update this issue when this is done? I'm also assigning you on this issue. Thank you!

**Comment by kevinreiss** [comment]
All the special locations have been updated.

**Comment by christinach** [comment]
Thank you @kevinreiss !

**Comment by regineheberlein** [comment]
Will do @christinach !

**Comment by regineheberlein** [comment]
@christinach @kevinreiss This is done. 

FYI I made no changes to "Electronic Access" after checking in with @mzelesky , nor to "Princeton University" or "Obsolete Locations". Also, @mzelesky clarified that "cat" and "circ" are artificial location codes that don't need to be changed.

**Comment by christinach** [comment]
Thank you @regineheberlein and @mzelesky !
