### ISSUE TITLE
Availability by mfhd

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/bibdata#1179]
This ticket is to keep separate documentation for the Availability endpoint by `mfhd` (i.e. is a child of #573)

The part relevant from the original ticket is:

```
Support [availability by] `?mfhd=`

returns the same fields as ?id, but just a single holding location instead of all of them.
Used by requests app
```

The endpoint needs to navigate the alma pagination in order to return all the items of the holding

Additional notes from @carolyncole  - see https://github.com/pulibrary/bibdata/issues/573#issuecomment-781585579

```
For the availability?mfhd= endpoint the fields we use are: 
barcode, location, copy_number, status, on_reserve, item_type, pickup_location_id, pickup_location_code, 
enum_display, chron, status_label

Fields we do not use, but are currently present: id, item_sequence_number, due_date, patron_group_charged, 
enum, label(?), location(?). 

(I put question marks, because I do not see them at first glance, but they seem like things we might use...)
```

Carolyn also pointed out the part of the Request app that uses this end point is on https://github.com/pulibrary/requests/blob/8ad33d654365cc876264f89192de8aec8acc57fd/app/models/requests/request.rb and that noted that the `system_id` in that code is similar to the `bib_id`. 

Kevin also noted that everywhere there is a `mfhd` the application has access to the `bid_id`. This is important because Alma API does not allow to fetch an individual holding (the equivalent of mfhd) without having the `bib_id`.

**Comment by hectorcorrea** [comment]
@carolyncole @kevinreiss do you have an example of what is displayed in the `enum_display` and `chron` fields? 

There are many `enum_*` and `chronology_*` fields in the ExLibris response and I am trying to figure how to combine them to mimic what you got from Voyager.

**Comment by mzelesky** [comment]
We will likely only use enumeration_a and chronology_i. That's all that was migrated from Voyager. In the future, we may end up using multiple levels of enumeration, which we would likely want to display in order (i.e., enumeration_a through enumeration_h, chronology_i through chronology_m).

**Comment by hectorcorrea** [comment]
@mzelesky great, thanks!

**Comment by hectorcorrea** [comment]
@mzelesky: There is some temporary location that comes back in the API call to Alma that we use to get information for the Request app (notice that this is a separate ticket from #1190)

For example, the API call to 

```
.../almaws/v1/bibs/9919392043506421/holdings/22105104420006421/items
```

Gives a response like this (I removed some unrelated properties to make it easier to digest) that includes `in_temp_location`, `temp_location`, and `temp_library` at the **holding level** in addition to the `library` and `location` information that comes at the **item level**.

In this case, do we need to return both the `temp_location` and the `location` or should we return only the `temp_location` when `in_temp_location` is `true` ?

```
{
  "item": [
    {
      "bib_data": {
        "mms_id": "9919392043506421",
        "title": "Prilozi za istraživanje hrvatske filozofske baštine.",
        "author": "Sveučilište u Zagrebu. Institut za filozofiju.",
        "link": "https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/9919392043506421"
      },
      "holding_data": {
        "holding_id": "22105104420006421",
        "call_number": "B6 .xP7",
        "in_temp_location": true,
        "temp_library": {
          "value": "online",
          "desc": "Electronic Access"
        },
        "temp_location": {
          "value": "etasrcp",
          "desc": "ETAS Non Circ ReCAP"
        },
        "link": "https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/9919392043506421/holdings/22105104420006421"
      },
      "item_data": {
        "pid": "23105104390006421",
        "barcode": "32101080920208",        
        "base_status": {
          "value": "1",
          "desc": "Item in place"
        },
        "awaiting_reshelving": false,
        "physical_material_type": {
          "value": "ISSUE",
          "desc": "Issue"
        },
        "policy": {
          "value": "Gen",
          "desc": "Gen"
        },
        "enumeration_a": "g. 4, br. 7/8",
        "chronology_i": "",
        "description": "g. 4, br. 7/8",
        "receiving_operator": "import",
        "process_type": {
          "value": "",
          "desc": null
        },
        "library": {
          "value": "recap",
          "desc": "ReCAP"
        },
        "location": {
          "value": "pa",
          "desc": "rcppa RECAP"
        },
      },
      "link": "https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/9919392043506421/holdings/22105104420006421/items/23105104390006421"
    },    
}
```
