### ISSUE TITLE
Create a guide document for the catalog-alma-qa QA testing

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1184]
We discussed this with the rest of the DSSG and there will be different people recommended from the DSSG that will do QA testing. 
We should come up with a document pointing specific features/functionality that we would like them to test.

**Comment by hackartisan** [comment]
There is a start to this at https://docs.google.com/spreadsheets/d/1ZA5RHXP-Q43NCpU0xbZhTlvxlUQT5V8uKMBFYexpKcc/edit#gid=0
