### ISSUE TITLE
Availability status_label values need to be processed

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/bibdata#1186]
- The values for status_label should be capitalized
- "check_holdings" should be translated to "Some items not available"

https://github.com/pulibrary/bibdata/blob/alma/app/adapters/alma_adapter/availability_status.rb#L34

**Comment by eliotjordan** [comment]
@mzelesky Is the value for `check_holdings` correct?

**Comment by mzelesky** [comment]
Yes, that looks good to me.

**Comment by hectorcorrea** [comment]
@eliotjordan do you have a sample mms_id with "check_holdings" status that I can use to test?

**Comment by hectorcorrea** [comment]
Never mind, I found one: 9921799253506421

**Comment by hectorcorrea** [comment]
Fixed by PR #1191
