### ISSUE TITLE
Add "cdl" key to bibliographic/:id/availability

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1189]
This should be true if work_order_type is "CDL" and false otherwise.

see https://github.com/pulibrary/bibdata/pull/1156 for reference.

**Comment by hectorcorrea** [comment]
@eliotjordan @hackartisan do you have a mms_id that I can use to test?

**Comment by hackartisan** [comment]
@hectorcorrea 9965126093506421
