### ISSUE TITLE
Add `temp_loc` to bibliographic/[:id]/availability.json endpoint

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/bibdata#1190]
We need `temp_loc` for stackmap and for logic to display the request button in OL.

https://github.com/pulibrary/bibdata/blob/alma/app/adapters/alma_adapter/availability_status.rb#L29

**Comment by hectorcorrea** [comment]
@eliotjordan what's the value that goes in `temp_loc` ? true/false or an actual location?

**Comment by hackartisan** [comment]
orangelight is expecting an actual location.

**Comment by mzelesky** [comment]
Our temp locations are not currently included in our publishing profiles. This needs to be corrected before temp locations can be accessed. To fix this, we need to assign 'Current library subfield' and 'Current location subfield.' If those values are different than the locations in the 852 field, then they are temp values.

**Comment by tpendragon** [comment]
Blocked by current work on availability.

**Comment by hectorcorrea** [comment]
This has been unblocked (https://github.com/pulibrary/bibdata/pull/1211)

**Comment by hectorcorrea** [comment]
Per Mark: the following records are in temporary locations and are not ETAS: 9959958323506421 and 9938793603506421
