### ISSUE TITLE
The indexing process didn't index the cataloged date for 9932455293506421 

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1197]
Pull this record as a fixture and use it to troubleshoot the error.

2021-04-01T16:43:51+00:00 ERROR 001 9932455293506421 - error parsing cataloged date L66\1997\(LC)

https://catalog-alma-qa.princeton.edu/catalog/9932455293506421/raw

**Comment by mzelesky** [comment]
https://catalog.princeton.edu/catalog/3245529/staff_view

**Comment by christinach** [comment]
Reviewed this with @mzelesky. It is a data issue because of 950$b; cataloged_date drives the recently cataloged. So if there is an error it will not be there.
