### ISSUE TITLE
Include records with electronic portfolios in online facet

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1202]
per @mzelesky 

A record should be in the online facet if either of the two below conditions are true:

- If there is an electronic portfolio include it in the online facet.
- If the second indicator of 856 is 1 or 0 or blank include in the online facet. https://www.loc.gov/marc/bibliographic/bd856.html

Do not consider holding locations these are only used for physical items. (The elfs are not valid any more. The access.rb file should not include elfs. https://github.com/pulibrary/bibdata/issues/1203)

Implementation: Use a flag `electronic_record`

**Comment by christinach** [comment]
Example with electronic_portfolio_s field that is not included in the online facet https://catalog-alma-qa.princeton.edu/?q=1476-4687&search_field=all_fields
https://catalog-alma-qa.princeton.edu/catalog/99122306151806421/raw

**Comment by hackartisan** [comment]
Does the flag have meaning beyond being an implementation note? Is this really about these being the 2 cases that should cause a resource to show in the "online" facet?

**Comment by christinach** [comment]
Yes, the flag is an implementation note. Per @mzelesky these are the 2 cases that will place an electronic record in the online facet.

**Comment by eliotjordan** [comment]
What about Hathi items? Those are currently marked as Online.

**Comment by christinach** [comment]
Good question. I think yes but I need to look through the code. @kevinreiss @mzelesky will we still continue to include Hathi in the online facet?
