### ISSUE TITLE
Remove elf locations from access.rb

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1203]
Remove `elf` locations from bibdata; elfs are not valid locations and we will not have them anymore in Alma.
Some records they still have them because they were added after the P2E (Print to Electronic) file was used to import electronic records into Alma.

**Comment by hackartisan** [comment]
@christinach is it true that this ticket can be closed when https://github.com/pulibrary/bibdata/blob/alma/marc_to_solr/translation_maps/access.rb does not contain any keys with "elf"?

**Comment by christinach** [comment]
I think so. Because by removing them from the https://github.com/pulibrary/bibdata/blob/alma/marc_to_solr/translation_maps/access.rb file they will not appear under the online facet. But I would need to test it as well.

**Comment by tpendragon** [comment]
@christinach @hackartisan Should we also remove https://github.com/pulibrary/bibdata/blob/alma/marc_to_solr/translation_maps/locations.rb.tmpl#L37-L40 ?

**Comment by christinach** [comment]
@tpendragon yes. 
One way to do this is to wait for the cleanup in alma. Alma should not have elf locations at all. @mzelesky is there  a time for this cleanup?
The other way is not to count it when we pull the locations from Alma.

**Comment by hackartisan** [comment]
The code that generates the database tables needs to filter these out.

**Comment by tpendragon** [comment]
@hackartisan Should we close this since there's the other ticket?

**Comment by hackartisan** [comment]
yes i meant to do that!
