### ISSUE TITLE
Replace voyager fixtures with alma fixtures in traject tests

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1204]
Working through the traject specs, to ensure that we're covering the various code paths and data variations.

**Comment by christinach** [comment]
@mzelesky I can't find a fixture to satisfy this condition https://github.com/pulibrary/bibdata/blob/97420778d2d92b0bbba7906d680cda0cae2adf49/spec/marc_to_solr/lib/config_spec.rb#L357-L359. 
I also don't understand what does `not-ceased_008` https://github.com/pulibrary/bibdata/blob/97420778d2d92b0bbba7906d680cda0cae2adf49/spec/marc_to_solr/lib/config_spec.rb#L298-L301 mean. 
I can find 008-6 with c (no d) and the publication end date displays for both https://catalog-alma-qa.princeton.edu/catalog/997928443506421 https://catalog-alma-qa.princeton.edu/catalog/997608663506421/ .
It does not display for https://catalog-alma-qa.princeton.edu/catalog/997622433506421/.
Maybe you can help me to understand.
