### ISSUE TITLE
Correction on the isbn_display field

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1205]
If there is no subfield $a in 020 then we should not display the isbn in the record page.

**Comment by hackartisan** [comment]
@christinach do you mean it shouldn't index? Only index 020$a?

**Comment by christinach** [comment]
We should not index the isbn_display if 020 is missing. The isbn_display filed is what we see in the catalog record page as ISBN.
For example: https://catalog-alma-qa.princeton.edu/catalog/99121576653506421/ (hardcover) should not display. In the staff_view https://catalog-alma-qa.princeton.edu/catalog/99121576653506421/staff_view the 3rd z| 9781138388888 q| hardcover has no $a.

This is also an issue in production. Would it be better to apply this change in the main branch and we pull it with the rebase?

**Comment by christinach** [comment]
I updated my previous comment as : ` if 020$a `

**Comment by hackartisan** [comment]
👍🏻 we agreed on slack this will be fine to just go in the alma branch
