### ISSUE TITLE
Delete ETAS code

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1209]
ETAS is going away as of alma launch and won't come back. We can remove all the etas code.

**Comment by kevinreiss** [comment]
some methods reference "etas", some reference "hathi"

**Comment by maxkadel** [comment]
On catalog.princeton.edu there are 5 works that are listed under the location `online$etas`
* https://catalog.princeton.edu/catalog/9948595283506421
* https://catalog.princeton.edu/catalog/9911897463506421
* https://catalog.princeton.edu/catalog/9910009553506421
* https://catalog.princeton.edu/catalog/9910407913506421
* https://catalog.princeton.edu/catalog/995642993506421
