### ISSUE TITLE
Post incremental ReCAP dump files to S3

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1220]
Follow-on to #1049 / #1218

Once the dump objects are created the file/s need to be posted to S3.

Recent work converting the current / old process to use s3 can be found in https://github.com/pulibrary/bibdata/pull/1069/files and https://github.com/pulibrary/bibdata/pull/1082

**Comment by tpendragon** [comment]
Questions I'm hoping whoever works this will have the answer to:

Do we have a way to test this? Like somewhere else to upload this content to in staging?
Is it a problem if the format's not exactly the same as previously?
Does this only run in production?

**Comment by christinach** [comment]
@carolyncole has added a test https://github.com/pulibrary/bibdata/pull/1082/files for the princeton records we upload to scsb S3.
It is running in production.
@kevinreiss and @mzelesky should have more info regarding a test environment.

**Comment by hackartisan** [comment]
I would expect staging to have a poller, but I would think we don't want it publishing these files.

**Comment by hackartisan** [comment]
@tpendragon Can we just not include the configuration entry for the recap job in staging? Maybe that whole `jobs` section should only be populated for production / test.

**Comment by tpendragon** [comment]
We can, but I think we probably want it going somewhere in staging so we can make sure it's all working, right? I was just going to set up a Princeton AWS bucket with a tight delete window on it.

**Comment by hackartisan** [comment]
👍🏻 that sounds good!

**Comment by tpendragon** [comment]
Leaving some notes here in case I don't finish this in time:

Current way this works (a lot of this is going to end up deleted, and a lot of it is not tested):

1. `marc_liberation:recap_dump` gets called by a rake task which is now deleted (https://github.com/pulibrary/bibdata/blob/50b293cd5fcdb02ff8716984c6f953c6a24ecc14/lib/tasks/sync.rake#L8-L10)
1. `Dump.dump_ids` called with the dump type `PRINCETON_RECAP` (https://github.com/pulibrary/bibdata/blob/50b293cd5fcdb02ff8716984c6f953c6a24ecc14/app/models/dump.rb#L51-L53)
1. A `Dump` is created with `update_ids` set to all the updated barcodes from the queries. NO files are created! `https://github.com/pulibrary/bibdata/blob/50b293cd5fcdb02ff8716984c6f953c6a24ecc14/app/models/dump.rb#L99-L104`
1. Several slices of dump files are created. These are empty records, no actual file is saved yet. RecapDumpJob is called to generate the actual files associated with those `DumpFile`s: https://github.com/pulibrary/bibdata/blob/50b293cd5fcdb02ff8716984c6f953c6a24ecc14/app/models/dump.rb#L38-L45
1. Each file which gets created at the DumpFile's path is uploaded to the S3 bucket (https://github.com/pulibrary/bibdata/blob/50b293cd5fcdb02ff8716984c6f953c6a24ecc14/app/jobs/recap_dump_job.rb#L17-L21). The files are just the default named DumpFile paths, which are named after the generation timestamp.

With the new process:

(in progress)

**Comment by mzelesky** [comment]
I don't know if the publishing profile can handle SubmitCollection for bound-withs. Also, the entire call number (852 h and i) needs to be in the 852$h. So I think there's going to have to be additional work done on the records before submitting them to SCSB.
