### ISSUE TITLE
pickup_location_id should return an id same to what we currently get from voyager

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1233]
Currently we return from voyager the pickup_location_id. The mapping is happening in voyager_helpers The list is:
https://github.com/pulibrary/voyager_helpers/blob/0ae062a25177187fb6b47ae19e29b45ea469acb0/lib/voyager_helpers/liberator.rb#L1325

@kevinreiss can you confirm that these pickup_location_id(s) will not change ? @mzelesky

**Comment by hackartisan** [comment]
Close as duplicate of #848
