### ISSUE TITLE
Manage locations via a config file instead of using the database

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1241]
This is part of #1103 
I'm able to update the locations and the flags using the voyager mapping file, the voyager data and the alma locations. 
I thought it would be good to dump everything locally in a yaml file and check it in the repo, so that I can upload them in the location tables anytime, locally or in the VM.

**Comment by hackartisan** [comment]
I thought the plan was to move everything into a json file.

**Comment by christinach** [comment]
It can be either or. The current json files have the voyager values mapped to alma. 
The future json or yaml files will be a dump of the alma location values so that we can update the location tables anytime.

**Comment by hackartisan** [comment]
Okay as long as this isn't in addition to the json files we were talking about! 👍🏻

**Comment by christinach** [comment]
> Okay as long as this isn't in addition to the json files we were talking about! 👍🏻

Are you talking about the json files with the mapped voyager alma values https://github.com/pulibrary/bibdata/pull/1213/files or about the future files we want to use to update the locations?

**Comment by hackartisan** [comment]
My understanding is that the mapped voyager-alma value files are temporary, and at the end of the day we will have 1 set of config files representing everything that it currently stored in the locations database. Whether it's json or yaml I'm not sure I have an opinion about.

**Comment by christinach** [comment]
Yes correct.

**Comment by hackartisan** [comment]
So it seems like this rake task will also be temporary, right?

**Comment by christinach** [comment]
Yes the rake task I thought about it to be temporary. My first thought was ok we update the locations with the correct flags now we need to dump them so that we can upload them locally and do our work until we move on to the next location tickets.

**Comment by christinach** [comment]
This was also the main reason I tried https://github.com/pulibrary/bibdata/pull/1235
