### ISSUE TITLE
Don't add elf locations to locations db when populating database

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1245]
These values are still in alma records; it's bad data but if we index it then an erroneous physical holdings area appears in the catalog.

Update the location generator code to skip these locations (reference https://github.com/pulibrary/bibdata/pull/1215 for specific values)

When we phase out the database in favor of config files (see #1195) this won't be a problem anymore; simply close this issue if that happens first.

Related: #1250

**Comment by christinach** [comment]
closed by #1280
