### ISSUE TITLE
Delete  skipped elf-related tests in traject config spec

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/bibdata#1247]
https://github.com/pulibrary/bibdata/blob/alma/spec/marc_to_solr/lib/config_spec.rb#L449-L457

https://github.com/pulibrary/bibdata/blob/alma/spec/marc_to_solr/lib/config_spec.rb#L484-L487

**Comment by christinach** [comment]
We are not testing anymore elf locations. The have been removed from alma. We should delete the elf tests. For online locations we now use the electronic_portfolio_s field https://github.com/pulibrary/bibdata/blob/alma/spec/marc_to_solr/lib/config_spec.rb#L133-L171 . An example https://catalog-alma-qa.princeton.edu/catalog/99122306151806421/raw.
