### ISSUE TITLE
008 fields from the bibdata bibliographic endpoint are improperly formatted

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/bibdata#1249]
Spaces are being stripped from the 008 field values:

https://bibdata-alma-staging.princeton.edu/bibliographic/99120519033506421
https://bibdata-alma-staging.princeton.edu/bibliographic/9919643053506421

**Comment by tpendragon** [comment]
This is a browser display problem. If you `wget` those URLs the 008 fields are right.

**Comment by hectorcorrea** [comment]
The issue in staff view seems to be a display issue, the correct value is shown if you view-source 

![Screen Shot 2021-04-14 at 1 42 43 PM](https://user-images.githubusercontent.com/568286/114755704-f4b94500-9d27-11eb-89d8-8caf4f3c19a5.png)
