### ISSUE TITLE
Don't add zobsolete library and locations when we pull location values from alma

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1250]
Similarly to https://github.com/pulibrary/bibdata/issues/1245 we don't want to populate the location tables with zobsolete library - locations
https://catalog-alma-qa.princeton.edu/?f%5Blocation%5D%5B%5D=Obsolete+Locations

**Comment by hackartisan** [comment]
Per discussion with @mzelesky at an alma checkin we don't need to worry about this -- closing
