### ISSUE TITLE
Barcode endpoint and SubmitCollection job need the same formatting for SCSB records; bound-withs need to be handled in both places

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1251]
Records have to follow the schema documented here: https://htcrecap.atlassian.net/wiki/spaces/RTG/pages/27692276/Ongoing+Accession+Submit+Collection+through+API

The code here should be ported for Alma: https://github.com/pulibrary/voyager_helpers/blob/0ae062a25177187fb6b47ae19e29b45ea469acb0/lib/voyager_helpers/liberator.rb#L1114

In addition, bound-with records have an additional requirement of sending all bib records associated with the barcode in SubmitCollection, like we currently return for the barcode endpoint.

The owning library (the value in the 852 $b) needs to also be put in the 876 $k for each item.

**Comment by tpendragon** [comment]
How many bound-withs are there? We solve this in the barcode controller with a query, which isn't a big deal because it's one resource, if we have to do this for every resource it gets prohibitively expensive on API calls.

**Comment by mzelesky** [comment]
There are roughly 15,000. So it won't be too frequent that any are included at all.

**Comment by tpendragon** [comment]
Will we have to worry about the first submitCollection needing to do 15k of them?

**Comment by mzelesky** [comment]
Yes, we will.

**Comment by tpendragon** [comment]
I'm going to start work on this, but I don't expect I'll finish it. Hopefully I'll be able to provide all the necessary research.

**Comment by hackartisan** [comment]
@mzelesky The 876$k you mentioned at yesterday's meeting is not include in that documentation. Could you update the description of this issue to add additional instructions for that?

**Comment by hackartisan** [comment]
`876$k` is a new requirement that's not on the documentation yet. It should be the owning library code, e.g. `firestone`.

**Comment by hackartisan** [comment]
Closing this with https://github.com/pulibrary/bibdata/issues/1170 and #1255 as follow-ups
