### ISSUE TITLE
Load test the alma-based catalog

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1260]
Use siege or similar tool to hit the alma qa site with a lot of requests and see where it errors.

**Comment by christinach** [comment]
I did a quick test with no parameters; 5mins pinging catalog-alma-qa. The VM went down. I will try again a new test using specific endpoints from the document we have for the bibdata endpoints and I will log the steps on this ticket.

**Comment by hackartisan** [comment]
Some pointers to a previous siege I did against catalog searches:
- The issue was https://github.com/pulibrary/pul_solr/issues/174
- The code to generate the random search urls is at https://github.com/pulibrary/pul_solr/tree/main/scripts
- Based on the comment in that issue a good command to start with might be `$ siege --concurrent=25 --time=5m --file=urls.txt`

Note that in this case we do want to make sure we get javascript files, and in fact we want them to execute. If it's not possible to execute the JS then I'm not sure how much value we'll get out of this exercise -- the webserver infrastructure is identical to what we currently have so we know there's not a load issue there.

**Comment by hackartisan** [comment]
I just confirmed that siege does not execute javascript.

**Comment by jrgriffiniii** [comment]
I am looking to port https://app.circleci.com/pipelines/github/pulibrary/orangelight/1551/workflows/ab891724-bfb7-46dc-800e-2d3672c1beb7/jobs/2830 into bibdata, but thus far this is passing for me locally.
