### ISSUE TITLE
Update guard for recap location on item enrichment

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1277]
This line will break when many recap items are switched to locations under their home libraries to use the remote storage feature of alma:

https://github.com/pulibrary/bibdata/blob/41dc462cd2a8d1d1c05daa1b2d13d43bde35f1c0/app/adapters/alma_adapter/alma_item.rb#L51

Keep the guard but use the location code not the library. Location code should be a member of one of these arrays: https://github.com/pulibrary/bibdata/blob/41dc462cd2a8d1d1c05daa1b2d13d43bde35f1c0/app/adapters/alma_adapter/alma_item.rb#L145-L155

**Comment by hackartisan** [comment]
This logic was pulled from voyager helpers enrichment

**Comment by tpendragon** [comment]
For reference this was duplicating logic from the regex here:

https://github.com/pulibrary/voyager_helpers/blob/0ae062a25177187fb6b47ae19e29b45ea469acb0/lib/voyager_helpers/liberator.rb#L1128

**Comment by hackartisan** [comment]
Keep the guard but use the location code not the library. Location code should be a member of one of these arrays: https://github.com/pulibrary/bibdata/issues/1277

**Comment by eliotjordan** [comment]
Closed by #1341
