### ISSUE TITLE
Update the location external name in Alma not to include the library name

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1282]
In Alma we should update the location external name not to include the library name. For example`Firestone Library Stacks` should change to `Stacks`.
In Orangelight in the search results page and in the record page it will display: `Firestone Library - Stacks » PN2287.B37 F73 2020 `

For Recap locations under other owing libraries with use restrictions follow this pattern: `Remote Storage (ReCAP): <library name> use only`.
`Marquand Library - Remote Storage (ReCAP): Marquand Library use only`

@mzelesky @regineheberlein

**Comment by christinach** [comment]
What is the status of this issue? We still have a lot of locations where the external name includes the library name. https://bibdata-alma-staging.princeton.edu/locations/holding_locations

**Comment by regineheberlein** [comment]
It's on my list--sorry, haven't gotten to it yet!

**Comment by christinach** [comment]
Thank you @regineheberlein ! no worries, just following up. :)

**Comment by regineheberlein** [comment]
Truth be told, I had missed the ticket and only learned about this yesterday. 

The external names are all changed now with the exception of the ReCAP locations for Special Collections.

**Comment by christinach** [comment]
Wonderful! Thank you!
