### ISSUE TITLE
Refactor AvailabilityStatus so that it doesn't call the Alma gem directly

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1285]
Refactor AvailabilityStatus so that it does not need to call the Alma gem and instead it receives the data that it needs.

Benefits:
* All calls to the gem happen in the AlmaAdapter, making it easier to keep track of them since we have to keep an eye on API usage.
* Will allow us to remove duplicate alma_preserve_exception from AvailabilityStatus in favor of the one in AlmaAdapter.

**Comment by kevinreiss** [comment]
@christinach is this useful to do?

**Comment by mzelesky** [comment]
Is this handled by the switch to SRU?
