### ISSUE TITLE
Princeton_Recap update_ids array includes different numbers

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1298]
Example from https://bibdata.princeton.edu/events.json for `Princeton_Recap` event. 
"id": 23627,
"start": "2021-05-02T19:00:15.609Z",
"finish": "2021-05-02T19:11:40.962Z",
"success": true,
"error": null,
"dump_type": "PRINCETON_RECAP",
"dump_url": "https://bibdata.princeton.edu/dumps/23726.json"

The dump file includes 001 record ids that they were updated correctly on 2021-05-02. I looked each one in the catalog.
 In https://bibdata.princeton.edu/dumps/23726.json the `update_ids` array, includes non related numbers. This is consistent for all the Princeton_Recap events. We should inspect where are these numbers coming from and update the code to include in the `update_ids` the record ids that were updated. Due to the code freeze I'm labeling this in the alma project.

**Comment by christinach** [comment]
After searching in the file for these numbers I found out that these are coming from the 876$p 
`tag='876'><subfield code='0'>1254369</subfield><subfield code='3'>Bd.10</subfield><subfield code='a'>5874243</subfield><subfield code='h'></subfield><subfield code='j'></subfield><subfield code='p'>32101074958529</subfield><subfield code='t'>1</subfield><subfield code='x'>Shared</subfield><subfield code='z'>PA</subfield></datafield>`

**Comment by mzelesky** [comment]
I think it's more useful to have the barcodes (the 876p values) stored in the dump instead of the bib IDs, since many barcodes can exist under one bib. So knowing which items were sent is more useful than bib IDs.

**Comment by christinach** [comment]
Thank you @mzelesky . I didn't think about that. I will close the issue.
