### ISSUE TITLE
SCSB boundwiths fetched from Alma do not have holdings in the correct format

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/bibdata#1304]
Part of https://github.com/pulibrary/bibdata/issues/1255 and follow-up to https://github.com/pulibrary/bibdata/pull/1303

When a scsb boundwith record is pulled from Alma via the API, its holdings data is returned in an 'AVA' field. For SCSB this data needs to be translated into the expected MARC fields (e.g. 852, 876).

**Comment by hackartisan** [comment]
close in favor of https://github.com/pulibrary/bibdata/issues/1320
