### ISSUE TITLE
[SCSB] Include subfield I to indicate delivery expectations

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1321]
We need to include subfield I in 876 https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/princeton_marc.rb#L706

per @kevinreiss: items in Massachusetts will take 3-4 days to come rather than a day so we should tell them in our various labels and notifications related to delivery expectations .
Harvard has items both in Recap and HD (Harvard Depository).

We have a sample record. TODO: Add location of that record.

**Comment by christinach** [comment]
@kevinreiss when do we want this to be done?

**Comment by kevinreiss** [comment]
We can move forward with this now.

**Comment by hackartisan** [comment]
@kevinreiss what field should it be indexed as? What is the end-user use case?

**Comment by kevinreiss** [comment]
The end user case is items take 1-2 days longer to come from the HD warehouse instead of ReCAP. We can update the various expected delivery times we cite in the interface and emails to indicate this based on this value. This is new data so we need to create a new field to store it. In SCSB the attribute name used is "storage location". It's kind of long but we could do the name as "storage_location".

**Comment by christinach** [comment]
I looked in HL_20210716_063500.zip added in SCSB on 07/21/2021 and didnt find a 876$i.

**Comment by christinach** [comment]
Since this is item information can it be added as an attribute in the holdings1_display like we do for 876$zxh ? Do we need a new field? @kevinreiss

**Comment by kevinreiss** [comment]
We should add a new field to the item level data that makes it into the solr doc that reside in holdings1_display for the SCSB records. The 876 is intended to represent data at the item so even though it may seem a bit repetitive I think it's best to keep there in our JSON data alongside the other item-level attributes.

**Comment by christinach** [comment]
Ok so my understanding is that we don't need an extra solr field. Only to include it in the holdings_1display field and only for scsb.
