### ISSUE TITLE
Use scopes on the Dump model

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1345]
All over the place we do things like `dumps = Dump.where(dump_type: DumpType.find_by(constant: 'PARTNER_RECAP')` and we could refactor these to look like `Dump.partner_recap`

**Comment by hackartisan** [comment]
Here's an example of a commit where I did this: https://github.com/pulibrary/bibdata/commit/99ea15f79478d50bcfe35896fe8278f806daa203

**Comment by christinach** [comment]
closed by #1451
