### ISSUE TITLE
Ensure only one incremental indexing job can run at a time

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1348]
Proposal:

- Add a column `index_status` to the table
- When a job queues, check all incremental record dumps with index status other than "done". If any of them have an event with start date before mine, re-queue myself without running.
- When an incremental index job finishes, update `index_status` to "done"

This will prevent the second incremental index job (6 hours or less after launch) from running while the first (a full dump, will take about a day) is still going. It will also prevent similar scenarios in the future, should any given incremental job happen to be large enough to present this issue. And it will set us up for increasing our incremental publishing job to run once every hour if we decide we want or need that.

**Comment by eliotjordan** [comment]
One solution is:
https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#custom-errors
https://github.com/mperham/sidekiq/issues/3975

But we don't have an Enterprise license
 
jroch (ever-present) suggests using the ActiveJob API. Seems like a good option:
https://blog.eq8.eu/til/retry-active-job-sidekiq-when-exception.html#activejob-retry

**Comment by eliotjordan** [comment]
We might also want to try something like https://github.com/mhfs/sidekiq-failures for better visibility of failed jobs.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/bibdata/compare/alma...issues-1348-jrgriffiniii-index-once?expand=1 tracks my progress with this. The test suite should be passing, but I was encountering a number of repeated failures.

**Comment by jrgriffiniii** [comment]
This should be resolved with #1406
