### ISSUE TITLE
Bibdata: use the cloud instead of a samba share from the worker box

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1353]
for the `/data/marc_liberation_files` directory.

**Comment by hackartisan** [comment]
@kayiwa says we are trying to move away from this approach.

**Comment by tpendragon** [comment]
Can we chat about that? I'm curious why

**Comment by hackartisan** [comment]
Sure I'll put it on Friday agenda.

**Comment by hackartisan** [comment]
New proposal to use cloud storage for this.

**Comment by eliotjordan** [comment]
ActiveStorage to S3 works well. We use it Pulmap.

**Comment by hackartisan** [comment]
Jeremy at MIT told me they use aws ftp on top of s3 so alma just puts it right in s3 for them.

**Comment by christinach** [comment]
we are testing to move from samba to nfs

**Comment by kevinreiss** [comment]
Is this something we want to keep on the radar to do?

**Comment by christinach** [comment]
We're not using the cloud for now. We said that bibdata is one of the candidates to use nfs.
