### ISSUE TITLE
can not uncheck all delivery locations

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1357]
To set something to the default delivery locations, you should just be able to uncheck all the selected locations.

If you go in a choose one locations and click "Update Holding Location" 
then uncheck that same location and click "Update Holding Location"
The location stays selected if it was the only location

**Comment by carolyncole** [comment]
Go into the rails console and run this to set it to empty.
```
hl = Locations::HoldingLocation.find_by(code: 'scsbcul')
hl.delivery_locations = []
```

**Comment by hackartisan** [comment]
I think this will be obviated by https://github.com/pulibrary/bibdata/issues/1193
