### ISSUE TITLE
bibdata-worker1 will not generate gz files and will not index exisiting ones when running a rake task

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1359]
This issue came up when we switched from bibdata-worker2 -> bibdata-worker1. 
We kept the new vm (bibdata-worker1) up to date with rsync all existing files form bibdata-worker2. We also disabled the cron jobs on bibdata-worker2. 
the problems we noticed were:
1. When bibdata would create the event, the actual dump file would not exist in the vm (bibdata-worker1).
2. When running a rake task to index existing files in the vm (bibdata-worker1), the files would not be indexed.

**Comment by hackartisan** [comment]
@christinach shall we close this since we're about to move to the new infrastructure?

**Comment by hackartisan** [comment]
oops I pushed the wrong button -- just meant to ask!

**Comment by christinach** [comment]
Yes we can close it.
