### ISSUE TITLE
Step through browse list generation and document for go-live

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1362]
We'll need to know exactly what steps to execute and how long we expect each to take.

This is blocked until we have a full index on the alma-qa site.

**Comment by tpendragon** [comment]
Current strategy:

This takes two commands. My strategy to get a total time is to do the following:

1. `time bundle exec rake browse:all`
2. `time bundle exec rake browse:load_all`

then add them together. If they both go fine, and there's still time, I'll try `time /bin/bash -c "bundle exec rake browse:all && bundle exec rake browse:load_all`
