### ISSUE TITLE
Set on_reserve flag to correct value

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1363]
I did a search in alma for `where (In temporary location equals "Yes")` and found this item that is in a reserve location - https://catalog-alma-qa.princeton.edu/catalog/99106282523506421

I then looked that item up in bibdata:
https://bibdata-alma-staging.princeton.edu/bibliographic/99106282523506421/holdings/22158920250006421/availability.json

You can see the on_reserve in the metadata is `N`, not `Y`

There are a few use cases here:
- requests: on-reserve items cannot be requested
- show page: on-reserve items should not have a request button

Additional investigation is needed for both:
- For requests we should be able to use the info we get from the item-level API.
- For the show page we likely want to use the location code, either by adding a new flag to the locations table or by doing an API lookup to Alma's location endpoint. Either way we prefer to hold the logic in bibdata, not requests or orangelight. 

The alma locations API returns this information in the “fulfillment_unit” key. Value would be “reserves”. Mark will follow up to ensure the list of reserves locations is correct.

**Comment by hackartisan** [comment]
@carolyncole the reserves listing has been removed from orangelight and at one point it looked like the alma reserve feature may not be used so we just hard-coded that to 'N' for everything. I'll check on this.

**Comment by hackartisan** [comment]
@carolyncole I assume you're asking because it's used in Requests?

**Comment by carolyncole** [comment]
Yes, it is used in requests.  We use it to check and see if a person can request a copy.  If it is on reserve is should not be able to be requested for pickup.

**Comment by hackartisan** [comment]
We expect some use of alma reserves in the fall; I updated the description.

**Comment by hackartisan** [comment]
This is a lower priority right now because there won't be any reserves yet at go-live.

**Comment by kevinreiss** [comment]
another example https://bibdata-alma-staging.princeton.edu/bibliographic/9931973043506421/holdings/22185253590006421/availability.json

**Comment by christinach** [comment]
{
"code": "vidlr",
"name": "vidlr: Video Lib Res",
"external_name": "Video Library Reserve",
"type": {
"value": "OPEN",
"desc": "Open"
},
"remote_storage": "",
"map": "",
"suppress_from_publishing": "false",
"fulfillment_unit": {
"value": "Reserves",
"desc": "Reserves"
},
"accession_placement": {
"value": "none",
"desc": "None"
},
"call_number_type": {
"value": "",
"desc": null
},
"link": "https://api-na.hosted.exlibrisgroup.com/almaws/v1/conf/libraries/firestone/locations/vidlr"
