### ISSUE TITLE
Alma Delivery location supplied in a holding location should include the library code

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1376]
Alma required a library code like 'firestone' for delivery.  The data returned by  https://bibdata-alma-staging.princeton.edu/locations/delivery_locations.json includes a location code.  But the delivery location returned as part of a holding location does not https://bibdata-alma-staging.princeton.edu/locations/holding_locations/firestone$stacks.json

The location code is needed by alma to get the correct pickup information.  Could it please be returned in the first URL

**Comment by carolyncole** [comment]
Never mind...  I got Recap GFA locations and Alma locations confused.  I am assuming the library in the delivery locations matches what alma wants.

**Comment by kevinreiss** [comment]
Would it possible to have each delivery location returned with a holding location look like this?

```
{
  "label": "Stacks",
  "code": "firestone$stacks",
  "aeon_location": false,
  "recap_electronic_delivery_location": false,
  "open": true,
  "requestable": true,
  "always_requestable": false,
  "circulates": true,
  "remote_storage": "",
  "library": {
    "label": "Firestone Library",
    "code": "firestone",
    "order": 0
  },
  "holding_library": null,
  "hours_location": null,
  "delivery_locations": [
    {
      "label": "Firestone Library",
      "address": "One Washington Rd. Princeton, NJ 08544",
      "phone_number": "609-258-1470",
      "contact_email": "fstcirc@princeton.edu",
      "gfa_pickup": "PA",
      "staff_only": false,
      "pickup_location": true,
      "digital_location": true,
      "library": {
         "label": "Firestone Library",
          "code": "firestone",
          "order": 0
      }
  ]
}

**Comment by kevinreiss** [comment]
The library "code" attached to each delivery location is what Alma expects as the string submitted in a hold request.

**Comment by christinach** [comment]
Yes it is possible. I will add it. Thank you for the example.

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/locations/issues/89 , https://github.com/pulibrary/bibdata/pull/1414
