### ISSUE TITLE
Translate some item status values

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1380]
In the requests endpoint, translate the following statuses:
- “Acquisitions and Cataloging” to “In Process”
- “Acquisition” to “On order”

Get confirmation from @mzelesky that these are the correct values to translate from.

**Comment by carolyncole** [comment]
@hackartisan Why make this translation now.  We have already written code to deal with them as Aquisition...

**Comment by hackartisan** [comment]
@carolyncole I thought this was coming from y'all! Kevin brought this to our checkin today.

The discussion landed on these because they are the phrases currently used in production and seem clearer for users.

**Comment by kevinreiss** [comment]
Perhaps we should just handle the display language of these two use cases (On Order and In Process - to use their Voyager terms) for users in the request app. When the forms are constructed we already provide special labeling discussing expectations around these two request types that mention these request types. We can discuss tomorrow.

**Comment by kevinreiss** [comment]
<img width="1587" alt="Screen Shot 2021-06-02 at 4 56 48 PM" src="https://user-images.githubusercontent.com/278825/120557452-8e65b000-c3c3-11eb-9c58-a5bc652180b0.png">

For discussion here is how the form currently looks in the UI in a local env.

**Comment by kevinreiss** [comment]
<img width="1604" alt="Screen Shot 2021-06-02 at 5 06 15 PM" src="https://user-images.githubusercontent.com/278825/120558344-ebae3100-c3c4-11eb-8ab2-f6b4dda0d565.png">

this is an "Acquisitions and Catalog" Alma status that was formerly known as "In Process."

**Comment by hackartisan** [comment]
👍🏻
