### ISSUE TITLE
On order items are being marked as available

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1381]
See the very last item in this list: https://bibdata-alma-staging.princeton.edu/bibliographic/9939075533506421/holdings/22194161030006421/availability.json

It is an item that is on order.  I do not believe its status should be Available.  Is there a reason it is marked as available?

**Comment by kevinreiss** [comment]
Also the case for "In Process" items https://bibdata-alma-staging.princeton.edu/bibliographic/99122455086806421/holdings/22477860740006421/availability.json

In Voyager "On-Order" = Alma "Acquisition"
In Voyager "In Process" = Alma "Acquisitions and Cataloging"
