### ISSUE TITLE
Some ReCAP locations are not showing up with the remote_storage flag

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1385]
I have noted that `recap$pf` and `recap$pj` do not have the remote storage flag.  Can this data be refreshed from Alma once alma has been updated.  I believe @pdiskin and @pmgreen  are working on the updates to Alma

**Comment by pmgreen** [comment]
@carolyncole we are working on this now.

**Comment by christinach** [comment]
ok so I should wait and not update them in bibdata until you tell me.

**Comment by pmgreen** [comment]
@christinach PF and PJ have been added as Remote Storage Locations.

**Comment by christinach** [comment]
Thank you!

**Comment by christinach** [comment]
closed by #1386
