### ISSUE TITLE
uninitialized constant Faraday::Error::ConnectionFailed

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1391]
The error "uninitialized constant Faraday::Error::ConnectionFailed" is obscuring other errors and can be resolved by updating rsolr

https://github.com/rsolr/rsolr/compare/v2.1.0...master

Most recent honeybadger error was: https://app.honeybadger.io/projects/54497/faults/79785330

**Comment by hectorcorrea** [comment]
Issue is still happening, Honeybadger reported it last as of 6/9/2021 @ 7:00 AM: https://app.honeybadger.io/projects/54497/faults/79785330

**Comment by hectorcorrea** [comment]
As @hackartisan predicted, after this fix was deployed to the server we get a little bit more information on the error, the new Honeybadger alert is https://app.honeybadger.io/projects/54497/faults/79881407 and it includes the following information:

```
RSolr::Error::Http: RSolr::Error::Http - 404 Not Found
Error:     Not Found

URI: http://lib-solr8-prod.princeton.edu:8983/solr/catalog-alma-production-reindex/update?wt=json
Request Headers: {"Content-Type"=>"application/json"}
Request Data: "{\"delete\":[]}"
```

Notice that the delete dataset is empty (and malformed?). This should not result in a 404, though. But, this looks like progress :D

**Comment by hackartisan** [comment]
moving the new info to #1411 and closing this!
