### ISSUE TITLE
Update the label in the availability.json to pull information from the bibdata holding location label

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1409]
The orangelight search results uses the JS api call for the location display. 
 location display = library name + location description.
`"location": {"location": {
                "value": "cjk",
                "desc": "cjk: East Asian Library"`
The `location desc` is equivalent to the AVA subfield | `c| cjk: East Asian Library`  (example: https://catalog-alma-qa.princeton.edu/catalog/99117665883506421/staff_view ). This is what comes back with the JS call https://bibdata-alma-staging.princeton.edu/bibliographic/99117665883506421/availability.json. It is not the Alma `external_name` value as we initially thought. 

In https://bibdata-alma-staging.princeton.edu/locations/holding_locations we use the alma `external_name` value in the holding location `label` and not the `location desc`.

The search results page in Orangelight will first display the location after retrieving the information from bibdata and concatenating a string. Then the JS call will replace the location display with the information that is coming from the availability.json response. 
The issue became more obvious when the alma `external_name` (in the alma backend) was updated to blank and the location display changed for some records between the bibdata call and the JS call. 

- We should update the availability.json response, to have a holding_location.code lookup and update the holding_location_label https://github.com/pulibrary/bibdata/blob/9c5f90f469a051b631d699fe9f0db240022cef1b/app/adapters/alma_adapter/availability_status.rb#L48 with the bibdata.holding_location.label value (which is the alma external_name). In the future we could use for the lookup the location file that will replace the location tables.
- The other option which I'm not in favor would be to update the availability.js to have the holding_location.label lookup only for the `label`. But something like that would leave the availability.json response with incorrect information in the label field.

**Comment by hackartisan** [comment]
omg alma has too many different location formats! where are they even getting this "desc" string! Is it the value plus the external name? would stripping anything up through a colon work as desired?

**Comment by christinach** [comment]
The `location desc` string that we added as label in the availability.json is the alma location name. `“name”: “hy: East Asian Library”,`. It is a different value and has nothing to do with the external name. for example:
{“code”: “hy”,
“name”: “hy: East Asian Library”,
“external_name”: “”,
“type”: {“value”: “OPEN”,
“desc”: “Open”
},
“remote_storage”: “”,
“map”: “”,
“suppress_from_publishing”: “false”,
“fulfillment_unit”: {“value”: “General”,
“desc”: “General”
},
“accession_placement”: {“value”: “none”,
“desc”: “None”
},
“call_number_type”: {“value”: “”,
“desc”: null
},

**Comment by hackartisan** [comment]
Thanks for sorting through this. Pulling the value from the location table seems reasonable to me.

**Comment by christinach** [comment]
@mzelesky should I update the label on the availability item level as well. It also takes the location desc and if it is a temp_location it takes the temp_location desc. If yes I will open another issue.

**Comment by christinach** [comment]
closed by #1410
