### ISSUE TITLE
figgy holding_locations will break on go-live

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1447]
The holding_locations in figgy use bibdata URIs from the delivery_locations table. The IDs aren't the same between old bibdata and new. Not sure if the entries are otherwise the same.

Need a migration plan here.

**Comment by tpendragon** [comment]
Thoughts:

* Can we redirect from old to new? (I'm not sure if Figgy will follow those redirects or not...)
* Can we actually force the IDs to be the same?

I'm running a query now to see how many there are in Figgy if it turns out we have to migrate all of these there.

**Comment by tpendragon** [comment]
We're going to try importing these locations again. If delivery locations are automatically generated we'll try to find a way to make the IDs the same probably, if not then we can just migrate the DB from current prod for delivery locations and adjust the couple of things that are different.

**Comment by hackartisan** [comment]
Yes, they're deleted and regenerated; plasma went from being record 49 to being record 73.

**Comment by christinach** [comment]
> We're going to try importing these locations again. If delivery locations are automatically generated we'll try to find a way to make the IDs the same probably, if not then we can just migrate the DB from current prod for delivery locations and adjust the couple of things that are different.

One potential issue is that as long as we have to regenerate the locations for any alma back end change the location id will change and if figgy continues to rely on that it will break.

**Comment by christinach** [comment]
Unless the ids stay the same as you said.

**Comment by christinach** [comment]
closed by #1460
