### ISSUE TITLE
Availability API Extension 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#145]
Extend the existing availability API that supports the end-user recommended display of availability information in applications that index library data. The existing API provides the raw data but relies on the availability.js script in OL to render the data. This extension should send send back html that can be easily embedded on a page using basic javascript. This extension should support both the "brief" (i.e search results) and "full" (the show page) views of availability information we display in OL. It is expected that any client application will at least be able to embed the bib ID and if a Voyager-derived record the mfhd ID. A client application's HTML could look like this:

```
<div class="availability--brief" data-pul-id="123242234""></div>

<div class="availability--full" data-pul-id="1232324">
    <div class="availability--mfhd" data-mfhd-id="2345"></div>
    <div class="availability--mfhd" data-mfhd-id="4345"></div>
</div>
```

A call to the availability API with some basic javascript should populate them with the appropriate HTML. Moving whatever we want to display for availability in these two contexts will ensure a consistent display and consistent application across client applications. Likely clients are the "Bento Box", main catalog, getit.princeton.edu, and various local branch library custom displays of data in pulsearch.

**Comment by tampakis** [comment]
From @kevinreiss 
> If we do go the route of expecting an availability response for a Voyager holding to toggle the request button basically I would expect the response would be a link to the preferred method of fulfilling the request [basically stackmap or the request form] and an appropriate label.

Also, we should think about how we handle the non-voyager ids (theses, visuals, soon recap). Should marc_liberation provide an availability response for them or should the logic for which label to display continue to live in the OL application helper>

**Comment by kevinreiss** [comment]
We have some idea of how the ReCAP middleware application will fit into availability now. It looks like we will need to depend on the middleware for the most current status of our *own* recap holdings in addition to depending on it for availability for the partner items from Columbia and NYPL that we'll add to the OL index. 

The two main complications that seem to be presented by this are:

1. On the "results" page we are going to have to process multiple holding items that include a ReCAP location differently than we do now. We might want to just fall-back to some variation of "check show page for details" in order to avoid the complication of trying to produce a real-time result for these items. For ReCAP items with a single holding we'll need to depend on a second call via JS to the middleware API to fetch availability.
2. On the show page we'll need to execute a holding level lookup for availability via the middleware API for items with holdings at ReCAP.

Our bib, holdings, and item IDs are being sent to the middleware system but right now the barcode is the lookup key for any data in the system.  I advised the HTC group that ideally being able to lookup availability by bib and holdings ID would be best for us but details will be forthcoming.
