### ISSUE TITLE
Check and document figgy's use of delivery locations

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1450]
Figgy references these by uri (i.e. by database id). They can't be deleted without checkin figgy first.

Some have been deleted as duplicates. We should:
- Pull a database backup from before these deletions happened if still available on google cloud backup.
- Search figgy to see if any of the deleted ones were in use and report counts, ids.
- Document in bibdata that these can't be deleted. Where would someone about to delete one be most likely to see such a message?

**Comment by christinach** [comment]
can you provide the honeybadger error that lead to this discovery?

**Comment by christinach** [comment]
I did a quick search https://github.com/pulibrary/figgy/blob/1a909ccf5b03f3f2dbdf5f6c56e5396c9df11e2e/app/decorators/scanned_resource_decorator.rb#L38-L45
and I see that it's trying to load the label from the holding_location. Why do we save the delivery location in the database if we can get the label from the holding location. @tpendragon

**Comment by christinach** [comment]
ok I see you save everything that comes from the holding locations in the db. That would mean that figgy will be broken when we launch alma since the locations are different.

**Comment by tpendragon** [comment]
There's only 12k of these in Figgy, it's probably faster to just pull them all and find the ones that are used but not in delivery_locations.json.

**Comment by tpendragon** [comment]
```
figgy_production=# SELECT metadata->'holding_location'->0, COUNT(*) FROM orm_resources WHERE metadata @> '{"holding_loc
ation": [{}]}' GROUP BY metadata->'holding_location'->0;
                                 ?column?                                 | count
--------------------------------------------------------------------------+-------
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/7"}  |    81
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/5"}  |     1
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/33"} |    42
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/15"} |     1
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/8"}  |     1
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/14"} |     1
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/13"} |  1844
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/4"}  |   158
 {"@id": "https://bibdata.princeton.edu/locations/delivery_locations/9"}  |  9777
(9 rows)
```

**Comment by tpendragon** [comment]
Of these only "33" is missing.

**Comment by tpendragon** [comment]
33 used to be:
```
33	Engineering Library Off-Site Storage	Friend Center for Engineering Education, Princeton, NJ 08544	 609-258-3200	 englib@princeton.edu	f	2018-04-18 20:53:16-04	2018-04-18 20:55:58-04	5	PT	f	t

```

**Comment by tpendragon** [comment]
The migration's done. Best place to document this, @christinach ? Top of that holding_locations.json file?

**Comment by christinach** [comment]
@tpendragon yes. I think you meant delivery_locations.json ?
