### ISSUE TITLE
Refactor DumpType into Single Table Inheritance on Dump

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1453]
Steps:
- Create a new 'type' column on the Dump model and populate it with strings from the dump_type property.
- Create objects such  as PartnerRecapDump using STI.
- Rewrite code to use these objects
- Delete DumpType table / model

Future ticket: rinse and repeat (DumpFileType)

**Comment by christinach** [comment]
STI : single table inheritance
