### ISSUE TITLE
SCSB Delete Directory is wrong

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/bibdata#1466]
It's `data-exports/PUL/Json/Incremental` right now, but all the files right now are in `data-exports/PUL/Json`.

Change it in princeton_ansible.

**Comment by hackartisan** [comment]
@kevinreiss this is what we found while working on another ticket -- does it match your understanding? Any knowledge of this change?

**Comment by kevinreiss** [comment]
No, I'd have to ask the vendor.

**Comment by kevinreiss** [comment]
@hackartisan based on some info I found from the vendor I think we can use ```data-exports/PUL/Json``` safely.
