### ISSUE TITLE
Parallelize indexing

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1469]
Can we make better use of our compute power by running each dumpfile in a background job? Without doing this, we have three workers and we’ll end up indexing with just one of them.

Note that one complication here is the new database column we have to mark when a dump is finished being indexed, so that 2 incremental update dumps aren't running at the same time.

[Notes from discussion](https://docs.google.com/document/d/1sq_DmkRVLWEQdwf0YY1Dl3KGYlPd_0ldCYYc6PTcOuY/edit#heading=h.2ayq9fwrwuhp):
- We have questions about whether a single worker is maxing out a worker box, and if not, would we see gains by running more than one worker per box in this scenario or would we not get those gains via the way sidekiq does threads?
- Or would we want to limit sidekiq workers per machine to just 1?

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/bibdata/pull/1493
