### ISSUE TITLE
Index item data to provide more granular availability information and reduce use of alma API

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1473]
Many statuses can be sent from the publishing job. But the publishing job cannot contain the worker order type. It will only say "work order".

So we can index many statuses currently used for availability.

For CDL items this can reduce the number of items we have to do the API call on, but it can't get rid of the API call completely.

There are about 76,000 bibs on work orders.

If we schedule hourly incremental updates and accept this delay for availability information, we could get finer-grained availability values and reduce our use of the alma API.

other related tickets: 
- https://github.com/pulibrary/bibdata/issues/1198
- https://github.com/pulibrary/bibdata/issues/1005

**Comment by kevinreiss** [comment]
@christinach we do actually index this data now for PUL records now, though we do not actually use it. Can I close this ticket?

**Comment by christinach** [comment]
We can close it. Additionally for CDL we are moving towards implementing and using the digital inventory.
