### ISSUE TITLE
Cleanup the recap$ locations and set the Alma recap_edd flag  correctly

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1498]
The recap_edd flag is always set to false.  It should be set to true in many recap locations.  

Here are the old location where recap_edd is set to true: etasrcp, rcpgp, rcpjq, rcppa, rcppb, rcppj, rcppk, rcppn, rcppq, rcppt, rcppw, rcpxw, scsbcul, scsbnypl

**Update**
The new locations are something like mendel$pk NOT recap$pk as is set up in bibdata.  The recap$ locations exist AND the mendel$ locations exists.  The flags are set correctly on the recap$ locations, but not on the mendel$ ect locations.  The recap$ locations should be purged and the new locations should have the correct flags set.

**Comment by christinach** [comment]
@carolyncole I checked https://bibdata-alma-staging.princeton.edu/locations/holding_locations and the recap locations you listed plus the scsbcul, scsbnypl have 'Recap EDD': true.

**Comment by christinach** [comment]
same for https://bibdata-alma.princeton.edu/locations/holding_locations

![Screen Shot 2021-07-08 at 9 43 33 AM](https://user-images.githubusercontent.com/9905193/124932346-ff0a7880-dfd0-11eb-9236-352303a8c2c8.png)

**Comment by carolyncole** [comment]
To bring this back in from slack.  The old recap$ locations for items in libraries should be removed.  They are no longer in use.  For instance recap$pk is now in alma as mendel$pk.  medel$pk has the recap edd flag set incorrectly.

@mzelesky and ideas on how to map between the old rcppk and the new locations?  It seems like it is just replace rcp with the correct library so if I am right the ones that need the edd flag set correctly would be

 rcpgp => firestone$gp , rcppb => firestone$pa, rcppj => marquand$pj, rcppk => mendel$pk, rcppn => lewis$pn, rcppq => plasma$pq, rcppt => engineering$pt, rcppw => architecture$pw, rcpxw => rare$xw

not sure how rcpjq, rcppa translate since they are just recap locations not related to a library.

**Comment by christinach** [comment]
@mzelesky @kevinreiss  if there is a mapping please update this issue with a translation map https://github.com/pulibrary/bibdata/issues/1199

**Comment by kevinreiss** [comment]
Mapping is at https://docs.google.com/spreadsheets/d/1LKypZZQNu3zy2lSZf_V-QgoV5FfZcILUrlk8BfRDqRM/edit#gid=0. I added column that says if the location is eligible for EDD at ReCAP.

**Comment by christinach** [comment]
@kevinreiss does this mean that alma records with location recap$pk are moved/updated to mendel$pk or will they keep both locations? 
I can't understand from https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=recap%24pk&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search (4,025 records) and https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=mendel%24pk&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search (138 records) because the index is older.
I can try to do a search in alma.

**Comment by christinach** [comment]
I might have down the wrong search but I looked for physical items with base status in mendel$pk https://princeton.alma.exlibrisgroup.com/ng/page;u=%2Frep%2Faction%2FpageAction.search.physical_item_results.xml.do%3FxmlFileName%3Dsearch.physical_item_results.xml&RequestBeanClassName%3Dcom.exlibris.repository.web.search.RepositorySearchBean&pageViewMode%3DEdit&pageBean.advancedSearchPerformed%3Dtrue&pageBean.searchMode%3DAdvanced&pageBean.securityHashToken%3D4900755837146601384 and it returned 349

and physical items with base status in recap$pk and it returned 10,525. 

I don't think we should remove the recap$pk from the locations table. right?

**Comment by christinach** [comment]
I will update the existing mapping file https://github.com/pulibrary/bibdata/blob/alma/voyager_alma_mapping.csv with the new 'EDD allowed' column @kevinreiss added in https://docs.google.com/spreadsheets/d/1LKypZZQNu3zy2lSZf_V-QgoV5FfZcILUrlk8BfRDqRM/edit#gid=0

**Comment by christinach** [comment]
@carolyncole for now I will not remove the recap locations because the searches I did return different numbers which means that a lot of items are in the old locations. I will move forward to update the flags of the new locations.

**Comment by christinach** [comment]
I will use the updated file that @mzelesky updated 2 weeks ago https://docs.google.com/spreadsheets/d/18YCL_PoGMjybNHplVpVhdk-fEgPrTHHxU2VvNcpOTBI/edit#gid=0 to regenerate the locations file. 
@mzelesky said that I can remove recap$pk (old recap locations) since all the items will be up to date on July 26th. Thanks @mzelesky .

**Comment by christinach** [comment]
Based on the updated file that @mzelesky provided and the updated list that @carolyncole and @kevinreiss provided for the recap_edd: true, the mapping for the new recap locations and recap_edd:true is:
1. rcpgp -> recap$gp,  
2. rcpjq -> recap$jq
3. rcppa -> recap$pa
4. rcppb -> firestone$pb
5. rcppj -> marquand$pj
6. rcppk -> mendel$pk
7. rcppn -> lewis$pn
8. rcppq -> recap$pq
9. rcppt -> engineer$pt
10. rcppw -> arch$pw
11. rcpxw -> rare$xw
12. etasrcp -> online$etasrcp
13. scsbcul (partners not alma)
14. scsbnypl (partners not alma)
15. scsbhl (partners not alma)

**Comment by christinach** [comment]
This is a screenshot from my local:
![Screen Shot 2021-07-08 at 9 55 19 PM](https://user-images.githubusercontent.com/9905193/125011866-3c095600-e037-11eb-8596-9341e609bb27.png)

**Comment by christinach** [comment]
There was a discussion with @kevinreiss about the holding_library column and if it's still needed or if we can remove it. It might be used in the requests gem. Something to look into.

**Comment by carolyncole** [comment]
@christinach I just noted that the holding library was no longer set for the new locations: https://github.com/pulibrary/requests/issues/1021. It is definitely causing bad behaviors to not have it.  I spot checked a couple of locations from your screen shot and they look the same as production bibdata (minus the names).

**Comment by christinach** [comment]
I was wondering if we can use location[:library][:code] since the name of the library and the holding_library is the same in the new locations.

**Comment by christinach** [comment]
But we can definitely keep it as it is having both 'library' and 'holding_library' and maybe do these changes in the future. 
My thought was more about that the holding_library as a concept does not apply any more in the new locations with remote_storage.

**Comment by carolyncole** [comment]
@christinach since we have to support both the old and the new locations currently, it would be simpler to keep it for now.  Then remove it after we go live and everything is in its new location.

**Comment by christinach** [comment]
I will keep the old recap locations to be safe; And we will remove them after we go live.

**Comment by kevinreiss** [comment]
I agree, let's keep these through the migration to have a contingency if items don't migrate exactly as we think they should to the new remote_storage locations.

**Comment by christinach** [comment]
closed by #1503
