### ISSUE TITLE
Call number browse not finding CD- 50000

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1505]
https://catalog-alma-qa.princeton.edu/browse/call_numbers?search_field=browse_cn&q=CD-+50000 gives no results; this search gives results in catalog.princeton.edu

The record is in the qa catalog: https://catalog-alma-qa.princeton.edu/catalog/99103141233506421

Reported by Brian Newhouse; follow-up requested.

**Comment by tpendragon** [comment]
I suspect this is because of https://github.com/pulibrary/orangelight/issues/2532. We didn't run call number generation again afterwards because we were going to do it when we generate the QA index.

**Comment by hackartisan** [comment]
Okay let's go ahead and run it since we don't have the new index yet.

**Comment by christinach** [comment]
I think it is a sorting problem. The call number is in the browse lists but when you clink on browse related items it takes you to somewhere else. https://catalog-alma.princeton.edu/catalog/99103141233506421

while you can see the call number : https://catalog-alma.princeton.edu/browse/call_numbers?start=942449

**Comment by christinach** [comment]
I'm not sure if it is related to this issue. I haven't looked into it https://github.com/pulibrary/orangelight/issues/2480

**Comment by christinach** [comment]
@tpendragon mentioned the issue with the space at the end. This is the case again with this one. It has a space at the end.

**Comment by hackartisan** [comment]
Running the browse lists didn't resolve this issue. the branch deployed when I ran it was from July 6th, which post-dates the space-stripping PR. I'll redeploy and run just the call number generation again and look into this more while it's running.

**Comment by hackartisan** [comment]
Terminal spaces are still present in the csv load file

**Comment by christinach** [comment]
I think it would be better to handle this in bibdata in traject. We have a similar issue that involves more fields but maybe we can fix the space issue there https://github.com/pulibrary/bibdata/issues/1517.

**Comment by christinach** [comment]
or in a separate issue

**Comment by christinach** [comment]
closed by #1528

**Comment by hackartisan** [comment]
I think we should leave this open until we're re-run browse lists on qa and notified the user who reported it.

**Comment by christinach** [comment]
Since we cant use catalog-alma-qa for a while, I tested this locally running browselists with the fix.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/9905193/126713220-7ef8e7b9-371e-45d6-9f06-b2dd0df753b8.gif)

**Comment by christinach** [comment]
I followed up with Brian.
