### ISSUE TITLE
Index all incremental dumps created since the most recent full dump 

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1518]
This would ideally happen as part of the full dump task, but if all the dump files are backgrounded we don't want to risk any of the incrementals running before the fulls so that may not work.

Make sure to update indexing documentation as part of this.

## Technical Implementation

An IndexManager to coordinate indexing alma full and incremental dumps.

```
class IndexManager < ActiveRecord::Base
  solr_collection string
  dump_in_progress foreign key (tentative)
  last_dump_completed foreign key

  # returns the active IndexManager for the given collection
  def self.current(solr_collection)

  # finds and indexes the next incremental dump. no-op if there's a dump_in_progress.
  def next_incremental
```

Running a new full index on catalog-alma-rebuild:
  - Delete `last_dump_completed` from current Index Manager for the rebuild collection
  - empty the rebuild index via the solr API
  - queue up the initial full dump
  - when a full dump finishes
    - adds the dump to last_dump_completed
    - it calls IndexManager.current(collection).next_incremental
    - the full dump index jobs will have to store a reference to the index manager or the collection they're going into for this to work.
    - sidekiq batches make an action like this possible via the batch callback

Swapping the rebuild index into production use
  - Change the solr_collection value
  - do the alias swap via the solr API
  - Alternative: don't use the alias as the solr_collection value? This means we may need to look up what the alias is pointing to using the solr API pretty frequently.

Ensuring all incrementals get indexed, and in the correct order
  - When a new incremental file gets transferred from sftp, call next_incremental on the configured primary `SOLR_COLLECTION`
  - When any incremental file finishes indexing, call next_incremental on the collection it indexed into
    - sidekiq batches make an action like this possible via the batch callback

Instead of configuring `SOLR_URL` and `SOLR_REINDEX_URL` in env, we configure `SOLR_BASE_URL`, `SOLR_COLLECTION`, and `SOLR_REINDEX_COLLECTION`.

**Comment by tpendragon** [comment]
Yeah we can't have one incremental run before another either. To handle this I think we'd have to either check to make sure there aren't started DumpFiles from an earlier dump enqueued or have some sort of managing coordinator in the database.

**Comment by hackartisan** [comment]
Hm. A managing coordinator in the database seems tricky when you want to manage building a new index on catalog-alma-rebuild. A given incremental file may have been indexed into the live prod index but not into the rebuild index, or vice-versa.

**Comment by hackartisan** [comment]
Here's a proposal for an IndexManager to coordinate indexing alma full and incremental dumps.

```
class IndexManager < ActiveRecord::Base
  solr_collection string
  dump_in_progress foreign key
  dumps_complete [foreign key]
  active boolean

  # returns the active IndexManager for the given collection
  def self.current(solr_collection)

  # finds and indexes the next incremental dump. no-op if there's a dump_in_progress.
  def next_incremental
```

Running a new full index on catalog-alma-rebuild:
  - Set current rebuild manager to active:false
  - empty the rebuild index via the solr API
  - create a new IndexManager for the rebuild collection and set it to active
  - queue up the initial full dump
  - when a full dump finishes, it calls IndexManager.current(collection).next_incremental
    - the full dump index jobs will have to store variable for the collection they're going into for this to work.
    - sidekiq batches make an action like this possible via the batch callback

Ensuring all incrementals get indexed, and in the correct order
  - When a new incremental file gets transferred from sftp, call next_incremental on the configured primary `SOLR_COLLECTION`
  - When any incremental file finishes indexing, call next_incremental on the collection it indexed into
    - sidekiq batches make an action like this possible via the batch callback

Instead of configuring `SOLR_URL` and `SOLR_REINDEX_URL` in env, we configure `SOLR_BASE_URL`, `SOLR_COLLECTION`, and `SOLR_REINDEX_COLLECTION`.

**Comment by tpendragon** [comment]
Proposal:

See sidekiq batch example: https://github.com/mperham/sidekiq/wiki/Really-Complex-Workflows-with-Batches

Create a "super-batch" for each indexing operation.

When a Dump completes, look for any dumps after that dump and add it to the batch.

If another super-batch tries to enqueue, just fail out if one exists already.

**Comment by tpendragon** [comment]
Started playing with the batch implementation - a problem that happens is you need to keep track of which Dumps are indexed into which core to do start-stop indexing.

**Comment by hackartisan** [comment]
Not sure what stop-start indexing is, but yes. And a dump may have been indexed into a core but then that core may have been wiped, meaning it would need to be indexed again.

**Comment by hackartisan** [comment]
The description has been updated with the current plan; we'll keep it updated there.
