### ISSUE TITLE
Patron route fails to load patrons without a net ID

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1520]
We will (at some point) have patrons who don't have net IDs who will be allowed to make requests again. The patron route produces an error if you pass a barcode value over to the patron route. In prod

https://bibdata.princeton.edu/patron/{barcode}

in alma

https://bibdata-alma-staging.princeton.edu/patron/{barcode}

produces a 500 error for a barcode that return a valid result.  Ping me for a valid test barcode for a patron of this type.

**Comment by kevinreiss** [comment]
@hackartisan can we make this one a priority this month, I think we will need to start using this relatively soon.

**Comment by christinach** [comment]
if we don't get to it in this cycle I put it in the backlog for the next one.
