### ISSUE TITLE
Rake task to request full partner records from SCSB API

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1544]
It would remove a bottleneck on Kevin to have this as a rake task. 

The API accepts an email address to report when the export to s3 is finished. Maybe use the drds libanswers email address.

**Comment by kevinreiss** [comment]
Write-up of API calls when we find time for this https://docs.google.com/document/d/175SVaJ_7p7L4DYJ4H7-HvBH6WS4Y3gFGUIaw81TnT8Y/edit

**Comment by kevinreiss** [comment]
The rake task should accept a flag that states which SCSB environment to request the data from, uat or production.
