### ISSUE TITLE
Index a defined set of topics under "Indigenous Studies" to boost their visibility

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#1548]
![Screen Shot 2021-09-29 at 11 25 41 AM](https://user-images.githubusercontent.com/65608/136403275-ec6f74c7-a0cb-4c86-af23-cee3bf3d3441.png)

![Screen Shot 2021-10-05 at 11 54 28 AM](https://user-images.githubusercontent.com/65608/136403223-715d931d-1c98-453f-a7ac-d03f0f1af23d.png)

Related to #595 

Index topics in [this list](https://docs.google.com/spreadsheets/d/1Y_GdQi7-VPdSzpgLk3Phn2IR6tst-dTO/edit#gid=714979645) to be discoverable under the "Indigenous Studies" keyword search to boost their visibility. 

Example: [This search](https://catalog.princeton.edu/?f%5Bsubject_topic_facet%5D%5B%5D=Kootenai+language&q=Kootenai%20language&search_field=subject) for "Kootenai language" with "Subject (Browse)" selected from the search dropdown should be discoverable under the term "Indigenous Studies" searched from the keyword dropdown.

This will build on #595 and may require a one-to-many term mapping, depending on the approach to #595.

**ACCEPTANCE CRITERIA**
- [x] Bibdata has a list of terms that trigger the addition of "Indigenous Studies"
- [x] At index time, this term gets added to lc_subject_facet, lc_subject_display, and subject search fields
- [x] I can search for "Indigenous Studies" in the "Subject (Keyword)" drop down and retrieve these records
- [x] I can use the "Subject > Topic" facet to limit to "Indigenous Studies" and retrieve these records
- [x]  Add a flag CHANGE_THE_SUBJECT. If there is this env variable then this code will change.
- [x] Test this in staging

**Comment by minjiec** [comment]
Background information of the 2400~ terms in the spreadsheet:
- The terms are extracted from the LCSH database
- are about "the indigenous peoples of the Western Hemisphere, including Eskimos"
- but restricted to those organized hierarchically under the umbrella heading "Indians"
- and go only two levels deep.

Related projects:
1.	A [count](https://docs.google.com/spreadsheets/d/1CoJdjimDBP_Iys1_xW1aw0d6EolJ7Sd0rRqBgMKoyUw/edit#gid=971920615) of how many titles PUL has for each subject heading (left-match) as of August 2021
2.	A Cotsen project that adds 650 #0 Indians to [every record](https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f%5Bsubject_facet%5D%5B%5D=Indians&f1=all_fields&f2=author&f3=title&op2=AND&op3=AND&q1=&q2=&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&search_field=advanced&sort=pub_date_start_sort+asc%2C+title_sort+asc%2C+score+desc&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=rare%24xc&f_inclusive%5Badvanced_location_s%5D%5B%5D=rare%24ctsn&f_inclusive%5Badvanced_location_s%5D%5B%5D=rare%24ctsnrf&f_inclusive%5Badvanced_location_s%5D%5B%5D=rare%24hsvc&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=pub_date_start_sort+asc%2C+title_sort+asc%2C+score+desc&search_field=advanced&commit=Search) identified as being related to the topic of Indians, for easy retrieval
