### ISSUE TITLE
Review Lewis library external name in Alma

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1556]
Some of the Lewis locations have the library name in the external name. Review if some can be updated so that we avoid the library name repetition in the string. 
old issue: https://github.com/pulibrary/bibdata/issues/1282

If there are any location updates in Alma, please open a follow up ticket in bibdata so that we update the locations tables.

@mzelesky

**Comment by pmgreen** [comment]
@christinach `Lewis `, `Lewis Library: ` and `Lewis Library (SCI): ` have been removed from the external names. (The two ReCAP locations still include 'Lewis Library Use Only'.) Please comment here if you need a separate ticket re: updating the locations tables.

**Comment by christinach** [comment]
@pmgreen thank you! I will open a ticket to update the locations table in bibdata.
