### ISSUE TITLE
Incremental Index status page

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#1562]
Per a conversation with @hackartisan; create a status page on bibdata that staff can refer to, showing the start and end dates and times of incremental indexing jobs in descending order.  The purpose of this page is to allow staff to determine when they should expect to see changes they have made to item records in Alma reflected in the catalog.

**Comment by tpendragon** [comment]
If the use case is "As a cataloguer I want to know if my changes in Alma have indexed or are actively indexing" I don't think this is a good way to solve it. We don't tend to send people to bibdata, the dumps don't contain which BibIDs are attached to them, and if they had follow-ups we'd have to do a bunch more introspection anyways.

I wonder if we can wait until we get this request? If there's a question of "did my latest change get updated" then I think I'd want that indexed into Orangelight and displayed somewhere - maybe librarian view?

**Comment by hackartisan** [comment]
yes this makes a lot of sense. it's a pretty significant feature to write in anticipation of a question we haven't gotten yet.

**Comment by hackartisan** [comment]
yes this makes a lot of sense. it's a pretty significant feature to write in anticipation of a question we haven't gotten yet.

**Comment by christinach** [comment]
We had an array of delete_ids and update_ids were we (developers) used to look for which ids were updated or deleted. https://bibdata.princeton.edu/dumps/23916.json 
However this was not always the case and we had to look deeper in the index to confirm if some of the records were truly deleted or updated. 
This would come as a request from catalogers when blacklight would not reflect the record changes in voyager. I don't think that displaying the index status would resolve this issue and provide an answer to a cataloger who wants to see their changes in blacklight; 
Maybe this 'Status' view could be a first step but if the changes are not displaying in blacklight, the second step would be to open an issue in bibdata or ask in the catalog channel. 
I do think though that we should not proceed creating this feature without having a real user request.

**Comment by hackartisan** [comment]
After discussion, this doesn't seem like the right feature.

Other thoughts included:
1. keep track of what questions we get and what we do to answer them (where?)
1. provide the last indexed time
2. log the updated IDs on a dump the way we used to

Opened https://github.com/pulibrary/bibdata/issues/1569 to track more information moving forward.
