### ISSUE TITLE
External name for marquand$pz should include the word 'RARE'

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1568]
Reported in the catalog channel from Marquand library.
example item https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&f2=author&f3=title&f_inclusive%5Badvanced_location_s%5D%5B%5D=marquand%24pj&f_inclusive%5Badvanced_location_s%5D%5B%5D=marquand%24pz&op2=AND&op3=AND&q1=&q2=&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=all_fields&q=99118491543506421

marquand$pz location should include in the location external name the word 'RARE'. 
This should be updated first in alma and then open a follow up ticket in bibdata to update the location tables.
@kevinreiss @mzelesky I'm tagging you for this issue. Thank you.

**Comment by pmgreen** [comment]
@christinach External name for marquand$pz has been changed to `Remote Storage (ReCAP): Marquand Library Use Only Rare Books`

**Comment by christinach** [comment]
Thanks! I'll open another issue to update the locations.
