### ISSUE TITLE
Indexing Alma URLs starting with "na05"

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1575]
We are indexing the un-aliased version of our Alma URLs, if we ever did have our backend system moved again by Ex Libris they would break. 

Example: https://catalog.princeton.edu/catalog/995638343506421

URLs are: https://na05.alma.exlibrisgroup.com/view/uresolver/01PRI_INST/openurl?u.ignore_date_coverage=true&portfolio_pid=53770877360006421&Force_direct=true

This is likely something we need to fix on the publishing side. These URLs really should start with princeton.alma.exlibrisgroup.com. However right now
https://princeton.alma.exlibrisgroup.com/view/uresolver/01PRI_INST/openurl?u.ignore_date_coverage=true&portfolio_pid=53770877360006421&Force_direct=true doesn't actually work. I'm going to ask Ex Libris about this since according my understanding they are supposed to take you to the same place and that the latter form is preferred.

**Comment by christinach** [comment]
This was the dead not active url. Exlibris says this will not be an issue.
