### ISSUE TITLE
Cleanup 856s in Alma

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1600]
We found with @mzelesky that there are records where the second indicator of the 856 indicated it was a full-text version of the resource, but there is a subfield 3 on the URL.

@mzelesky will search over the Voyager records he submitted in the 'Print to Electronic' migration process and find how many have 856 with the subfield 3.

I will look if I can search 856s with subfields using analytics in alma.

**Comment by mzelesky** [comment]
There are a total of 77,515 bibs that are likely mistakes from the P2E file. Of those, 9,031 only have URLs for tables of contents from the Library of Congress. I will work with Enterprise Services to experiment in the Alma sandbox to find a way to remove the portfolios from these records.

To be clear, the URLs themselves won't be removed from the records. They will just have the portfolios removed.

**Comment by christinach** [comment]
Thank you @mzelesky !

**Comment by christinach** [comment]
Closing this issue as it is a large cleanup project in Alma that will take some time to complete and not in Bibdata.
