### ISSUE TITLE
SCSB Export (submitCollection) needs to have a collection group of CGD and a use restriction change for a subset of items

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/bibdata#1624]
Change the designation for MMS-IDs in marquand$pj that are in a hash built from an excel document provided by Patty.

We can store the excel spreadsheet as a JSON file in the repository.

This has to be submitted and updated in SCSB by October 1. We'll receive the data by August 26.

**Comment by christinach** [comment]
Discussed with @mzelesky:
Submit collection cannot be implemented with this change until after October 12th. The spreadsheet of bibids has been completed. This work can begin on October 4th.

**Comment by christinach** [comment]
per @mzelesky HTC are pushing the SCSB code deployment that would allow this to work to the end of November.

**Comment by christinach** [comment]
we will not do this sidecar concept.
