### ISSUE TITLE
New Location needs to be accounted for

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1629]
I have created a new location in Alma.

firestone$secw

It is the Scribner Room: Common Works Collection.

What is needed to get this location working in Blacklight? I would like to create documentation to post on Confluence to explain all the steps needed, so future requests from selectors/etc. will be easier to manage.

Thank you,
Mark

**Comment by christinach** [comment]
We need to update bibdata and deploy the change. The changed records that will have this location will be indexed with this location code.

**Comment by mzelesky** [comment]
Ok. There are no records yet in this location. They will be ordered this week.

**Comment by christinach** [comment]
I will add the location now so that it is ready. 
The preferred steps would be to inform the DRDS team of the new location first. We add the location, deploy it to production and then the records are added in the backend.

**Comment by christinach** [comment]
From slack after communicating with @mzelesky and @carolyncole:
Will replicate the flags as in firestone$seref location

![Screen Shot 2021-08-23 at 3 00 20 PM](https://user-images.githubusercontent.com/9905193/130502873-2ebf2c03-1b00-4087-b4c2-eb10dffbb4ef.png)

**Comment by christinach** [comment]
Pulling the data from ALma the location external name is: Scribner Library: Common Works Collection
