### ISSUE TITLE
Status label is nil in certain situations

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1649]
https://github.com/pulibrary/bibdata/blob/a08c81169e3a2c31e36ed5ecaaef9be64a5140a6/app/adapters/alma_adapter/alma_item.rb#L231

This line produces a nil label for the item in https://github.com/pulibrary/requests/issues/1083.

We can look at the process type if the label is nil, but I wanted to be certain this would not cause issues in other places before I applied a patch just in requests.  It may be better to understand this at the bibdata level.  Maybe there is another field that should be returned from the api instead of always the label.

**Comment by christinach** [comment]
The response I get from https://bibdata.princeton.edu/bibliographic/99125378834306421/holdings/22897184810006421/availability.json? is:
[
{
"barcode": "",
"id": "23897184800006421",
"holding_id": "22897184810006421",
"copy_number": "1",
"status": "Not Available",
"status_label": "Acquisition",
"status_source": "process_type",
"process_type": "ACQ",
"on_reserve": "N",
"item_type": "Gen",
"pickup_location_id": "recap",
"pickup_location_code": "recap",
"location": "recap$pa",
"label": "ReCAP - Remote Storage",
"description": "",
"enum_display": "",
"chron_display": "",
"in_temp_library": false
}
]

@carolyncole where did you get the nil status response from?

**Comment by christinach** [comment]
The item must have been updated in Alma since the status is not nil anymore.

**Comment by hectorcorrea** [comment]
I would suggest that we update bib data to log the `mms_id` if we get nil from Alma on that specific field. That way we will have more information if/when the issue happens again. Perhaps log it as a WARN.

**Comment by christinach** [comment]
@carolyncole checked through the response again and it was not a bibdata issue it is a requests issue. I don't think also there is a possibility in alma to have an item in a process type and missing information on the label that we get from there.

**Comment by christinach** [comment]
> I would suggest that we update bib data to log the `mms_id` if we get nil from Alma on that specific field. That way we will have more information if/when the issue happens again. Perhaps log it as a WARN.

@hectorcorrea if you would like open a new issue for your suggestion?
