### ISSUE TITLE
Stokes location 'spia' and 'spr' have the same external name

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1650]
Linda Ch. reported in the catalog channel: `Stokes Library houses two collections.  SPIA and SPR.  The catalog no longer shows which collection a book is located in.  Can this please be addressed so we know which section to go to when getting a book`
The external name in Alma for these 2 locations (stokes$spia and stokes$spr) is configured to be the same: 'Wallace Hall'. Can this be updated so that the label indicates which section to go when getting a book? 
@mzelesky @regineheberlein 

When/If the external name in Alma is updated, please open a follow up issue in bibdata to update the locations.

Follow up with Linda Chamberlin.

**Comment by regineheberlein** [comment]
I've reached out to Linda on Slack

**Comment by mzelesky** [comment]
A corresponding ticket has been created in alma-config to track the change. https://github.com/PrincetonUniversityLibrary/alma-config/issues/61

**Comment by christinach** [comment]
Thank you @regineheberlein! Thank you @mzelesky !

**Comment by christinach** [comment]
Follow up with @mzelesky and Lynda about https://github.com/PrincetonUniversityLibrary/alma-config/issues/61.

**Comment by mzelesky** [comment]
The names have been updated in Alma.

**Comment by christinach** [comment]
Thank you @mzelesky
