### ISSUE TITLE
Figgy ARKs are not converting to manifest URLs during indexing.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/bibdata#1659]
This causes the viewer to not work for items which have the 856 but are not the BibID associated with the item in Figgy. This is usually the case with related items. Reported by Tom Ventimiglia.

https://catalog.princeton.edu/catalog/9956597633506421 should display a viewer.

**Comment by hectorcorrea** [comment]
Notice that the value in the `856` (http://arks.princeton.edu/ark:/88435/zk51vm39g) resolves to https://catalog.princeton.edu/catalog/9956630863506421#view and link does display the viewer.
