### ISSUE TITLE
Electronic Collection Level Deactivation Does not remove deactivated portfolios

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1662]
The top level electronic collection (China Online Journals Wanfang Data) containing the second link on this record: https://catalog.princeton.edu/catalog/99125340401906421 was completely deactivated in Alma last Friday. The links to all 6,000 individual portfolios that were deactivated by that action still appear to remain in the blacklight indexed data. In theory all those should have shown up as changed records in the incremental publishing process that happened after the deactivation.

**Comment by kevinreiss** [comment]
It also appears individual portfolio deactivations are not coming through. This record https://catalog.princeton.edu/catalog/99125289341106421 contains portfolios that were deactivated before noon on 9/23 as of the afternoon of 9/24.

**Comment by kevinreiss** [comment]
I would have expected that records who had portfolios deactivated would appear in the next scheduled incremental publishing job reflected that change. Probably to first step is to see if this is actually making it into publishing and take investigation from there.

**Comment by christinach** [comment]
The index has not been updated yet see https://github.com/pulibrary/bibdata/issues/1669#issuecomment-928204492

**Comment by christinach** [comment]
> https://catalog.princeton.edu/catalog/99125289341106421

The record has been updated but I'm not sure which are the deactivated portfolios and if they still appear in the indexed record. I will check Alma.

**Comment by christinach** [comment]
> The top level electronic collection (China Online Journals Wanfang Data) containing the second link on this record: https://catalog.princeton.edu/catalog/99125340401906421 was completely deactivated in Alma last Friday. The links to all 6,000 individual portfolios that were deactivated by that action still appear to remain in the blacklight indexed data. In theory all those should have shown up as changed records in the incremental publishing process that happened after the deactivation.

I will also look for this one in Alma when it was modified. I don't see the record to have been reindexed since 08/24.

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/bibdata/issues/1689
