### ISSUE TITLE
EAL's "Wilhelm Collection" can no longer be retrieved by a search

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#1663]
Reported by Martin: EAL has a collection with a donor agreement specifying the items are kept together, which at some point was sent to ReCAP and we decided to satisfy the spirit of the agreement by making it easy to retrieve the set of items in Orangelight by searching for "Wilhelm Collection". This no longer works.

Here is an example of one of the items: https://catalog.princeton.edu/catalog/9912680083506421:
> 0| 9912680083506421 8| 22646026850006421 a| 01PRI_INST b| eastasian c| Remote Storage (ReCAP): East Asian Library Use Only d| 60282.681 e| available f| 1 g| 0 j| pl k| 8 p| 3 q| East Asian Library 

I believe the migration to Alma probably removed the "wc" code and/or the "Wilhelm Collection" name from these items.

**Comment by hectorcorrea** [comment]
See this thread on Slack for possible indexing options https://pulibrary.slack.com/archives/CA891BNR0/p1632486513267600 suggested by Lia C.

**Comment by christinach** [comment]
Per Lia C. this falls into a cataloging discussion that requires @jbaxmeyer's approval to update or not a marc record in Alma.

**Comment by escowles** [comment]
I've emailed Jennifer and will checkin with her on this tomorrow.

**Comment by christinach** [comment]
Closing as this [collection](https://catalog.princeton.edu/?f%5Blocation%5D%5B%5D=East+Asian+Library&q=Wilhelm%20Collection&search_field=all_fields) is discoverable
