### ISSUE TITLE
Display the public notes for collection and item level records that have electronic portfolios

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1680]
Reported in the catalog feedback queue:
```
public notes entered in Alma for e-resources are not showing up in Blacklight. They did migrate correctly from SFX, to the expected fields in Alma. These can contain essential information for users, so we hope they can be restored soon.

Examples:
(1) passworded ejournal
The Book collector (ISSN 0006-7237) - MMS ID 99125185161706421
https://catalog.princeton.edu/catalog/99125185161706421
The public note includes a link to the restricted access page --https://library.princeton.edu/resource/restricted/33162 -- which provides the password information. We have approximately 50 passworded ejournals, all set up this way. Prior to Alma, the note would appear on a line above or below the holdings information. The note is entered on the portfolio record, on the Notes tab, under Public Note.
We have already begun receiving problem reports (in e-support) about passworded journals because the link to password information is no longer visible.

(2) collection-level note
PressReader - Collection ID 61753493390006421
sample title from this collection: African business (ISSN 2059-3848)
https://catalog.princeton.edu/catalog/99125225386706421
The note that should be appearing on all titles from this collection is simply "recent issues only" -- CZ coverage dates for these titles are unreliable; actual coverage varies from latest issue to latest several months' worth and changes frequently.
e.g. In this case, since not specific to a single title, the note is entered at the electronic service level for the collection, on the Notes tab, under Public note.

In addition to the portfolio and the collection service levels, there is also a field for Public Note at the collection level. I couldn't immediately find an example where we've used this, but we would expect Blacklight to display any note information from that field also.
```

**Update**:
I looked into the first mms_id 99125185161706421 and my understanding is that we need to index the electronic portfolio -> public note (951$i). Currently we don't index the public note and this is why it does not display in Blacklight. 

Regarding the second example I can see in Alma the Public note for this collection name but it's not included in the publishing job. 
@mzelesky would know better how to proceed with this enrichment. I will follow up with Nancy as soon as @mzelesky has time to review this issue and provide a response.

**Update 10/04/21**:
@mzelesky, Nancy B., Joe M. and @kconnellmail  will discuss this issue to see if there is some way to accomplish moving collection-level notes to the portfolio level via some job.

**Comment by christinach** [comment]
https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/electronic_portfolio_builder.rb

**Comment by kevinreiss** [comment]
@christinach, @mzelesky, will we find these notes in the current published data we receive from Alma? I think yes, but wanted to confirm.

**Comment by kevinreiss** [comment]
The tasks for this ticket are:

1. Add two fixtures to bibdata. A collection level record and individual portfolio record.
2. Add processing for the notes to the class @christinach references. 
3. We'll need to do a reindex to include this data in staging/prod. 
4. Update OL code to display new notes fields on the show page.

**Comment by christinach** [comment]
> @christinach, @mzelesky, will we find these notes in the current published data we receive from Alma? I think yes, but wanted to confirm.

yes the publishing job includes 951$i

**Comment by kevinreiss** [comment]
@mzelesky has prepared a test export from Alma production that includes all e-records with portfolios. It should be here later today. We can use this for examples of both "item" level and "collection" level e-records. For the purposes of the catalog the end result will look the same in the records "Show Page"

**Comment by kevinreiss** [comment]
generated on 2/22.

**Comment by kevinreiss** [comment]
The two example IDs in the thread will be in this data set.
