### ISSUE TITLE
Reindex Scribner locations

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/bibdata#1681]
@christinach the following changes have been made to the external names of these two locations:
`Firestone Library - Scribner Room` > `Firestone Library - Scribner Library`
`Firestone Library - Scribner Room: Reference` > `Firestone Library - Scribner Library: Reference`

**Comment by pmgreen** [comment]
Thanks @christinach Do you have an estimate of when this update will be done, so I can convey it?

**Comment by christinach** [comment]
@pmgreen Monday morning will update them. I will follow up with you.

**Comment by pmgreen** [comment]
Thanks @christinach
