### ISSUE TITLE
Reindex production so that Change the Subject and indigenous studies terms are applied

### ISSUE THREAD

**Issue by bess** [pulibrary/bibdata#1686]
Related to #595 

- [x] Coordinate a reindex in staging
- [x] Rebuild the staging browse lists
- [x] Coordinate a reindex in production
- [x] Rebuild the production browse lists

**Comment by christinach** [comment]
This is done. See discussion in https://pulibrary.slack.com/archives/CA891BNR0/p1634582061499700
