### ISSUE TITLE
Add additional subject headings to Change the Subject

### ISSUE THREAD

**Issue by bess** [pulibrary/bibdata#1691]
Add the 20 approved (as of Oct 8) additional subject headings to Change the Subject. See this spreadsheet for details: https://docs.google.com/spreadsheets/d/191sqH8tqpc0EFv2l1U9mh1-S1K4YFrtUQAaUlWhb4eg/edit#gid=0

**ACCEPTANCE CRITERIA**
- [ ] Subject terms like "Indians of Central America" are changed AFTER the addition of Indigenous Studies, so that the record will get both its augmented subject and its changed subject
- [ ] Reindex a subset of staging so we can demo this at the end of the workcycle

**Comment by kevinreiss** [comment]
Discussed with @escowles on 12/7. Agreed we can close.
