### ISSUE TITLE
Override an existing xml file in /data/marc_liberation_files/scsb_update_files while processing Full scsb files

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1704]
This error 'Zip::DestinationFileExistsError: Destination' happens when SCSB files are processed and extracted in `/data/marc_liberation_files/scsb_update_files`. This causes the process to stop and writes an error in the events page. We should override the xml file when it exists in `/data/marc_liberation_files/scsb_update_files` and let the process to continue.

### Honeybadger error: 
ActiveRecord::StatementInvalid in ScsbImportFullJob
https://app.honeybadger.io/projects/54497/faults/80414654

ACCEPTANCE CRITERIA
- [ ] override the xml file when it exists in /data/marc_liberation_files/scsb_update_files

**Comment by hectorcorrea** [comment]
I cannot reproduce this in my local environment. 

Even if I force the `.xml` or the `.gz` file to exist before the Zip code is executed in the [zip()](https://github.com/pulibrary/bibdata/blob/main/app/models/dump_file.rb#L40-L57) or [unzip()](https://github.com/pulibrary/bibdata/blob/main/app/models/dump_file.rb#L59-L78) methods the file is overwritten as expected and no exception is thrown.

I cannot find the exception [DestinationFileExistsError](https://app.datadoghq.com/logs?query=DestinationFileExistsError&cols=service%2Csource&index=&from_ts=1633383562899&to_ts=1635975562899&live=true) in our Datadog logs either  ¯\_(ツ)_/¯

**Comment by christinach** [comment]
We can try to replicate this on staging.

**Comment by christinach** [comment]
@kevinreiss @carolyncole @sandbergja @regineheberlein this is the error we see in the events page when the scsb job to import the full dump got re-triggered when sidekiq restarted.

<img width="1299" alt="Screen Shot 2022-03-01 at 7 32 30 AM" src="https://user-images.githubusercontent.com/9905193/156169689-014272b7-89ae-45f2-a4e7-7b8aaa8bcf62.png">

**Comment by christinach** [comment]
last time this was triggered from the job we have running once a month was

![Screenshot 2023-05-05 at 11 20 16 AM](https://user-images.githubusercontent.com/9905193/236499690-c5bf39a5-d550-409d-a98a-12f195a6ff36.png)
I've deleted the event and cleared the directory so that we ran the scsb import job if we want to before the next reindex (week of 5/8/2023)

**Comment by christinach** [comment]
This seems to have been fixed after we upgraded our boxes to jammy.
