### ISSUE TITLE
Expand Change the Subject to include all approved terms

### ISSUE THREAD

**Issue by bess** [pulibrary/bibdata#1719]
**ACCEPTANCE CRITERIA**
- [ ] All of the terms highlighted on [this spreadsheet](https://docs.google.com/spreadsheets/d/191sqH8tqpc0EFv2l1U9mh1-S1K4YFrtUQAaUlWhb4eg/edit#gid=0) have been configured in Change the Subject

**Comment by christinach** [comment]
See update on this: https://pulibrary.slack.com/archives/CA891BNR0/p1639669859211100 The Reparative Metadata Group is planning to evaluate those terms. 
Blocking this issues until further updates on the terms. 
@escowles @kevinreiss when you have an update from the working group please update this issue.

**Comment by carolyncole** [comment]
Will update to include lines 2 - 11 in here: https://docs.google.com/spreadsheets/d/1teQMEn_F_KlYZcOrtZ498SluSoUDb6rDHB3KQBYlZlw/edit#gid=1865606421
