### ISSUE TITLE
130 field is not indexed

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1721]
https://catalog.princeton.edu/catalog/9946018083506421/

There should be a 'uniform title' with value from 130.
```
<datafield tag=“130” ind1=“0" ind2=” “>
     <subfield code=“a”>Bible.</subfield>
     <subfield code=“l”>Latin.</subfield>
     <subfield code=“s”>Vulgate.</subfield>
     <subfield code=“f”>1461.</subfield>
</datafield>
```
https://www.loc.gov/marc/bibliographic/bd130.html
@mzelesky thank you.

**Comment by christinach** [comment]
In order to implement this request approval from @kevinreiss and @escowles . It will be a new field display in the catalog.

**Comment by kevinreiss** [comment]
Check in on this issue at the next OL weekly check-in.

**Comment by maxkadel** [comment]
Do we need an Orangelight ticket to ensure this field is displayed?

**Comment by maxkadel** [comment]
Hrm, it looks like it is indexed, see https://catalog.princeton.edu/catalog/9946018083506421/raw

```json
"uniform_title_s":["Bible. Latin. Vulgate. 1461"]
```
