### ISSUE TITLE
Indexing 856 Content on Records without any Holdings or Portfolios

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1724]
Example MMS ID: 99125403776206421

https://catalog.princeton.edu/catalog/99125403776206421

This is a record created recently that points to electronic content in our dataspace instance. Under voyager the workflow was to create an elf holding and add an 856 link with the pointer to dataspace. This record has the 856 but these holdings don't exist in Alma so there are none. The workflow for creating these records ultimately should be updated to create an electronic portfolio rather than just add an 856 link but that is going to take some coordination and conversation with the folks who create these records. As a fallback that would ensure user access to links in the 856 it is also probably a good thing to have our indexer handle 856 content on records that might show up without any holdings or portfolios.

**Comment by mzelesky** [comment]
I think this is deprecated in favor of digital inventory.

**Comment by kevinreiss** [comment]
Discussed at DACS-ATT meeting, we are going to close this in favor of the planned work around digital inventory.
