### ISSUE TITLE
Why do we need extra code for these locations?  What is not default?

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1743]
https://github.com/pulibrary/bibdata/pull/1742#pullrequestreview-824153780

**Comment by christinach** [comment]
The default (which was set long in the past and can probably change)is coming as 
open:true, 
requestable: true, 
always_requestable: false. 

The code can be updated and set only 'requestable' to be false.

**Comment by christinach** [comment]
It would be better though to update the location code and remove some parts that are not needed anymore for example: the generation of the json files based on the previous voyager -> alma mapping file.
