### ISSUE TITLE
The barcode/[barcode]/scsb route should return a record even if it is suppressed

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1745]
https://github.com/pulibrary/bibdata/blob/27ce102fa72468467732dfe5d236d3d76b7b0d06/app/controllers/barcode_controller.rb#L22

Many records in ReCAP are suppressed. This route should not be checking to see if the bib is suppressed.

**Comment by mzelesky** [comment]
Sample barcode: 32101092605078

**Comment by carolyncole** [comment]
https://bibdata.princeton.edu/barcode/32101104202237/scsb
