### ISSUE TITLE
DeleteDumpJob is failing regularly

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1749]
https://app.datadoghq.com/apm/error-tracking?issueId=34b4f4c2-3ac8-11ec-a09e-da7ad0900002&start=1639594937571&end=1639598537571&paused=false

```
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "dumps" violates foreign key constraint "fk_rails_4ce65c3a4c" on table "index_managers"
DETAIL:  Key (id)=(88) is still referenced from table "index_managers".
: DELETE FROM "dumps" WHERE "dumps"."id" = $1
```

**Comment by christinach** [comment]
Temporarily I manually ignored the error and stopped recording data.

**Comment by regineheberlein** [comment]
This is happening again, see https://app.honeybadger.io/projects/54497/faults/87574003/01GB4H4ZJKWHHXCDYS6V5RGS89?q=occurred.after%3A%227+days+ago%22

**Comment by maxkadel** [comment]
This is making it difficult for me to see actually relevant errors in the sidekiq logs.
