### ISSUE TITLE
2 updated records not updated in Blacklight

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1756]
Recently I have needed to relink Lapidus books from a wrong BIB record to a new, correct one.
 
Here’s an example
 
Lapidus Deposit 1682
Wrong BIB = 9932144563506421
New, correct BIB = 99125437328906421
 
I made this change yesterday.  As of today, Lapidus Deposit 1682 is showing as holding in BOTH records
https://catalog.princeton.edu/catalog/9932144563506421
and
https://catalog.princeton.edu/catalog/99125437328906421
 
Alma holdings show the correct holding info for these MMS IDs –
 
When will the public catalog update the wrong record so that it does not show the Lapidus holding?
 
----

History of 99125437328906421:
It was included in incremental_16185650540006421_20220113_210155[054]_new.tar.gz
At this time, it had no holdings attached.

It was then included in incremental_16197013530006421_20220114_150146[052]_new.tar.gz
At this time, it still had no holdings attached.

It was then included in incremental_16200861960006421_20220114_210127[051]_new.tar.gz
At this time, it had one holding attached (the Lapidus Deposit 1682 holding).

---

History of 9932144563506421:
It was included in incremental_16185650540006421_20220113_210155[054]_new.tar.gz
At this time, it had 2 holdings attached (including the Lapidus Deposit 1682 holding)

It has not appeared in any files since then.

---

To me, this says that when a holding is removed from a bib in Alma, it does not become included in the next incremental dump. I am going to create a SalesForce ticket about this, but I think this will require workflows being adjusted for relinking holdings. When a holding is moved from a bib, the attached bib must be saved as well.

For the immediate fix, I am going to save 9932144563506421, which should put it into the next incremental dump.

**Comment by christinach** [comment]
There is an open issue in Salesforce. It is an Alma issue.
