### ISSUE TITLE
Troubleshooting - Indexmanager will get stuck if previous_to_full_incremental dump causes errors

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1760]

**Comment by christinach** [comment]
The specific case in bibdata_staging was that the specific incremental dump has attached dumpfiles but the files do not exist in the vm. In this case it would be better to remove the specific record from the database so that it doesn't blow up the process and trigger a 'General Publishing job' in alma so that you will run a full reindex in the next days.
Second option would be if you have the exact file you can always move it on the server. In the next retry it will see it and index it.

**Comment by christinach** [comment]
Add this in the docs.

**Comment by kevinreiss** [comment]
I'm not 100% but is this documentation this issue was suggesting we add? https://github.com/pulibrary/bibdata/blob/main/docs/add-missing-dump-to-next-event.md

If it is we can close this issue.
