### ISSUE TITLE
liberate:full rake task doesn't issue a commit when it is done

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/bibdata#1783]
We ran `rake liberate:full` on staging yesterday according to the [instructions here](https://github.com/pulibrary/bibdata/blob/main/docs/indexing.md#creating-a-full-index), but had to manually commit at the end in order to see any documents in the solr index.

**Comment by christinach** [comment]
based on this https://github.com/pulibrary/bibdata/blob/63de58d1ece27d11f49dc8c0f30e280dd53690e7/app/services/index_functions.rb#L28 scsb should have issues a commit.
