### ISSUE TITLE
We need to ignore records with bad UTF8 characters

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1796]
When alma gives us a record with bad UTF8 we need to ignore that record in traject and go on to the next record.

We should log the error so that either record can be corrected at some future point.

 Unexpected error on record id `99125119454006421/99125119454006421` at file position 2874
 while executing (to_field publication_place_facet at marc_to_solr/lib/traject_config.rb:712)
 Exception: ArgumentError: invalid byte sequence in UTF-8

 marc_to_solr/lib/traject_config.rb:713:in `strip'

**Comment by carolyncole** [comment]
Here is an example to test against
[DRDS_test_records_16849857680006421_new.txt](https://github.com/pulibrary/bibdata/files/8134966/DRDS_test_records_16849857680006421_new.txt)

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/bibdata/pull/1797
