### ISSUE TITLE
Please index changes to firestone$pres and lewis$serial

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/bibdata#1803]
We have made changes to the external names of these two locations per MWC:
`firestone$pres`
`lewis$serial`

**Comment by christinach** [comment]
Thank you @pmgreen

**Comment by christinach** [comment]
@pmgreen what are the new external names? Locally when I pull the locations from Alma I dont see changes

**Comment by pmgreen** [comment]
`firestone$pres`: `Preservation Office: Contact preservation@princeton.edu`
`lewis$serial`: `Lewis Library - Serials (Off-Site)`
