### ISSUE TITLE
Ignore Resource Sharing Library Temp Location

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1821]
When indexing records in temporary locations we need to ignore the resource sharing location. Any items in this location are charged out to other libraries and the items themselves are routed to our resource sharing request options by the request form. 

This issue has more background. https://github.com/PrincetonUniversityLibrary/alma-config/issues/127

**Comment by christinach** [comment]
@kevinreiss are we talking about the https://bibdata.princeton.edu/locations/holding_locations/RES_SHARE$IN_RS_REQ or https://bibdata.princeton.edu/locations/holding_locations/RES_SHARE$OUT_RS_REQ ?

**Comment by christinach** [comment]
Based on https://github.com/PrincetonUniversityLibrary/alma-config/issues/127#issuecomment-1032793425 we are talking for https://bibdata.princeton.edu/locations/holding_locations/RES_SHARE$IN_RS_REQ .

@mzelesky @kevinreiss is this correct?

**Comment by mzelesky** [comment]
Yes that is correct. That location is for items that are out to other libraries.

**Comment by christinach** [comment]
Thank you @mzelesky

**Comment by christinach** [comment]
There shouldn't be 852s with RES_SHARE$IN_RS_REQ. I confirmed with @mzelesky . 
We need only to check if this location is in 876 and if it is then index the items as a permanent holding.
