### ISSUE TITLE
The build_items method needs to reference description instead of enumeration

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1827]
https://github.com/pulibrary/bibdata/blob/99f589ae48a2f71ddaf83afa264ed87a05e495ac/marc_to_solr/lib/process_holdings_helpers.rb#L144

In this line, it should say item[:description] instead of item[:enumeration].

**Comment by sandbergja** [comment]
In Alma publishing profile, there's a field called "description" that we bring in on the Enrichment tab.  It includes both chronology and enumeration.

**Comment by christinach** [comment]
Update it as enum_chron in bibdata and Enumeration/Chronology in the requests form

**Comment by kevinreiss** [comment]
Update the label on the request form table to say "Enumeration and Chronology" and update the code's hash key to be [:enum_chron].

**Comment by christinach** [comment]
Confirm with @mzelesky if the hash key will be `:description` or `:enum_chron`. Also look in the Orangelight agenda for related notes.

**Comment by mzelesky** [comment]
enum_chron or description both work; what really matters is what displays.

**Comment by sandbergja** [comment]
I'm going with `description`, since it's consistent with the availability JSON and the Alma UI.
