### ISSUE TITLE
Allow the Change the subject to also allow just masking

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1829]
Instead of substituting the value we would like to also just hide certain values.

**Comment by christinach** [comment]
maybe add in the config an empty string and see the result if its hide the term.

**Comment by kevinreiss** [comment]
This adds a lot of new terms that need to be scanned for every record we index. Need to test the impact of these additions on the current indexing process.

**Comment by christinach** [comment]
https://docs.google.com/document/d/19juNkdtqbOUwaqO_qLcu6mUMwPr6DbTEVQTEfzmPMeQ/edit

**Comment by carolyncole** [comment]
related to https://github.com/pulibrary/bibdata/issues/1830

**Comment by maxkadel** [comment]
It sounds like the intention of this ticket is to 
a) ensure that the original unwanted subject headings don't get through to the production data and 
b) we don't end up with duplicate subject headings

An intermediate step, which would not require the subjects in the catalog to be up-to-date, would be to continue to map the terms, & programmatically ensure that there are no duplicate headings in the set. 

It's possible the code already works this way, and we just need a test to verify.

**Comment by carolyncole** [comment]
There are no existing examples for what we need to mask, but writing a test to see if the code blows up when you pass nothing for the replacement term would be a good check.
