### ISSUE TITLE
CJK equivalent characters in different scripts not returning same results on Browse Lists

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1841]
From the #catalog channel on 4/13/22:

After PUL's system migration to ALMA, the number of *indexed" CJK bib headings has been greatly reduced, which is alarming. Martin [@Martin H](https://pulibrary.slack.com/team/U8ET04Q93) and Joshua [@Joshua Seufert](https://pulibrary.slack.com/team/U9NLF73AB) may have already noticed. Using CJK characters to search or browse in Blacklight becomes far less useful. Here is an example: if one selects "Subject (browse)" and type in "沈从文," one gets very limited hits--12 to be exact! Type in (traditional characters) 沈從文，one gets extra 3 hits. Yes, one must search twice in order to get these 15. Now, if using pinyin "Shen, Congwen," the result is 263. What happens, if one uses  "Author (browse)"?  Here are the results:  沈从文 (63),  沈從文 (109, again from a separate search by changing the middle Chinese character), and Shen, Congwen (182). BTW, the AAP (authorized access point for the name is: Shen, Congwen, 1902-1988. Since Blacklight has not been able to "re-direct" to controlled terms, most users--especially students--don't even know that "browsing" in CJK is supposed to work like this:   type in 沈从文 in browse box[es], the system would redirect: "See: Shen, Congwen, 1902-1988." I just wanted to share this experience of mine with all those who work with CJK. It is also possible that this affects all other vernacular character displays.

---

I received clarification that this is actually 2 issues.
1. Different CJK scripts are no longer seen as equivalent in Blacklight searching, though they were at one time.
2. Variants for authorized access points are not redirected to the AAP.

This ticket is for issue 1. There were 2 examples given:
沈从文 is supposed to be equivalent to 沈從文 in searching
毛泽东 is supposed to be equivalent to 毛澤東 in searching

**Comment by mzelesky** [comment]
After further discussion, it was found that this is only an issue for browse lists. It sounds like they are ideally wanting the results from Subject Browse for 沈从文 to be the same as the results from 沈從文

**Comment by sandbergja** [comment]
Another topic mentioned on the thread:

In this record: https://catalog.princeton.edu/catalog/9942717413506421, the MARC contains an 880 field:  `600-08/$1 a| 沈从文, d| 1902- t| 边城. `

However, it does not display in the show page.

**Comment by mzelesky** [comment]
The corresponding 600 field has different indicators, I wonder if that's the problem

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/bibdata/1841?planning-poker) with Zenhub @regineheberlein @rladdusaw @sandbergja

**Comment by sandbergja** [comment]
> Another topic mentioned on the thread:
> 
> In this record: https://catalog.princeton.edu/catalog/9942717413506421, the MARC contains an 880 field: `600-08/$1 a| 沈从文, d| 1902- t| 边城. `
> 
> However, it does not display in the show page.

I broke this comment off into its own issue: https://github.com/pulibrary/bibdata/issues/1980

**Comment by sandbergja** [comment]
Closing, since the stakeholders decided it was no longer necessary (they prefer a cataloging solution).
