### ISSUE TITLE
Display for Firestone$pb has been updated

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/bibdata#1857]
The catalog display for Firestone$pb has been adjusted from `Firestone Library - Remote Storage (ReCAP): Supervised use in Firestone A-16-H-3` to `Firestone Library - Remote Storage (ReCAP): Supervised use in Firestone`. Please update Bibdata and OL display. @christinach

**Comment by christinach** [comment]
Thank you @pmgreen

**Comment by christinach** [comment]
@pmgreen the external name that I see is : `"external_name": "Remote Storage (ReCAP): Firestone Library Use Only"`

**Comment by christinach** [comment]
@pmgreen I was checking pf location. :)
