### ISSUE TITLE
Add synonym mappings for indigenous languages to "Indigenous Languages"

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#1858]
Creating issue here, though I suspect the implementation will be in `bibdata` or `pul_solr`.

Add a mapping for all of the indigenous languages (identified by CaMS) to the term "Indigenous Languages", so searches can limit to any indigenous language, in addition to limiting to a specific language. Terms: https://docs.google.com/spreadsheets/d/1EzE7g8Ui8NZhnhQ0q-sSQubrdHLYpam5_HXV7XRA9dM/edit#gid=528830807. 

### Success criteria

- [x] If 008/35-37 has a [language code from this tab](https://docs.google.com/spreadsheets/d/1EzE7g8Ui8NZhnhQ0q-sSQubrdHLYpam5_HXV7XRA9dM/edit#gid=528830807), the `language_facet` field will include a value "Indigenous Languages (Western Hemisphere)"
- [x] If 041$a has a [language code from this tab](https://docs.google.com/spreadsheets/d/1EzE7g8Ui8NZhnhQ0q-sSQubrdHLYpam5_HXV7XRA9dM/edit#gid=528830807), the `language_facet` field will include a value "Indigenous Languages (Western Hemisphere)"
- [x] If 041$d has a [language code from this tab](https://docs.google.com/spreadsheets/d/1EzE7g8Ui8NZhnhQ0q-sSQubrdHLYpam5_HXV7XRA9dM/edit#gid=528830807), the `language_facet` field will include a value "Indigenous Languages (Western Hemisphere)"
- [x] If 650$a has a [language subject heading from this tab](https://docs.google.com/spreadsheets/d/1EzE7g8Ui8NZhnhQ0q-sSQubrdHLYpam5_HXV7XRA9dM/edit#gid=1088917906) and 650$v has the subdivision "Texts", the `language_facet` field will include a value "Indigenous Languages (Western Hemisphere)"
- [x] If 650$a has a language subject heading from the tab, but no `650$vTexts` exists, the field does not include the "Indigenous Languages (Western Hemisphere)" (unless it meets one of the criteria above).

**Comment by kevinreiss** [comment]
Reach out to Minjie for details on this.

**Comment by kevinreiss** [comment]
Grouping languages into a facet (this is similar feature-wise to what change the subject does).

**Comment by kevinreiss** [comment]
Discuss with @mzelesky in the OL meeting.

**Comment by mzelesky** [comment]
@escowles will check with DSSG to confirm that we want the language facet updated for this, not an extra subject heading.

**Comment by escowles** [comment]
Yes, DSSG confirmed this should be in the language facet.
