### ISSUE TITLE
Update the server directories to no longer have marc_liberation

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#1874]
to merge @acozine  changes here: https://github.com/pulibrary/princeton_ansible/pull/2781/files. We need to update:

[config/deploy/staging.rb](https://github.com/pulibrary/bibdata/blob/efde884542e8673d38a2b1ce9f28191dfa2069f6/config/deploy/staging.rb)
[config/deploy/production.rb](https://github.com/pulibrary/bibdata/blob/efde884542e8673d38a2b1ce9f28191dfa2069f6/config/deploy/production.rb)
[[docs/test_indexing.md](https://github.com/pulibrary/bibdata/blob/af4338d91a72917ef0313a7cc8109824a5b6a1a3/docs/test_indexing.md)](https://github.com/pulibrary/bibdata/search?l=Markdown&q=marc_liberation)

**Comment by maxkadel** [comment]
Need to coordinate testing with @acozine

**Comment by sandbergja** [comment]
closed by https://github.com/pulibrary/bibdata/pull/1903
