### ISSUE TITLE
Indicators for the new 876 field should be spaces instead of zeroes

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1877]
https://github.com/pulibrary/bibdata/blob/4c2f7b2df482af4ce3e9508683c1e3454601a48c/app/adapters/alma_adapter/alma_item.rb#L72

**Comment by carolyncole** [comment]
@christinach is there some place this should be tested?  If not it looks ok to me...

**Comment by christinach** [comment]
@carolyncole This is a new field we add and it should have spaces ' '  in the indicators. @mzelesky says it is wrong the way it is added with '0' in the indicators. We don't need to test it somewhere.

**Comment by christinach** [comment]
Currently it's being used in the barcode controller when Recap accessions the items.
