### ISSUE TITLE
Seeding figgy cache in development seems to block indexing to Solr

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#1881]
Trying to add a couple fixture objects to Solr in development kicks off seeding the cache for figgy, which runs for a very long time, and seems to be getting the seed for all the production data, which is not needed in development. 

Reproduction:
* Bring up bibdata solr - `bundle exec rake servers:start` 
* Copy the url for lando's development solr
* Using a fixture xml with MARC data, run 
```bash
traject -c marc_to_solr/lib/traject_config.rb PATH/TO/FILE.xml -u LANDO_SOLR_URL/solr/marc-liberation-core-development -w Traject::JsonWriter
```

**Comment by christinach** [comment]
We should include the above in the documentation.

**Comment by christinach** [comment]
documentation was added
