### ISSUE TITLE
Log errors from traject in alma indexer

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#1885]
The command line to traject currently does not capture errors. We could use a utility like the Open3 gem to capture stdin, stdout, and stderr and log to the rails log or otherwise react to errors.

https://github.com/pulibrary/bibdata/blob/38405f611eccbdcc703b68ca91f4f0b79a7dd08e/app/services/alma/indexer.rb#L10

# Goal

To learn more from honeybadger errors like this one: https://app.honeybadger.io/projects/54497/faults/86965009

# Success criteria

- [x] If I try to index a file locally using [these instructions](https://github.com/pulibrary/bibdata/blob/main/docs/test_indexing.md#test-indexing-a-specific-xml-file), a local solr, and the wrong filename: a "No such file or directory @ rb_sysopen" error is added to log/development.log
- [x]  If I try to index a file locally using [these instructions](https://github.com/pulibrary/bibdata/blob/main/docs/test_indexing.md#test-indexing-a-specific-xml-file), a local solr, and an invalid traject configuration (for example, it attempts to write to a solr field that doesn't exist in schema.xml, or doesn't contain an id field): an error including the solr response is added to log/development.log.

**Comment by sandbergja** [comment]
Re-opening this one, since we aren't yet logging the error messages that traject throws.
