### ISSUE TITLE
Include additional heading for all works with given subheading, regardless of order

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#1889]
For https://github.com/pulibrary/bibdata/issues/1863 we created an implementation that simply left-matched the subject heading. This means that if subject headings fully follow the LoC rules for subject headings, they should be included.

This code also has the advantage of being significantly simpler and requires less human intervention in order to implement and update (previously there was a piece of code that required a developer to decide if a subject heading on its own was relevant)

With this code, however, if there is a subfield x that is on the "always include" list will not be included if it's not in the full explicit list (full list for now - https://docs.google.com/spreadsheets/d/1jFsLExGilXWmXEikliuYUtdipF5HnRbNMZn-rgJYflY/edit#gid=1600276075). (e.g., there are 28 instances of `ǂx Indian authors` in the full list, but if somehow there was a `ǂa Latvian literature ǂx Indian authors` added, it would not get the "Indigenous studies" subject heading.)

We could write code that adds the "Indigenous studies" subject heading for any subject heading with a given subfield x. We can look at the previous implementation for one way to implement this (see https://github.com/pulibrary/bibdata/commit/659427979f0fb4534d938cb13047643ff4a1fe0d); however, we would need to be sure not to over-match with similar code (e.g., don't match on all `ǂa Alaska` subject headings).

**Comment by christinach** [comment]
@maxkadel will review the ticket
