### ISSUE TITLE
ArgumentError: missing required parameter params[:queue_url]

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/bibdata#1910]
This is creating a huge volume of exceptions in Honeybadger.

## Backtrace

    line 18 of [PROJECT_ROOT]/app/services/aws_sqs_poller.rb: poll
    line 5 of [PROJECT_ROOT]/lib/tasks/indexing.rake: block (3 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/86325613)

**Comment by christinach** [comment]
see also https://github.com/pulibrary/princeton_ansible/issues/3038

**Comment by christinach** [comment]
related issue https://github.com/pulibrary/bibdata/issues/1867

**Comment by christinach** [comment]
We also thought that sqs-poller was not running by doing https://github.com/pulibrary/princeton_ansible/pull/3044.

**Comment by christinach** [comment]
Will review why this change that worked at some point doesn't work anymore https://github.com/pulibrary/princeton_ansible/issues/3041. https://github.com/pulibrary/princeton_ansible/pull/3044

**Comment by christinach** [comment]
I self assigned this issue because it is part of https://github.com/pulibrary/bibdata/issues/1867

**Comment by christinach** [comment]
Resolved by https://github.com/pulibrary/princeton_ansible/pull/3126/files
