### ISSUE TITLE
SignalException in at_exit

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/bibdata#1924]
Error on Bibdata staging https://app.honeybadger.io/projects/54497/faults/86704574

/usr/lib/ruby/2.7.0/open-uri.rb:21:in `initialize'
20 | else
21 | open_uri_original_open(name, *rest, **kw, &block)
22 | end
23 | end

**Comment by christinach** [comment]
This could be to a developer ctrl+c instead of typing exit to exit a vm.

**Comment by kevinreiss** [comment]
I see one active instance of this error in honeybadger from a different block of code https://app.honeybadger.io/projects/54497/faults/94190454 and agree that is likely a ctrl-c. Closing.
