### ISSUE TITLE
CDL Record Does Not Show "View Digital Content" Link

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1938]
CDL Display the following section when an item record attached to the physical item has been sequestered and scanned in the "Controlled Digital Lending" process type in Alma. 

<img width="1027" alt="Screen Shot 2022-08-02 at 3 36 47 PM" src="https://user-images.githubusercontent.com/278825/182478035-00ded14a-ea28-46e8-8ae1-c5f1b0f5ff9c.png">

**Actual behavior**
Visit record https://catalog.princeton.edu/catalog/99101599253506421 to see an example. Visit the MMS ID in Alma to see the state of the item records attached to this bib. A CDL Record with the correct behavior is: 

**Impact of this bug**
Users do not have any indicator a copy is available for digital lending unless they scroll to the bottom of the page.

**Comment by christinach** [comment]
check if the issue is related to the fact that the cdl item is in a temporary location.

**Comment by christinach** [comment]
another example https://catalog.princeton.edu/catalog/99125436335206421 with cdl false in the bibdata response
```
{"99125436335206421":
{"22911832010006421":{"on_reserve":"N","location":"engineer$stacks","label":"Engineering Library - Stacks","status_label":"Available","copy_number":null,"cdl":false,"temp_location":false,"id":"22911832010006421"},
"engineer$res":
{"on_reserve":"Y","location":"engineer$res","label":"Engineering Library - Reserve","status_label":"Unavailable","copy_number":null,"cdl":false,"temp_location":true,"id":"engineer$res"}}}
```

**Comment by christinach** [comment]
We asked Liza in Reserve & Resource Sharing if it's possible not to place CDL items in temporary locations.
Liza instructed staff in Reserves that CDL items that go on 'Reserve' not to be in a temporary location. 
We should keep this issue open until we make sure that CDL records are not placed in temporary locations and that the ones in temporary locations have been reassigned to a permanent location.

**Comment by kevinreiss** [comment]
Write Liza to confirm their current practices.

**Comment by kevinreiss** [comment]
@mzelesky pulled the latest alma info on these items and we still have about 200 items in CDL in temp locations. We are looking into just ending this cataloging practice.

**Comment by kevinreiss** [comment]
Confirmed with Mark that there a no more CDL items in temp locations.
