### ISSUE TITLE
Error Message: ActiveRecord::StatementInvalid in rake bibdata:indexing:poll_sqs

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/bibdata#1959]
Error Message: ActiveRecord::StatementInvalid in rake bibdata:indexing:poll_sqs

Honeybadger link: https://app.honeybadger.io/projects/54497/faults/87507590

Failing code block:
app/services/aws_sqs_poller.rb
[PROJECT_ROOT]/app/services/aws_sqs_poller.rb:44:in `bib_dump'

def bib_dump
--
44 | dump = Dump.create(dump_type: DumpType.find_by(constant: dump_type))
45 | dump.event = dump_event
46 | dump.generated_date = dump_event.start

The error appears to be occurring at fixed intervals, possibly related to a scheduled job.

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/bibdata/1959?planning-poker) with Zenhub @regineheberlein @rladdusaw @sandbergja

**Comment by christinach** [comment]
I don't see this error in honeybadger. I think we can close this ticket.

**Comment by kevinreiss** [comment]
Ok, thanks for reviewing @christinach
