### ISSUE TITLE
Review indexing of Committed and Uncommittable Collection Group Records from Recap Partners

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#1962]
When Harvard joined ReCAP last summer two new Collection Group identifiers were introduced, committed and uncommittable. Records in either group are loanable to partners. We should confirm these are being processed and displayed in the same fashion records from the shared and open groups are. At the present time only Harvard has records in either of the new collection groups. 

The SCSB api docs describe the parameters for Collection Group ID as follows

```Data can be requested by Collection Group ID, either Shared (use 1)/Open (use 2)/Private (use 3)/Committed (use 5)/Uncommittable (use 6). Default is Shared and Open, can use 1,2,3 as well.```

I believe this means we want to pass the ID combo of 1,2,5,6 to get all shareable records from each partners under this updated model. 

- [x] Are we requesting committed and uncommittable items in full partner dump requests
- [x] Are we requesting committed and uncommittable items in incremental partner dump requests
- [ ] Are these statuses properly represented in the solar index for SCSB item data?
- [ ] Are these statuses properly displayed in the OL show page section displaying ReCAP Partner Item status information.

**Comment by kevinreiss** [comment]
No, we are not receiving these statuses in either full or incremental updates. We need update our rake tasks for full dumps to request these statuses, and we need to talk to the vendor to have them add them to the incremental dumps that they generate for us. Rake task was added in this PR https://github.com/pulibrary/bibdata/pull/1953.

**Comment by kevinreiss** [comment]
Filed request to add statuses to incremental dumps: https://htcrecap.atlassian.net/jira/core/projects/MS/list?selectedIssue=MS-576

**Comment by kevinreiss** [comment]
The vendor is adding the statuses to the incremental feed the week of 9/19.

**Comment by christinach** [comment]
We include the extra statuses in the incremental dump. https://github.com/pulibrary/bibdata/pull/1987/files
