### ISSUE TITLE
update bibdata with new locations from Alma

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/bibdata#1963]
The following 9 locations were created; they are all Special Collections locations with reading room use only. 

NB these are also the locations for which we want to suppress the Reading Room Request button (https://github.com/pulibrary/orangelight/issues/2910).

rare$xmr
Fulfillment unit: Closed
Remote Storage: ReCAP remote storage

rare$scactsn
Fulfillment unit: Limited

rare$scagax
Fulfillment unit: Limited

rare$scamss
Fulfillment unit: Limited

rare$scawa
Fulfillment unit: Limited

rare$scaex
Fulfillment unit: Limited

rare$scahsvm
Fulfillment unit: Limited

mudd$scamudd
Fulfillment unit: Limited

rare$scathx
Fulfillment unit: Limited

Additional background can be found here:
[Project overview](https://docs.google.com/document/d/1FYpmZwRNuhnyoG2LfRGVm0nHyOhpgASYhFiV3lwOPXw/edit)
[Locations proposal](https://docs.google.com/document/d/1y__OO9UPU6tbUT42ijKxa_LlR5rRXg8-/edit)
[Locations checklist](https://docs.google.com/document/d/1E36NShlpqeq7zFXmMcP1Tu5ZD2NWgySgp20teTGiQWE/edit#)

**Comment by christinach** [comment]
@regineheberlein will update the ticket when the data work is done in Alma.

**Comment by christinach** [comment]
The locations need to be added in bibdata before we move items in these locations in ALMA.

**Comment by christinach** [comment]
@mzelesky @kevinreiss is this the only recap location 'rare$xmr' ? Does it need to be added in https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/translation_maps/holding_library.rb ?

**Comment by kevinreiss** [comment]
For now I'd just add it because it's the convention. We should talk if we want to ticket deprecating the holding library entirely. Is it used by anything for a practical purpose at this point?

**Comment by christinach** [comment]
It is used in the advanced search and in the requests. We could discuss to deprecate it in a separate ticket.
