### ISSUE TITLE
Add new ReCAP location xmr/PG to SubmitCollection

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/bibdata#1964]
The new location has been created, see https://github.com/pulibrary/bibdata/issues/1963

rare$xmr
internal name: scarcpxm
Customer code: PG
Fulfillment unit: Closed
Remote Storage: ReCAP remote storage

Additional background can be found here:
[Project overview](https://docs.google.com/document/d/1FYpmZwRNuhnyoG2LfRGVm0nHyOhpgASYhFiV3lwOPXw/edit)
[Locations proposal](https://docs.google.com/document/d/1y__OO9UPU6tbUT42ijKxa_LlR5rRXg8-/edit)
[Locations checklist](https://docs.google.com/document/d/1E36NShlpqeq7zFXmMcP1Tu5ZD2NWgySgp20teTGiQWE/edit#)

**Comment by mzelesky** [comment]
It also needs to be Supervised Use in the Use Restriction.

**Comment by christinach** [comment]
@regineheberlein will update the ticket when the data work is done in Alma.

**Comment by christinach** [comment]
needs more clarification regarding the location code

**Comment by christinach** [comment]
This location code is included in the previous issue so it will be added there. #1963

**Comment by christinach** [comment]
The location was added in bibdata in https://github.com/pulibrary/bibdata/issues/1963
