### ISSUE TITLE
046 is not displaying in catalog-staging

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/bibdata#1976]
It was expected to show up in a "Compiled/Created" field. Here is an example, the same record in Alma:

https://princeton-psb.alma.exlibrisgroup.com/ng/page;u=%2Frep%2Faction%2FpageAction.mms.marc_re[…]1&pageBean.securityHashToken%3D4083767865258545437

and in catalog-staging:
https://catalog-staging.princeton.edu/catalog/99125628841606421

For comparison, here the 046 does display. The MARC encoding looks the same, so perhaps there's some other condition intervening (for example, the one missing the 046 display has no items)? 
https://catalog-staging.princeton.edu/catalog/9978169043506421

**Comment by maxkadel** [comment]
It looks like for the example record, the compiled_created_display may be getting populated from 245, subfield f.

```ruby
# Compiled/Created:
#    245 XX fg
to_field 'compiled_created_display', extract_marc('245fg')
to_field 'compiled_created_t', extract_marc('245abchknps')
```

**Comment by regineheberlein** [comment]
Ah! Then I'll populate that field in my MARC output, thanks!
