### ISSUE TITLE
583 is not displaying in catalog-staging

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/bibdata#1977]
This is a field more often used in archives than outside it; perhaps we don't index it?

Example in Alma:
[https://princeton-psb.alma.exlibrisgroup.com/ng/page;u=%2Frep%2Faction%2FpageAction.mms.marc_re[…]1&pageBean.securityHashToken%3D4083767865258545437](https://princeton-psb.alma.exlibrisgroup.com/ng/page;u=%2Frep%2Faction%2FpageAction.mms.marc_re%5B%E2%80%A6%5D1&pageBean.securityHashToken%3D4083767865258545437)

and in catalog-staging:
https://catalog-staging.princeton.edu/catalog/99125628841606421

**Comment by regineheberlein** [comment]
This suggests they would be: https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb#L616
```
# Notes index field 5XX
to_field "notes_index", extract_all_marc_values(from: '500', to: '599')
```

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/bibdata/1977?planning-poker) with Zenhub @regineheberlein @rladdusaw @sandbergja

**Comment by regineheberlein** [comment]
@rladdusaw With respect to filtering which local ones to display (raised during checkin today)--all of them have the `(PULFA)` prefix in the 035 (and none of the ones we don't want to display have it)

**Comment by regineheberlein** [comment]
Sorry, even better--they all have a 003 with value "PULFA":

`<controlfield tag='003'>PULFA</controlfield>`

**Comment by mzelesky** [comment]
When records are imported, the 001 and 003 values get combined into an 035 field, putting parentheses around the value in the 003 field.
