### ISSUE TITLE
Alternate script 600 field is not being indexed for display in the lc_subject_display field

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/bibdata#1980]
### Expected behavior
[MMS ID 9942717413506421](https://catalog.princeton.edu/catalog/9942717413506421/staff_view) has a 600 field "Shen, Congwen, 1902- -- Bian cheng." and a matching 880 field with the CJK version: "沈从文, 1902- -- 边城."  I expected both to display in the [orangelight show page](https://catalog.princeton.edu/catalog/9942717413506421) and the `lc_subject_display` field in the [raw json](https://catalog.princeton.edu/catalog/9942717413506421/raw).

### Actual behavior
The CJK version does not appear in the orangelight display, or in the raw json.

### Previous discussions

In the catalog channel on slack: https://pulibrary.slack.com/archives/CA0UY0Q07/p1649860781667399

### Re-indexing needed

After this is fixed, we'll need a full re-index.

### Notes

There is a cjk_subject line here, which indexes the "alternate script" version: https://github.com/pulibrary/bibdata/blob/7c3e63c479ac2f9c8a59b53cfdbe878763ecf5bf/marc_to_solr/lib/traject_config.rb#L889

However, [it is not a stored field](https://github.com/pulibrary/pul_solr/blob/79feb74e0cbb83d3acca8489ed59034407858a9e/solr_configs/catalog-production-v2/conf/schema.xml#L675), it is only used for search.

**Comment by christinach** [comment]
https://pulibrary.slack.com/archives/CA0UY0Q07/p1649953748468119
