### ISSUE TITLE
Request to index non-LC names in records, i.e. those designated as "viaf" or "uncontrolled."

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/bibdata#1984]
Request to index non-LC names in records, i.e. those designated as "viaf" or "uncontrolled."

_Originally posted by @faithc in https://github.com/pulibrary/aspace_helpers/issues/181#issuecomment-1239608807_

**Comment by regineheberlein** [comment]
@faith can you provide a little more information about this please?

**Comment by faithc** [comment]
Closing this as request noted in https://github.com/pulibrary/aspace_helpers/issues/181 should resolve the issue.
