### ISSUE TITLE
Items in AEON with process_type: missing should have status label 'Unavailable'

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1989]
### Desired behavior
Items in AEON with`process_type: missing` should have status label: 'Unavailable' in the availability response. https://github.com/pulibrary/bibdata/blob/040d5ac3f6157416bd1ca2b7bc54190394d735be/app/adapters/alma_adapter/status.rb#L26

### Current behavior
Items in AEON have status_label: 'On-site Access'. https://github.com/pulibrary/bibdata/blob/040d5ac3f6157416bd1ca2b7bc54190394d735be/app/adapters/alma_adapter/status.rb#L17
example: https://bibdata.princeton.edu/bibliographic/availability.json?deep=true&bib_ids=9963575053506421
```

  "9963575053506421": {
    "22726823980006421": {
      "on_reserve": "N",
      "location": "rare$hsvm",
      "label": "Special Collections - Manuscripts",
      "status_label": "On-site Access",
      "copy_number": null,
      "cdl": false,
      "temp_location": false,
      "id": "22726823980006421"
    }
  }
}
```

Related issue https://github.com/pulibrary/orangelight/issues/3173

https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get%2Falmaws%2Fv1%2Fbibs%2F%7Bmms_id%7D%2Fholdings%2F%7Bholding_id%7D%2Fitems

**Comment by christinach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OrangelightBibdataRequests-571691cab409d8d821b873be/issues/pulibrary/bibdata/1989?planning-poker) with Zenhub @leefaisonr @maxkadel @sandbergja

**Comment by kevinreiss** [comment]
emailed stakeholders 1/9.

**Comment by kevinreiss** [comment]
Asked stakesholders 2/8 and 2/16 for a meeting to discuss the issue.

**Comment by kevinreiss** [comment]
Reached out to Sara L. about this 3/2.

**Comment by kevinreiss** [comment]
SC is going to suppress items in the statuses that are truly non-requestable rather than having us change the current codebase.
