### ISSUE TITLE
Extract change_the_subject configuration, support class to separate gem

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1994]
This will allow other applications to use the configuration and code, while we maintain a single configuration of record.

https://github.com/pulibrary/bibdata/blob/6630d8cadbfb8acd8a34aff7664e8821acb313d6/marc_to_solr/lib/change_the_subject/change_the_subject.yml

related to https://github.com/pulibrary/pulfalight/issues/1088

**Comment by eliotjordan** [comment]
An alternative is to extract the change_the_subject.yml file and support classes into a gem.

**Comment by hackartisan** [comment]
new gem in progress here https://github.com/pulibrary/change_the_subject

**Comment by maxkadel** [comment]
Successfully deployed to bibdata-staging
