### ISSUE TITLE
Implement Integration with Alma's Digital inventory Feature

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#1996]
Make 2 remote repositories in Alma: one for CDL and one for all other Figgy content.

Digital objects will be in the 896 fields in the publishing job. Repository name is in 896$x.

**Comment by kevinreiss** [comment]
@mzelesky I think we need to flesh this out some more.

**Comment by kelea99** [comment]
### Needs Documentation

- Manual workflow for cams for cataloging and adding digital inventory for internal objects needed.  ( @mzelesky , is there documentation for this?)

-Workflow(s) for automated processes for RDSS, Figgy, etc.  for internal and external digital content

### Types of digital content in alma

- External = portfolio (workflow already exists for this). already in process for cleanup

- Internal = digital inventory (new digital asset workflow needed).

**Comment by kevinreiss** [comment]
Per OL meeting on 10/26. Will schedule a meeting to review this with Mark to restart a project plan for implementation.

**Comment by kevinreiss** [comment]
Kevin will set a meeting this wek.
