### ISSUE TITLE
New location in Alma

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#2007]
### User story
A new location has been added to the Firestone library.

firestone$isc

No items have been added yet.

### Concrete example
We can provide one if necessary, but there are no items currently in the location.

### Re-index required?
Re-indexing is not required, since there are no items yet in the location.

### Implementation notes, if any
Ideally, this location would be in place by 10/21, so staff can place items in the location. Please let us know if more time is needed.

**Comment by christinach** [comment]
@mzelesky thank you! the location will be in place by 10/21. I will follow up.

**Comment by christinach** [comment]
@mzelesky regarding the new location what are the circ options? Is it similar or the same to another firestone location from https://bibdata.princeton.edu/locations/holding_locations ?

**Comment by mzelesky** [comment]
Please see https://github.com/PrincetonUniversityLibrary/alma-config/issues/301 for the details. Sorry about not including this when I opened the ticket.

**Comment by christinach** [comment]
Thank you @mzelesky . In the list we would like also to know the 'Fulfillment unit'.

**Comment by christinach** [comment]
@mzelesky when I read 'Where can items be picked up at [only owning library, all owning libraries]? Only owning library', my understanding is that delivery location is only Firestone https://bibdata.princeton.edu/locations/delivery_locations/15. Can you please confirm?
