### ISSUE TITLE
Test lib-sftp-staging

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2027]
Test bibdata connection to lib-sftp-staging1

related to https://github.com/pulibrary/ops-catchall/issues/4

**Comment by christinach** [comment]
@kayiwa @mzelesky and I have tested the alma and almasftp account connection to lib-sftp-staging1.We were able to send files from the Alma sandbox to lib-sftp-staging1. 
Events were created in bibdata-staging but no files were transferred. 
@christinach is looking into why files were not transferred from lib-sftp-staging1 to bibdata-staging

**Comment by christinach** [comment]
Will revisit this next week (12/19/22) and follow up with @kayiwa

**Comment by christinach** [comment]
@kevinreiss thank you. I postponed looking into this issue because of the long Orangelight sprint + Holidays time.

**Comment by kevinreiss** [comment]
Francis asked to work with folks on this the week of 4/3.

**Comment by christinach** [comment]
Updates from the meeting today in https://docs.google.com/document/d/1Tyaltv3JWkfcu-SiROfGAEEso7ynMpugUM_wzQjP3ng/edit

**Comment by christinach** [comment]
https://bibdata-staging.princeton.edu/dumps/1165.json the files were transferred successfully from lib-sftp-staging1 to bibdata-staging. Additionally to the previous updates in the playbook , restaring the workers and deploying the app to bibdata-staging helped to fix the last [honeybadger]( https://app.honeybadger.io/projects/54497/faults/95091816) issue and trasfer the files from lib-sftp-staging1 to bibdata-staging.
