### ISSUE TITLE
New facet: geographic subject

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#2034]
Feature request received by DSSG: Add a geographic facet, similar to Subject: Era, based on $z in 6xx fields. This would allow users to limit their results to items ABOUT a place, which is sometimes different than the Place of publication.

### Acceptance Criteria

- [x] Index from Alma Staging a set of records using 6xx $z (Bibdata)
- [x] Add Facet to Orangelight. 
- [ ] Preview results in catalog-staging for POs. 
- [ ] Decide if this shows up on the advanced search page or not. We do not have subject era on the adv. search now.

**Comment by escowles** [comment]
DSSG discussion today: some catalogs have geographic subject facets (Cornell, Stanford, and Yale all display a geographic facet), but we're not sure whether they are using 6xx $z or 043 for the data. More investigation is needed to determine what is the best source of data for this facet.

**Comment by kevinreiss** [comment]
DSSG will investigate and report back.

**Comment by escowles** [comment]
Different people do it different ways. We'd like to try 6xx $z. Can we index that into a geographic facet in staging to see what the data looks like?

**Comment by christinach** [comment]
Yes, we will index a data set in bibdata-staging or bibdata-qa.

**Comment by sandbergja** [comment]
This is done!  Yay!
