### ISSUE TITLE
Index FAST subject headings

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#2040]
Index [FAST](https://fast.oclc.org/searchfast/) headings (6XX second indicator 7 with $2 fast) for subject browsing/searching in Blacklight

### Acceptance Criteria

- [ ] We only index this data when there are no LCSH subjects assigned to the record
- [ ] Fast Headings are searchable by keyword
- [ ] Fast headings are available for display. 

### Re-index required?

- [x] Full re-index
- [ ] Partial re-index
- [ ] No re-indexing required

### Implementation notes, if any

- Do we want to only index headings added by Princeton? 
- When we do not index the FAST headings are we only not indexing when there are 65x subject headers or do we not index them if there any other 6xx subject headings at all?

Approved by DSSG in January 2021

**Comment by escowles** [comment]
Question: since the FAST headings might duplicate LCSH, do we want to display these? Do we break them out by type? What if there are a bunch of them?

**Comment by mzelesky** [comment]
Initial analysis:
https://www.oclc.org/content/dam/oclc/fast/FAST-quick-start-guide-2022.pdf is a guide to FaST.

It lists 9 sections of FAST:
Topical
Personal Names
Corporate Names
Meetings
Named Events
Uniform Titles
Chronological
Geographic
Form/Genre

Of those, Named Events is the only area without a direct equivalent in LCSH.

The rest are simply derived from the LCSH equivalents, with some key differences.
1. Place names are always hierarchical and always in their 'natural order'.
  a. LCSH: Fuji, Mount (Japan)
  b. FaST: Japan -- Mount Fuji
2. Name-title headings are formed in FaST by starting with the title, then placing the name after.
  a. LCSH: Vonnegut, Kurt. Slaughterhouse-five
  b. FaST: Slaughterhouse-five (Vonnegut, Kurt)
3. In general, FaST consists of the individual facets of assigned LCSH split into the 9 segments listed above.
  a. LCSH: 650  _0 $a Internal migrants $z China $z Beijing $v Fiction.
  b. FaST:
    1. 650  _7 $a Internal migrants.
    2. 651  _7 $a China $z Beijing.
    3. 655  _7 $a Fiction.

There are other differences, but those are the most significant.

I am running some scripts to gather data on how FaST is currently used at PUL.
1. Find records that do not have LCSH/LCGFT but have FaST headings.
2. Of records that have LCSH/LCGFT and FaST, which records have headings unique to the FaST vocabulary that aren't directly represented by LCSH/LCGFT? This will also show all FaST headings on records with both vocabularies.

My hope is that these analyses will be used to inform us how to implement this request and its priority.

**Comment by mzelesky** [comment]
See this report for records with FaST headings but no LC headings: https://docs.google.com/spreadsheets/d/1N_Orxap8UTb4eJt8NDZKhnQA4wQp95ShI4fphkOf8ao/edit?usp=sharing

There are 2,635 such records out of 11,802,517 unsuppressed records in Alma. Records have not been further assessed (belonging to the Community Zone, records that are not yet fully cataloged, etc.).

**Comment by mzelesky** [comment]
See this report for records with LC headings that also have unique FaST headings: https://docs.google.com/spreadsheets/d/1Yt-fARTeLg_V2ok-kVhUAWUijAbnLuHEuvPQgjGhhT4/edit?usp=sharing

There are 353,931 such records out of 11,802,517 records in Alma.

Many of them have near-equivalent matches in LC, e.g., `World War, 1939-1945` vs. `World War (1939-1945)`.
Many others only have chronological headings, e.g., `1900 - 1999`, which were derived from other areas of the record.

**Comment by mzelesky** [comment]
See this report for records with LC headings that have FaST headings completely duplicated by LC portions:
https://docs.google.com/spreadsheets/d/1o4wkiChs1mFGI7E_yE80sMchxGiQirYLBdONCyEsNmU/edit?usp=sharing

There are 422,874 such records out of 11,802,517 records in Alma.

**Comment by mzelesky** [comment]
Overall summary:
1. Roughly 7% of our records have FaST headings.
2. Roughly 54% of those records have FaST headings with information that is entirely duplicated by LC headings.
3. Roughly 0.02% of our records only have FaST headings.

**Comment by kevinreiss** [comment]
Looking for clarity on when we should show these headings from DSSG, should it be only when there is only there unique data in FAST.

**Comment by escowles** [comment]
Should index and display the FAST headings only when there are no LCSH subjects.

**Comment by escowles** [comment]
Jennifer says it's fine to put them all in one section called "FAST Subjects"
