### ISSUE TITLE
Index 653 contents as keywords

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#2041]
Index MARC field 653 (uncontrolled index terms) contents as keywords

### Re-index required?

- [x] Full re-index
- [ ] Partial re-index
- [ ] No re-indexing required

### Implementation notes, if any

Approved by DSSG in April 2021

**Comment by sandbergja** [comment]
@escowles a few questions about this one:

- Do we want these indexed for display, search, or both?
- If for display, what is the desired display?  Underneath the subject headings?  Should they be links or not? If a 653 term is the same as a subject heading in the record, do we still want to display the 653 separately?
- Are there any specific example records that DSSG had in mind?

**Comment by escowles** [comment]
Apparently we have been stripping this field because it isn't being indexed, so we don't have sample records. So we can probably use the example values from the [MARC docs](https://www.loc.gov/marc/bibliographic/bd653.html).

**Comment by maxkadel** [comment]
Starting in February 2023, the 653 fields were no longer being stripped. @mzelesky is finding examples to share for testing.

**Comment by mzelesky** [comment]
Record with a 653 field that has multiple subfield a:
9925459873506421

Record with multiple 653 fields:
9925493943506421

Miscellaneous records with 653 fields:
9925508433506421
9925505643506421
9925496713506421
9925496093506421
9925494973506421
9925494093506421
9925493823506421
9925492163506421
9925474453506421
9925473353506421
9925466353506421

**Comment by mzelesky** [comment]
Here is a report of all 653 fields in PUL records, including the number of bibs that contain each field. https://docs.google.com/spreadsheets/d/1VgWYcZ1yW1EdlxN4G2tX5chIMOvZohXfg84tT6wwgBw/edit?usp=sharing

**Comment by maxkadel** [comment]
[Per Esmé](https://pulibrary.slack.com/archives/CA891BNR0/p1684871645803389), whether / how this field should be indexed is still under discussion by DSSG.

**Comment by escowles** [comment]
Jennifer reported back that she looked for email or notes on why she requested this and couldn't find anything. So I'm going to close this issue and we can revisit if she remembers where this request came from or someone else asks about it.

**Comment by escowles** [comment]
Reopening as new use cases for indexing 653 have surfaced. Minjie noted that non-Roman items because other fields included Romanized values, often without translation, but 653 includes English-language topic/format terms. A sample record is: https://catalog.princeton.edu/catalog/9951301943506421 (which includes "toy making" in a 653 which is otherwise not included in the record).

DSSG decided that these should be indexed but not displayed.

**Comment by sandbergja** [comment]
We can discuss this in the next Orangelight meeting.

**Comment by maxkadel** [comment]
@mzelesky is following up with stakeholders and will come up with a plan. May take a few weeks.

**Comment by mzelesky** [comment]
A meeting is scheduled for next week.

**Comment by kevinreiss** [comment]
No final decision until Jennifer returns from vacation at the end of Sept.

**Comment by mzelesky** [comment]
I met with Minjie Chen, Don Thornbury, and Beck Davis today about the 653 fields in Cotsen records.

The agreed plan of action is to compare all the 653 fields in the Cotsen records with all LCSH authorities (authorized headings and references) to see which ones can be easily mapped to LCSH with no further intervention.

After that process, we will evaluate what to do next. One potential solution raised by Minjie was to add 500 fields for the remaining Cotsen records with 653 fields similar to the following format:

500  __ $a Uncontrolled keywords: Toy-making; Toys, wooden.

**Comment by maxkadel** [comment]
@mzelesky  - Moved to backlog. Let us know whether further action is needed from the DACS team from this, or whether it can be closed.

**Comment by mzelesky** [comment]
I believe this can be closed. Other avenues are being pursued for the 653 fields in Cotsen.

**Comment by kevinreiss** [comment]
Discussed at Alma-DACS 1/9. CaMS is pursuing other avenues to make this data usable using LCSH subject headings added to the records.
