### ISSUE TITLE
'Changed Records' events are missing before 11/1/2022

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2058]
https://pulibrary.slack.com/archives/C031U4XCUH2/p1673012458251949
I was reviewing the bibdata events page and deleted three Full Partner Recap Records from 2021. I scrolled down to review the events and decide what dates and events to clear, as part of a maintenance ticket. 
I noticed that the event ‘Change Records’ which is the one that the incremental publishing job creates daily exists in the events page after 2022-11-01 which is odd.
Based on my calendar a full reindex ran on 10/31/2022 .

- Is there a history table where we can see any kind of changes?
- Was there any code update in bibdata before 11/1/2022 that could have caused this bug?
- Create in bibdata-staging changed records and partner events and see if you can replicate this. 
- Did someone delete Changed records before 11/1/2022?

**Comment by sandbergja** [comment]
Could it be this cron job? https://github.com/pulibrary/bibdata/blob/main/config/schedule.rb#L42-L44

This part seems to remove all incremental Events from the past two months: https://github.com/pulibrary/bibdata/blob/main/lib/tasks/marc_liberation.rake#L5

If the cron job was last run on Sunday, Jan. 1, that would explain why everything before November is missing.

**Comment by christinach** [comment]
@sandbergja you are right! I totally forgot about this job and the date that these events were cleared made me think that something else was going on. I'm closing this as resolved. Thanks !
