### ISSUE TITLE
Marquand$pv items should limit pick-up choices to only the Marquand Library

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2066]
Currently Marquand$pv items can be requested for delivery to any location. This should be limited to Marquand only.

**Comment by christinach** [comment]
@kevinreiss In this case is delivery location the one that has PJ or PZ https://bibdata.princeton.edu/locations/delivery_locations ?

**Comment by christinach** [comment]
per @kevinreiss https://pulibrary.slack.com/archives/C031U4XCUH2/p1674742310498019
