### ISSUE TITLE
Update marquand$pv holding location flag values

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2067]
The marquand$pv holding location should have the "open" flag set to false. It should have the recap_edd flag set to "true". It should have the same settings as marquand$pj.

**Comment by christinach** [comment]
@kevinreiss 'marquand$pj' has 'recap_edd: false', but we want 'marquand$pv' to have recap_edd: true. 
Which are the settings that are the same between the two locations ? I'm pasting below 'marquand$pj' and 'marquand$pv' with the two updated settings you requested in this ticket and the updated delivery location from ticket #2066 .

{
        "label": "Remote Storage (ReCAP): Marquand Library Use Only",
        "code": "marquand$pv",
        "aeon_location": false,
        "recap_electronic_delivery_location": true,
        "open": false,
        "requestable": true,
        "always_requestable": false,
        "circulates": true,
        "remote_storage": "recap_rmt",
        "fulfillment_unit": "Closed",
        "url": "https://bibdata.princeton.edu/locations/holding_locations/marquand$pv.json",
        "library": {
            "label": "Marquand Library",
            "code": "marquand",
            "order": 0
        },
        "holding_library": null,
        "delivery_locations": [
            "PJ"
        ]
    },

{
        "label": "Remote Storage (ReCAP): Marquand Library Use Only Rare Books",
        "code": "marquand$pz",
        "aeon_location": true,
        "recap_electronic_delivery_location": false,
        "open": false,
        "requestable": true,
        "always_requestable": true,
        "circulates": false,
        "remote_storage": "recap_rmt",
        "fulfillment_unit": "Closed",
        "url": "https://bibdata.princeton.edu/locations/holding_locations/marquand$pz.json",
        "library": {
            "label": "Marquand Library",
            "code": "marquand",
            "order": 0
        },
        "holding_library": {
            "label": "Marquand Library",
            "code": "marquand",
            "order": 0
        },
        "delivery_locations": [
            "PJ"
        ]
    },

**Comment by christinach** [comment]
sorry I was looking marquand$pz
