### ISSUE TITLE
barcode endpoint needs to be updated to accommodate the non-requestable ReCAP location

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#2071]
See 32101076551454 in the barcode endpoint with the 'scsb' at the end. 
https://bibdata.princeton.edu/barcode/32101076551454/scsb
The new non-requestable locations (xmd, xmgr, etc.) need to be accommodated for sending the ReCAP-specific information to SCSB for accessions.

**Comment by kevinreiss** [comment]
These two methods need to be aware of the new locations: https://github.com/pulibrary/bibdata/blob/e216a5573c858569ab133ae3821c9b0bb445c1e1/app/adapters/alma_adapter/alma_item.rb#L164-L182.

**Comment by mzelesky** [comment]
The methods attached to https://github.com/pulibrary/bibdata/blob/e216a5573c858569ab133ae3821c9b0bb445c1e1/app/adapters/alma_adapter/alma_item.rb#L184 also need to be addressed.

**Comment by regineheberlein** [comment]
@mzelesky Are the new locations considered "supervised use"?

**Comment by regineheberlein** [comment]
The new non-requestable ReCAP locations are:
xgr
xcr
phr
xrr
xmr

**Comment by carolyncole** [comment]
xmr will have the same restrictions as xm.  Similar for all locations above.
