### ISSUE TITLE
Mark items with shared retention agreements, with a CGD of "Committed" when accessioned into SCSB

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#2076]
### User story
Items marked for retention commitment in ReCAP will have the proper Collection Group Designation (CGD) of 'Committed' assigned in SCSB after accession.

### Acceptance criteria

- [ ] For an item that returns the values in the API response described in the notes, the CGD will have to be 'Committed' instead of 'Shared'.

### Notes

- The API call that retrieves the item information (`/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}`) has
`"committed_to_retain": {
      "value": "true",
      "desc": "Yes"
    },`
  in the `item_data` section, AND in this section:

  `"retention_reason": {
      "value": "ReCAPItalianImprints",   
      "desc": "ReCAP Collaborative Collection Development Italian Imprints"
    },
    "retention_note": ""
  }`

- If the response doesn't include the above information then the CGD will be based on the location only.

-   For now, this is the only shared retention program we are participating in, but there will be others ("retention_reason" "value").

- The updated CGDs will be included in the response of the bibdata barcode controller that SCSB's accession processing calls.

### Concrete example
In the sandbox, see https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/99126831126106421/holdings/22961480120006421/items/23961480110006421

The barcode is 32101119327524.

### Re-index required?

- [ ] Full re-index
- [ ] Partial re-index
- [x] No re-indexing required

### Implementation notes, if any
Records are anticipated to be loaded in March 2023.

**Comment by kevinreiss** [comment]
The updated CGDs will be included in the response of the bibdata barcode controller that SCSB's accession processing calls.

**Comment by carolyncole** [comment]
https://github.com/pulibrary/bibdata/blob/main/app/controllers/barcode_controller.rb#L14

**Comment by sandbergja** [comment]
The desired end result is that:

1. The SCSB goes to https://bibdata.princeton.edu/barcode/[BARCODE_OF_SCSB_ITEM]/scsb
2. If the alma endpoint @mzelesky documented has `"committed_to_retain": { "value": "true", "desc": "Yes" }`, bibdata will return a MARC record that includes an 876$xCommitted, rather than 876$xShared.
3. If the alma endpoint doesn't have this `committed_to_retain` info, then keep the current behavior.

**Comment by mzelesky** [comment]
I updated the description with a ReCAP record to allow for better testing.

**Comment by christinach** [comment]
> 3\. committed_to_retain

@mzelesky and I reviewed again the ticket and we should also consider the retention_reason with value "ReCAPItalianImprints". We expect to have more values in the future. Some values will not result in a "Committed" CGD. 
When a new value comes @mzelesky will create a ticket.

**Comment by christinach** [comment]
> The desired end result is that:
> 
> 1. The SCSB goes to [https://bibdata.princeton.edu/barcode/[BARCODE_OF_SCSB_ITEM]/scsb](https://bibdata.princeton.edu/barcode/%5BBARCODE_OF_SCSB_ITEM%5D/scsb)
> 2. If the alma endpoint @mzelesky documented has `"committed_to_retain": { "value": "true", "desc": "Yes" }`, bibdata will return a MARC record that includes an 876$xCommitted, rather than 876$xShared.
> 3. If the alma endpoint doesn't have this `committed_to_retain` info, then keep the current behavior.

@mzelesky and I reviewed again the ticket and we should also consider the retention_reason with value "ReCAPItalianImprints". We expect to have more values in the future. Some values will not result in a "Committed" CGD.
When a new value comes @mzelesky will create a ticket.
