### ISSUE TITLE
Add the updated proxy_base in bibdata to 856 link during indexing time

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2081]
### User story
We still have subscription content links that need to pass through access and authorization rules in our EZproxy stored in 856 links. This feature enables us to only invoke the proxy on a known subscription domain. This also lets us retire a legacy application (https://github.com/PrincetonUniversityLibrary/resolve) that has the same purpose this feature will accomplish.

### Acceptance Criteria
- [ ] The current list of "subscription" hosts that can appear in 856 is at: https://github.com/PrincetonUniversityLibrary/ezproxy_conf/blob/main/shim/hosts.dat. This data needs to be available to bibdata, we could add the CSV to the project or load it into a database table.As the clean-up of e-resource data in the Alma moves forward this list will only shrink, new entries will NOT be added to the list at this point.  
- [ ] Create a new field that stores eligible links with the prepended proxy field. Current field name is electronic_access_1display. The data in the existing filed should remain as it is.  
- [ ]  Links with a domain not on this list should not have any proxy information prepended to them. This is a change in behavior since every link derived from a 856 value now has the proxy prepended to it.
- [ ] The proxy_base URL itself needs to change. It will move directly to ezproxy https://login.ezproxy.princeton.edu/login?url from the current value of https://library.princeton.edu/resolve/lookup?url=.
- [ ] Confirm that the logic in OL that dealt with Open Access titles, princeton arks, and Princeton IIIF urls does not need to be replicated. I do not believe .princeton.edu URLs are in the hosts.dat file so there are likely no conflicts with those two. The Open Access logic may need to be recreate though since that required checking the 856 label value in addition to the URL to see if the proxy prefix should be pre-pended. 
- [ ] Complete OL https://github.com/pulibrary/orangelight/issues/3433

### Example Record
https://catalog.princeton.edu/catalog/9998970333506421

### Re-index required?

- [x] Full re-index
- [ ] Partial re-index
- [ ] No re-indexing required

### Implementation notes, if any
* Specs related to this feature in OL are here: https://github.com/pulibrary/orangelight/blob/d7b1255e14f3f117774ef47207b4a519bfbc0ee5/spec/services/online_holdings_markup_builder_spec.rb#L87
* this is the method that builds the link: https://github.com/pulibrary/orangelight/blob/d7b1255e14f3f117774ef47207b4a519bfbc0ee5/app/services/online_holdings_markup_builder.rb#L28

**Comment by kevinreiss** [comment]
PR related to this work: https://github.com/pulibrary/bibdata/pull/2090
