### ISSUE TITLE
Republish objects with Indigenous peoples of Mexico and North America subject headings

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#2126]
For context please see https://github.com/pulibrary/bibdata/issues/2119, which fixed the bug causing the issue.

Republish any works in Alma with subject headings with the form `$a Indians of Mexico $z Mexico` or `$a Indians of North America $z North America`, which had been created incorrectly. 

Further records affected by this bug will be addressed in the next full reindex.

**Comment by kevinreiss** [comment]
I think we can close this because of the recent full re-index?

**Comment by sandbergja** [comment]
Good call, @kevinreiss !  Closing.
