### ISSUE TITLE
Scanned map resource does not have coverage_display

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#2135]
### Expected behavior
Records with a valid 034 field (["Coded Cartographic Mathematical Data"](https://www.loc.gov/marc/bibliographic/bd034.html) should have a `coverage_display` field in their Solr document when indexed. 

### Actual behavior
Working record: https://catalog.princeton.edu/catalog/9977102743506421/raw includes 
```json
"coverage_display":["northlimit=039.970867; eastlimit=116.458477; southlimit=039.846038; westlimit=116.300205; units=degrees; projection=EPSG:4326"]
```

Non-working record does not include `coverage_display` - https://catalog.princeton.edu/catalog/9941463973506421/raw 

### Impact of this bug
The record cannot be indexed in pulmap until this is addressed. This was first reported in https://github.com/pulibrary/orangelight/issues/3496 

### Re-index required?

- [ ] Full re-index
- [x] Partial re-index
- [ ] No re-indexing required

### Implementation notes, if any
Look at https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/geo.rb and https://github.com/pulibrary/bibdata/blob/main/spec/marc_to_solr/lib/geo_spec.rb

**Comment by maxkadel** [comment]
When looking at the Alma record, it appears that the 034 subfield e has an invisible character that makes it not a valid coordinate format. This only became apparent when pasting the value into an editor

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/dc3cba40-10d0-4ac6-a10e-ca88713c58ba)

A cataloger should correct the record, and it should be caught in the next incremental. @eliotjordan

**Comment by mzelesky** [comment]
The record was corrected at 4:15 PM, so it should be in the 10 PM publishing job.
