### ISSUE TITLE
Augment the subject list for indigenous studies (with LCSH terms updated in April 2023)

### ISSUE THREAD

**Issue by minjiec** [pulibrary/bibdata#2150]
Hello! This issue is a continuation of issue #1863. The list of LCSH about indigenous peoples of the Western Hemisphere has been updated. See [(2023-04) LCSH for Indigenous peoples in Western Hemisphere](https://docs.google.com/spreadsheets/d/1tbS54gJtrLCNS6xMxeb0DD4dOuQL8xZT-c0TQIi2I0w/edit#gid=565995152)

A few things to note about the spreadsheet.

- Tab 1 LCSH contains 5758 LC subject terms that can be implemented to tag bib records with "Indigenous Studies" in Blacklight. 
(1) Over 900 terms were added, and they have the date stamp **2023/04** in the last column.
(2) I have removed a term [Luso-Indians](https://en.wikipedia.org/wiki/Luso-Indian) from last year's list and please update your code accordingly. The term is about people in India. (Since the library has no material about this suject, no bib has been erroneously tagged as IS on account of this term.)

- Tab 2 "Additional subfields" has also grown.

**Comment by sandbergja** [comment]
closed by #2153
