### ISSUE TITLE
Add 506 subfields g for dissertation restrictions

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#2157]
Dissertation records for new dissertations are derived from ProQuest XML and include relevant restrictions information for these items in 506 subfield g, 506 subfield 5 fields, vetted by Lynn Durgin and Don Thornbury.

These subfields should be indexed to trigger behavior indicating users must request an in person viewing of the material at Mudd Library.  As they appear now, embargo dates do not appear in the restrictions note (see example here - https://catalog.princeton.edu/catalog/99127127233306421/), The presence of these two subfields in combination will be used to trigger behavior in OL to a SC approved workflow for handling requests for embargoed materials. 

Please let me know if you have any questions!  Thank you!

Here's the other example record (there is no restriction on it): https://catalog.princeton.edu/catalog/99127127233206421

## Implementation notes:

- [x] Create updated examples
- [ ] Index 506$g when 506$5 is present with a value of NjP
- [ ] Transform subfield g into a human readable date. (MARC record has 20230420, we will convert it into MM/DD/YYYY e.g. 04/20/2023)
- [ ] Test sample record in bibdata-staging
- [ ] Deploy bibdata with code to production
- [ ] Mark all impacted records for re-index in production Alma
- [ ] Confirm fields are indexed properly.

**Comment by mzelesky** [comment]
I have modified 99127127233306421 to have the following note:

 |a This dissertation is under embargo until 04/20/2023. |c A digital copy is available for viewing in the Mudd Manuscript Library reading room during the embargo period. If you are interested in this service, please fill out the Ask Us form using the following link. |u https://library.princeton.edu/ask-us |f No online access. |g 20230420 |2 star

I think having the date as a machine-readable date in the 506|g in addition to a human-readable date in 506|a will make it easier to format. That way, the 506|g can be used to power embargo functionality while traject doesn't have to re-word the note.
