### ISSUE TITLE
Check Traject config for use of Basic Auth

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#2165]
In CI, we want to be able to use basic auth for indexing via Traject, and it doesn't seem to be working right now. 

To get around this in the meantime, we've set the CI configuration to `BlockUnknown: false` (see [PR in pul_solr](https://github.com/pulibrary/pul_solr/pull/362))

We might check any overrides that match https://github.com/traject/traject/pull/262/files

**Comment by maxkadel** [comment]
[PR where file was pulled into Bibdata](https://github.com/pulibrary/bibdata/pull/1678/files) - is there a more targeted way we could add the utf-8 validation, so we would get updates to this file from the gem?

**Comment by kevinreiss** [comment]
Solr is secure in the sense that only certain IP addresses can connect to it. Closing ticket based on this.

**Comment by maxkadel** [comment]
Accidental re-opening.
