### ISSUE TITLE
Add indexing changes since Sept 2022 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2167]
Check the following file change histories to make sure our docs are up to date.

This is the documentation that needs to be updated: https://lib-confluence.princeton.edu/display/ALMA/MARC+fields+indexed+in+Blacklight

- [x] Orangelight [catalog_controller.rb](https://github.com/pulibrary/orangelight/blob/main/app/controllers/catalog_controller.rb)
- [x] Pul_solr [solr_config.xml](https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-production-v2/conf/solrconfig.xml) [schema.xml](https://github.com/pulibrary/pul_solr/blob/main/solr_configs/catalog-production-v2/conf/schema.xml)
- [x] Bibdata traject configuration [traject_config.rb](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb), [princeton_marc.rb](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/princeton_marc.rb),

**Comment by sandbergja** [comment]
- [x] language indexing changes
- [ ] access note changes

**Comment by sandbergja** [comment]
@maxkadel and I will pair to look into the action note questions.

**Comment by sandbergja** [comment]
Finished with updates to confluence!
