### ISSUE TITLE
Stop indexing the action_notes_display field

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/bibdata#2173]
This field is no longer being used in the catalog (we are using the action_notes1_display instead).  We should stop indexing it.

There is a [related ticket in Orangelight](https://github.com/pulibrary/orangelight/issues/3611) (although, since we are using FlipFlop, these two tasks can be done in either order).

- [Method to remove](https://github.com/pulibrary/bibdata/blob/5a35c7e22210240f0dc924a0fb7d9239da3f057b/marc_to_solr/lib/traject_config.rb#L808-L815)
- Run the tests and note which ones fail
- [Tests to look at / update](https://github.com/pulibrary/bibdata/blob/main/spec/marc_to_solr/lib/config_spec.rb)

**Comment by maxkadel** [comment]
Closed by https://github.com/pulibrary/bibdata/pull/2181

Deployed to production 7/7/2023
