### ISSUE TITLE
Link does not work in docs/location_changes.md

### ISSUE THREAD

**Issue by lizgarciao** [pulibrary/bibdata#2214]
[Location of invalid link in bibdata repo](https://github.com/pulibrary/bibdata/blob/main/docs/location_changes.md#:~:text=https%3A//github.com/PrincetonUniversityLibrary/alma%2Dconfig/issues).

The invalid link is the first one that appears in the document.

**Comment by christinach** [comment]
@lizgarciao You dont have access in https://github.com/PrincetonUniversityLibrary/ this is why it doesn't load for you. I will close this issue .

**Comment by christinach** [comment]
But will update the docs link to say that is a private repo and you may have no access. Thanks for finding it.
