### ISSUE TITLE
Change `bibliographic` endpoint to use SRU rather than API 

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#2239]
- When we have a crawler event that hits certain Orangelight endpoints (e.g. staff_view, .ris, .endnote), it can quickly use up our Alma api calls
- Currently, these calls go to the bibliographic endpoint (`"#{Requests.config['bibdata_base']}/bibliographic/#{id}"`, which then calls the Alma API

## Acceptance criteria
- The data provided from the bibliographic endpoint does not change
- The data is sourced from a call to the [Alma SRU](https://developers.exlibrisgroup.com/alma/integrations/sru/), rather than the Alma API.

**Comment by christinach** [comment]
@maxkadel tested it successfully on catalog-staging. Waiting for exlibris to see if we can put it in production.
