### ISSUE TITLE
Please index two dissertations in staging

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#2265]
Please index 99129108711406421 and 99129104070306421 in catalog-staging for review by Lynn Durgin and Christa Cleeton.  These are dissertations, one with an embargo in the 506 field, and one without.

**Comment by kevinreiss** [comment]
We need to do scenario 1 here: https://github.com/pulibrary/bibdata/blob/main/docs/test_indexing.md

**Comment by kevinreiss** [comment]
@kelynch the files are here: https://catalog-staging.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=99129104070306421+OR+99129108711406421

give them a look.

**Comment by kevinreiss** [comment]
On https://catalog-staging.princeton.edu/catalog/99129108711406421/ there is a 506g value set but our indexing expects that to be processed as embargo when subfield 5 in 506 is set to NjP, https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/embargo_date_extractor.rb#L15-L16. Feature commit. https://github.com/pulibrary/bibdata/pull/2170/files.

**Comment by kevinreiss** [comment]
Can we add that value to the record with a 506 and a 506 to the other record and retry?

**Comment by kelynch** [comment]
Sorry, just to clarify, the source record for https://catalog-staging.princeton.edu/catalog/99129104070306421 does not have an embargo at the source.  The source record for https://catalog-staging.princeton.edu/catalog/99129108711406421 does have one, however.  It looks like the "NjP" value being missing from 506 subfield 5 is what's causing the date parsing issue, is that right?

**Comment by kelynch** [comment]
The two records have been imported into Alma sandbox, with the following MMS IDs:
```
99129112208506421
99129112208406421
```

**Comment by christinach** [comment]
@kelynch the two records were indexed today.
https://catalog-staging.princeton.edu/catalog/99129112208506421
https://catalog-staging.princeton.edu/catalog/99129112208406421

Please review them and let us know if you need a new reindex. Otherwise we can close the ticket. Thank you.

**Comment by kevinreiss** [comment]
@kelynch, I think this issue can be closed, re-open if you think otherwise. However to fully display the restrictions dates for the embargo we will have to implement, see https://github.com/pulibrary/bibdata/issues/2267 for what still needs to be done to get this displayed.
