### ISSUE TITLE
New Alma location firestone$tech

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#2276]
See https://github.com/PrincetonUniversityLibrary/alma-config/issues/780

The location should never have any items sent to bibdata. In this case, does the location need to be added to bibdata?

**Comment by christinach** [comment]
@mzelesky do you mean that the publishing job will never publish items that are in location: 'firestone$tech'? Which would mean that we will not index these items. 
If that's the case, then we don't need to add firestone$tech in bibdata.

**Comment by mzelesky** [comment]
Yes, that is what I mean. Thank you for that feedback, I will only create tickets in the future when the new location is expected to appear in bibdata. Please close if appropriate.

**Comment by mzelesky** [comment]
The understanding was incorrect about this location. See https://github.com/PrincetonUniversityLibrary/alma-config/issues/780 for the information needed for the location in bibdata.

**Comment by christinach** [comment]
I didn't understand that the record would be indexed to the catalog. I thought they were suppressed. I will add the location.
