### ISSUE TITLE
Full reindex of SCSB looks to old pathname

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2287]
### Issue
For old files that exist in`/data/bibdata_files/scsb_update_files` the index is trying to index them from `/data/marc_liberation/scsb_update_files`  which is the old pathname. 

### Impact:
Sidekiq will keep retrying jobs with a path that does not exist until they get deleted by sidekiq or an admin user.

**Comment by christinach** [comment]
- Searched the inode of one of these files to see if it's duplicate or symlinked to another path but it doesn't. 
- Checked /etc/mstab to confirm we dont have mounted marc_liberation to /mnt/....
- Confirmed that these files exist in the directory bibdata_files and not in marc_liberation
- Checked the retry sidekiq jobs to confirm that it has the path `/data/marc_liberation/scsb_update_files` for some old files.
- Searched princeton_ansible code base for any marc_liberation path.
- Searched bibdata code base for any marc_liberation path.
- Searched the rails vars on the boxes and confirmed that they have the bibdata_files path 
- `Deleted all` the jobs that have the deprecated path.

**Comment by kevinreiss** [comment]
Christina is triggering another import today.

**Comment by christinach** [comment]
1. The reason we see the old path is because we have very old events in the database with dump_files that have that path. We should delete them from the database. I will update the ticket and proceed with deleting them.
```
id: 2057,                                                                                        
 dump_id: 56,                                                                                     
 path: "/data/marc_liberation_files/scsb_update_files/scsb_update_20210813_072300_1.xml.gz",      
 md5: "59a2bcd37b6c8da52accdac78342467e",                                                         
 created_at: Wed, 18 Aug 2021 19:46:57.145286000 UTC +00:00,                                      
 updated_at: Thu, 23 Mar 2023 20:21:00.157730000 UTC +00:00,                                      
 dump_file_type_id: 3,                                                                            
 index_status: "enqueued">
```
2. next step: See why when we run the full scsb reindex it's indexing old scsb update files. It should index the latest full partner scsb dump file and the rest of the daily scsb dump files that were created after the scsb full dump.

**Comment by christinach** [comment]
following ticket to look into https://github.com/pulibrary/bibdata/issues/2294
