### ISSUE TITLE
Update delete events task to purge daily SCSB Partner Files and SCSB Partner Full files Older than two months. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2289]
### User story
I want manage disk space on the bibdata file server. I want to remove SCSB partner files older than two months from the /data/bibdata_files/scsb_update_files/ directory. 

### Acceptance criteria

- [ ] Create new rake task to remove old daily update SCSB files. There is already a task to delete events. We can add it there.
- [ ] Schedule task to be run be run on the first of every month.

**Comment by christinach** [comment]
I've cleaned the bibdata production database. 
Deleted daily scsb partner dumps older than 2 months.
Deleted SCSB Full partner dumps older than 2 months.
Updated existing task to delete older records older than 2 months. We had it older than 6 months.
