### ISSUE TITLE
Remove the rewrite of the "P" Patron Group to "staff"?

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2307]
We are looking at leveraging Alma Patron Group assignment as the driver for what request types users have access to in the catalog request form, see [patron group refactor](https://github.com/pulibrary/orangelight/issues/3188) ticket. We noticed that the bibdata patron controller currently [rewrites the "P" patron group as staff](https://github.com/pulibrary/bibdata/blob/main/app/controllers/patron_controller.rb#L64). Investigate if rolling this back has any unintended impact on features in bibdata/orangelight. 
See [staff only pick up locations](https://github.com/pulibrary/orangelight/blob/main/app/models/concerns/requests/bibdata.rb#L60-L62)

Remove the rewrite:
- [x] See which specs are failing.
- [x] Test it in catalog-qa.
- [x] Request an item from 
- [Firestone Library Microforms](https://bibdata.princeton.edu/locations/delivery_locations/30)
- [Preservation](https://bibdata.princeton.edu/locations/delivery_locations/29)
- [Microforms](https://bibdata.princeton.edu/locations/delivery_locations/28)

**Comment by kevinreiss** [comment]
Figgy may be tracking the type of patron group for statistics. Figgy has a service to talk to bibdata that can confirm this.

**Comment by rladdusaw** [comment]
Services that call the bibdata patron endpoint:
Figgy for GA logging of CDL: https://github.com/pulibrary/figgy/blob/43d6f5b628029d26be1f4677cc6917578132ea70/app/services/cdl/event_logging.rb#L40
Orangelight: https://github.com/pulibrary/orangelight/blob/68bfee3bb380151ce087f3b5dbaae9775e0ea8bb/app/services/bibdata.rb#L57

The patron data are used for statistics gathering in Figgy and used pretty extensively in Orangelight. 

The only location I could find where Orangelight checks the patron_group is in the [Illiad_patron model](https://github.com/pulibrary/orangelight/blob/68bfee3bb380151ce087f3b5dbaae9775e0ea8bb/app/models/requests/illiad_patron.rb#L53) but the patron_group is included in the [main request form](https://github.com/pulibrary/orangelight/blob/68bfee3bb380151ce087f3b5dbaae9775e0ea8bb/app/views/requests/request/_request_form.html.erb#L9) so other systems that Orangelight forwards requests to might be impacted as well.

**Comment by kevinreiss** [comment]
It looks like the illiad patron is using a lookup to campus ldap to determine status. With respect to the main request form, I think we include the attribute but don't actually do anything with it at the moment. For the CDL stats we should ask if it would be a big issue if one of the identifying strings for a patron were to change.

**Comment by rladdusaw** [comment]
Tested with:
https://catalog-staging.princeton.edu/catalog/99108246773506421
https://catalog-staging.princeton.edu/catalog/99127607755106421
