### ISSUE TITLE
Slow Postgres queries - Identify the root cause and write a ticket to fix it

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/bibdata#2312]
### Expected behavior
Postgres queries take less than a minute to complete - the norm seems to be spikes of 30 milliseconds, so this is a major outlier.

### Actual behavior
Beginning on January 25, 2024, we've started to get Postgres queries that are taking over 1 minute 30 seconds. [Example monitoring alert on Datadog](https://app.datadoghq.com/monitors/4727581?q=application%3Abibdata&source=monitor_notif&view=spans&from_ts=1707267241000&to_ts=1707268441000&eval_ts=1707268441000).

### Impact of this bug
Some queries are taking a very long time, likely causing errors in whatever upstream service is using these queries.

### Honeybadger link and code snippet, if applicable

```
```

### Re-index required?

- [ ] Full re-index
- [ ] Partial re-index
- [x] No re-indexing required

### Implementation notes
In Datadog (Maybe?) and on the postgres servers we are logging slow SQL Postgres queries.

**Comment by sandbergja** [comment]
This started happening after we changed the incremental indexing to be every two hours.  It also usually (but not 100% of the time) coincides with a time that browse lists are generated.

**Comment by sandbergja** [comment]
https://github.com/pulibrary/princeton_ansible/issues/3699 would help to give us useful information to troubleshoot this issue.

**Comment by maxkadel** [comment]
It does look like it is correlated with an Orangelight slow-down - see [datadog correlation search](https://app.datadoghq.com/correlations/53c3cd3a-ea2d-422e-8a7e-5775e87d8da4)

**Comment by maxkadel** [comment]
It appears that this has not occurred since 3/12/2024. Will try to gather logs now in case it pops up again.

**Comment by maxkadel** [comment]
Dates on which the alert occurred:

```
2024-01-26 04
2024-01-26 19
2024-01-30 00
2024-02-02 10
2024-02-03 17
2024-02-05 00
2024-02-05 16
2024-02-06 02
2024-02-07 01
2024-02-07 20
2024-02-10 01
2024-02-10 04
2024-02-13 23
2024-02-18 19
2024-02-23 17
2024-02-26 19
2024-02-27 15
2024-03-01 20
2024-03-03 03
2024-03-04 18
2024-03-05 11
2024-03-05 14
2024-03-05 17
2024-03-07 14
2024-03-07 17
2024-03-07 19
2024-03-07 21
2024-03-09 01
2024-03-11 10
2024-03-12 04
2024-03-12 07
```

**Comment by maxkadel** [comment]
The main datadog logs for this time period have already been purged.

**Comment by maxkadel** [comment]
Suggest closing until / unless this occurs again, since the logs needed for investigation are no longer available, and it does not appear to be occurring any more.
