### ISSUE TITLE
Investigate the figgy_ark_cache current behavior

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/bibdata#2330]
- [x] We are not sure how it is working with Alma or Voyager records currently.
- [x] Check to see if the rake task is running, and if it actually updates the cache when it runs.

**Comment by kevinreiss** [comment]
the production figgy ark cache is huge see this output

```
deploy@bibdata-alma1:/data/bibdata_files$ du -h
0	./campus_access_files
83G	./figgy_ark_cache
19G	./partner_update_scratch
12G	./scsb_update_files
```

**Comment by kevinreiss** [comment]
The last six files modified in prod, nothing since July 2021. 
```
-rwxr-xr-x 1 deploy www-data  43 Jul 16  2021 figgy_princeton_edu__catalog_json
-rwxr-xr-x 1 deploy www-data 135 Jul 16  2021 ark__88435_br86b689r
-rwxr-xr-x 1 deploy www-data 135 Jul 16  2021 ark__88435_rv042x39q
-rwxr-xr-x 1 deploy www-data 135 Jul 16  2021 ark__88435_df65vc17f
-rwxr-xr-x 1 deploy www-data 135 Jul 16  2021 ark__88435_6395wb422
```

**Comment by kevinreiss** [comment]
83990 non hidden files in the directory.

**Comment by kevinreiss** [comment]
Noting ALL files in the directory were created on 7/16/2021.

**Comment by kevinreiss** [comment]
Clearly this https://github.com/pulibrary/bibdata/blob/f83b373fab64d3dc5edc6b7efd5cb9d8d6be1407/lib/tasks/orangeindex.rake#L145 isn't clearing anything. The system is correctly configured to find the cache in directory at ```/data/bibdata_files/figgy_ark_cache```.

**Comment by kevinreiss** [comment]
Looks like the task requires a param be passed to it to decide which directory it should operate on: https://github.com/pulibrary/bibdata/blob/f83b373fab64d3dc5edc6b7efd5cb9d8d6be1407/lib/tasks/orangeindex.rake#L150. Other wise it will use this as a default ```/opt/bibdata/current/tmp/figgy_ark_cache```

**Comment by kevinreiss** [comment]
We think this is specifically broken because of changes to the blacklight json api (changed approximately two years ago).

**Comment by kevinreiss** [comment]
See the results from https://github.com/pulibrary/figgy/issues/6324 and then re-assess this ticket.

**Comment by maxkadel** [comment]
DLS will work on this the week of May 8.

**Comment by christinach** [comment]
See [further discussion in slack](https://pulibrary.slack.com/archives/C9ZM9RX4J/p1715105505667769)
