### ISSUE TITLE
Remove unused input fields from homepage

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2331]
### Current display
Home page has input fields: `Get an Alma Record`, `Get Holdings`, `Get Items`
These fields where used when we had Voyager. No one is using them now.

### Desired display
Homepage should not have the input fields `Get an Alma Record`, `Get Holdings`, `Get Items``

### Acceptance criteria

- [x] I can successfully use this feature with Voice Over in Safari.
- [x] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

**Comment by kevinreiss** [comment]
What should we put in place of the form fields?

**Comment by christinach** [comment]
@kevinreiss  [ticket 2328](https://github.com/pulibrary/bibdata/issues/2328) will basically update the homepage
