### ISSUE TITLE
Label backlog tickets that miss a template with the new `template-update` label

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2337]
### What maintenance needs to be done?
In order to make the tickets readable, actionable and more accessible we want all the existing tickets to use a template.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
To make the tickets readable, actionable and more accessible

### Acceptance criteria
 - [ ] All the backlog tickets use a template

### Notes
Part of (@sandbergja and @christinach) accessibility goal
Related to https://github.com/pulibrary/dacs_handbook/issues/166

**Comment by kevinreiss** [comment]
Looks like this has been done for bibdata.
