### ISSUE TITLE
Make Sure rake alma:setup_keys can pull a valid Alma key

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2338]
Currently this task is broken since the Lastpass entry it looks for has gone away. 

Acceptance criteria:

1. Obtain valid key from the ExLibris developer portal
2. Re-create the note in LastPass

**Comment by kevinreiss** [comment]
Confirmed that the ATT team does not use lastpass for key management. We can re-create the same note after getting a valid read-only for bibdata from the Ex Libris developer portal. This entry was probably deleted in error.

**Comment by maxkadel** [comment]
Re-created lastpass note.
