### ISSUE TITLE
Don't index Private SCSB records

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2383]
### What maintenance needs to be done?
The following are the CSV files that are being generated with each full partner dump:
[ExportDataDump_Full_HL_20240515_230000.csv](https://github.com/pulibrary/bibdata/files/15421991/ExportDataDump_Full_HL_20240515_230000.csv)
[ExportDataDump_Full_NYPL_20240515_150000.csv](https://github.com/pulibrary/bibdata/files/15421994/ExportDataDump_Full_NYPL_20240515_150000.csv)
[ExportDataDump_Full_CUL_20240515_070000.csv](https://github.com/pulibrary/bibdata/files/15421995/ExportDataDump_Full_CUL_20240515_070000.csv)

We want to make sure that we download full dumps from partners with the attached CSV to have the following codes `collection group Id(s): 1*2*5*6`

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- Full dumps from partners in S3 may include private records (collection group Id: 3). We don't want to index them.

### Acceptance criteria
 - [ ] Don't import a full dump that the attached CSV includes '3' in the collection group Id(s) column.

**Comment by maxkadel** [comment]
Requested private CUL records to be sent from / to UAT 5/29/2024, waiting for them to be marked delivered.

**Comment by sandbergja** [comment]
This has been tested in staging, and it works great!  Closing.
