### ISSUE TITLE
FTP failure on jobs that use lib-sftp

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#2400]
### Expected behavior
There have been sporadic FTP failures since June 7th (accessing lib-sftp), and all publishing jobs since June 11th have failed. This includes POD and the Blacklight incremental publishing jobs. I am creating a ticket in princeton-ansible as well, as this also affects our financial integrations.

**Comment by kevinreiss** [comment]
@christinach @mzelesky is there futher investigation to be done here or did our recent steps to address file rotation issues stemming from our disk space issues cover it?

**Comment by maxkadel** [comment]
Closing - investigated and related to disk full errors, addressed under other tickets.
