### ISSUE TITLE
Some incremental files not indexed by Orangelight

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#2402]
### Expected behavior
All files published by Alma are ingested.

### Actual behavior
https://catalog.princeton.edu/catalog/9963574423506421/raw shows an update date of the record of May 22nd, 2024, but the record appeared in incremental_38210657830006421_20240612_090624[022]_new and incremental_38208282420006421_20240612_000634[059]_new. I am unsure if all the records from those 2 files were skipped, but at least 9963574423506421 was

### Impact of this bug
Updates from those 2 files are not reflected in the catalog

**Comment by christinach** [comment]
While I was working on https://github.com/pulibrary/bibdata/issues/2411 I checked the bibdata VM and these two incremental files never made it to bibdata.

**Comment by kevinreiss** [comment]
@christinach can we close this or is there further investigation to do?

**Comment by maxkadel** [comment]
Related to full disk on lib-sftp and that Alma should not generate a file for a failed job, resolved in other tickets.
