### ISSUE TITLE
Remove mailer configuration ~Move to new Mail Relay Server~

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/bibdata#2404]
Bibdata does not send mail, so mailers and mail configuration should be removed.

~Review the following PRs for each of our application that utilizes the mail relay.  Confirm that the following is true after deploying to prod:~

- ~I can still send and receive emails~
- ~/var/log/mail on lib-ponyexpr-prod shows that the mails are sent successfully~
- ~For a rails app, make sure that `enable_starttls` is false.  See https://github.com/pulibrary/orangelight/pull/4026 and https://github.com/pulibrary/pdc_describe/pull/1843 for examples.~

**Comment by maxkadel** [comment]
Per discussion in team meeting, we do not actually send mail from the bibdata servers.
