### ISSUE TITLE
Allow 773/774 fields to have institution identifier prefix before MMS ID

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#2413]
### Current indexing
https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/princeton_marc.rb#L820 only accepts 773 and 774 fields that have $w that starts with `99` and ends with `6421`. 

### Desired Indexing
To allow our records to follow the MARC format (see https://www.loc.gov/marc/bibliographic/bd760787.html for $w), we need to add in Alma the prefix `(NjP)` to all 773 and 774 $w. 

(important:)This will break the current indexing routine unless we support
`valid_linked_fields` to accept a $w that may or may not start with `(NjP)` as long as there is a valid MMS ID that ends the subfield.

Examples:
773  __ $w (NjP)9923506421
773 __ $w 9923506421

This will allow both ways to work while we remediate the bib records.
### Acceptance criteria
- [ ] 773 and 774 linkages work (important:) with or without the presence of the `(NjP)` prefix - 

### Implementation Notes
From @christinach on slack:
```The index will accept 773 and 774 with a $w that may or may not start with (NjP) as long as there is a valid MMS ID that ends the subfield. When NJP is there and the mms_id is valid we will index Njp and the mmsid When Njp is not there and the mms_id is valid we will index the mmsid only.```

**Comment by sandbergja** [comment]
Closed by #2422
