### ISSUE TITLE
Alert in slack when the bibdata event is created from a failed Alma job

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2416]
### What maintenance needs to be done?
Create an alert to trigger in the slack channel when a Bibdata event is created from a failed Alma job. 
### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- We want to be notified when for any reason an Alma job fails.

### Acceptance criteria
 - [ ] There is an alert that checks if bibdata created an event from a failed alma job.

### Implementation notes, if any

- Implement it in checkmk.

**Comment by maxkadel** [comment]
From what I can see, it is possible to set an alert to send slack messages from Honeybadger only for specific messages / based on a filter; however, this is a paid feature that we do not have access to.

**Comment by kevinreiss** [comment]
I like this idea. What is the cost point?

**Comment by sandbergja** [comment]
@kevinreiss will look at the Honeybadger Business Pricing Tier.
