### ISSUE TITLE
Update external name for firestone$pb

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/bibdata#2426]
### Current display
external name (label):
`Firestone Library - Remote Storage (ReCAP): Supervised use in Firestone`
to:

### Desired display
`Remote Storage (ReCAP): Firestone Library Use Only`

### Notes 
https://github.com/PrincetonUniversityLibrary/alma-config/issues/1209

https://bibdata.princeton.edu/locations/holding_locations/firestone$pb

**Comment by pmgreen** [comment]
@kevinreiss the external name seems to still be the old one: https://catalog.princeton.edu/catalog/99130262268006421

**Comment by christinach** [comment]
@pmgreen I haven't updated the locations I will do it now.
