### ISSUE TITLE
ReCAP Update Job Needs to Transfer File to Proper Endpoint

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#246]
API is at https://uat-recap.htcinc.com:9093/swagger-ui.html#!/shared-collection-rest-controller/submitCollection but that is only good for a small number of record updates. The batch cycle involves invoking SFTP and moving the file output by this job to one the ReCAP production environment. Details to follow.

**Comment by escowles** [comment]
@kevinreiss Has this been resolved?

**Comment by kevinreiss** [comment]
The job has been running on bibdata-dev since August but needs to moved over to bibdata production. It also only generates the data files. The step to SFTP the data to their destination on the SCSB project server also needs to be added. I'll try and finish it up this week at some point.
