### ISSUE TITLE
User has a difficulty finding microfilm in the library catalog

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2498]
### User story
User has a difficulty finding microfilm in the library catalog
 
### Acceptance criteria
- [x] Add microform -microfilm, microfiche, microcard- as a format.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [x] If a record has the character `h` in the first character of an 007 field, it should be represented as the `microform` format
- [x] A record that is microform should also be returned in a search for its other format (i.e., Journal, Book, Musical Score)

### Implementation notes, if any
Related to: [orangelight#3499](https://github.com/pulibrary/orangelight/issues/3499)

**Comment by mzelesky** [comment]
I updated acceptance criteria with the approach we have decided on for identifying a microform record.
