### ISSUE TITLE
Delete Alma location marquand$ph

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/bibdata#2500]
https://bibdata.princeton.edu/locations/holding_locations/marquand$ph
See: https://github.com/PrincetonUniversityLibrary/alma-config/issues/1150

**Comment by christinach** [comment]
There are still some items in marquand$ph https://github.com/pulibrary/bibdata/issues/2500
@pmgreen can you confirm when no items will be in this location so that we can delete it from bibdata?
