### ISSUE TITLE
Add Primary source to the genre facet

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/bibdata#2508]
### User story

As a librarian, I would like to teach students about primary source research using the catalog.

### Acceptance criteria

- [x] If the 6xx$v, 6xx$x, or 655$a has 0 as the value of indicator 2 (meaning it uses LCSH vocabulary), and is one of the following terms, it should have a genre facet entry of "Primary source"
  - archival resources
  - archives 
  - charters
  - correspondence
  - diaries
  - documents
  - early works
  - interview
  - interviews
  - letters
  - manuscripts
  - notebooks, sketchbooks, etc
  - oral history
  - oratory
  - pamphlets
  - personal narratives
  - sources
  - speeches
- [x] If the 6xx$v, 6xx$x, or 655$a is Biography, the field has 0 as the value of indicator 2 (meaning it uses LCSH vocabulary), and the 100abcdjq match the 600abcdjq, it should have a genre facet entry of "Primary source"
- [x] If it doesn't match those criteria, it should not have a genre facet entry of "Primary source" (although in the future, we may adjust/expand the criteria)
- [x] If this change touches any of the files referenced in `.rubocop_todo.yml` create a new ticket to address the rubocop  todo.

### Concrete example

* [993740223506421](https://catalog.princeton.edu/catalog/993740223506421) should have the Primary source label, since it has a 6xx$v Biography and the 100a matches the 600a.

**Comment by caroldh** [comment]
@ellen-aa @sandbergja  Thanks for meeting with us Jane! Sorry for the confusion :-)  Here is the amended (current) list of acceptance criteria that we want included:

charters
correspondence
diaries
documents
interview
interviews
letters
manuscripts
notebooks, sketchbooks, etc
oral history
pamphlets
personal narratives
sources
speeches
pictorial works
photographs
atlases
maps
law and legislation
statistics

I am not certain where we landed with the 6xx $v, $x, and $a? If Jane or Ellen, you remember?
