### ISSUE TITLE
SCSB Incremental Updates

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#262]
We need to develop a job that will:
1. Download new incremental updates from the HTC server, making sure to only retrieve files that have not yet been processed.
2. Scrub the updates using a marc_cleanup routine.
3. Replace/insert the records into Blacklight, processing the files in order of the date.
4. Archive the original file on a server.

The updates are stored as zip files on HTC's server. Each zip file has 1 xml file in it, named '0.xml'. The file needs to be renamed something a little more helpful. I would recommend the name of the zip file, with the xml extension.

**Comment by christinach** [comment]
This was done.
