### ISSUE TITLE
SCSB Records with 008 errors

### ISSUE THREAD

**Issue by tampakis** [pulibrary/bibdata#264]
From the incremental updates, some records had 008s that didn't have the expected fixed length, causing errors in Traject while indexing.
 - SCSB-3958246 (CUL-NYPL_20170908_210000.xml)
 - SCSB-3642541 (CUL-NYPL_20170909_210000.xml)

**Comment by mzelesky** [comment]
There is unfortunately little that can be done programmatically to address this. However, I will add 008 length to the list of errors I will report to the partners.
