### ISSUE TITLE
Listen/detect record updates in Oracle for Voyager

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/bibdata#418]
This should improve reindexing (as discussed on 07/16/18)

**Comment by jrgriffiniii** [comment]
Involves extending methods to detect records which have been updated (for enumeration/iteration)

**Comment by jrgriffiniii** [comment]
Client/user should also be able to specify a start date and an end date (as specified by @mzelesky)

**Comment by mzelesky** [comment]
The comment about start and end date was really for how one will retrieve the list of bibs with ARKs newly minted in Figgy.
