### ISSUE TITLE
Improve the handling for form/genre subdivisions in 655 subfields

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/bibdata#460]
This is necessary in order to resolve https://github.com/pulibrary/orangelight/issues/1352 given that the original structure of the subdivisions is not preserved during the indexing process:

`650    0 a| Fishing y| 19th century v| Bibliography.`
`655    7 a| Manuscripts y| 19th century. 2| aat`
`700    1   a| Sherwin, Henry Alden, d| 1842-1916, e| former owner. 0| http://id.loc.gov/authorities/names/nr95012470`
(http://catalog.princeton.edu/catalog/3388644/staff_view)

```
description_t: [
  "1 v. (97 leaves); 30 cm."
],
form_genre_display: [
  "Manuscripts 19th century."
],
format: [
  "Manuscript",
  "Book"
],
```
(http://catalog.princeton.edu/catalog/3388644.json)

**Comment by mzelesky** [comment]
This work should probably be grouped with the other work on subjects and genres that is occurring as part of the Blacklight Authorities group. There is a need to index the vocabulary used for the genres and subjects, and add genres to the subject browse.

**Comment by jrgriffiniii** [comment]
Thank you for clarifying this @mzelesky.  I have created a new "authorities" label for these types of issues, as well as two additional issues for these pending actions.

**Comment by christinach** [comment]
https://catalog.princeton.edu/catalog/9933886443506421
