### ISSUE TITLE
Log Bibs with Unknown Statuses

### ISSUE THREAD

**Issue by tampakis** [pulibrary/bibdata#53]
"Unknown" is the fallback status for bibs not online, in an open location, not on-order, or without item records. We should log/compile a list of all of these "unknown" bibs and figure out if we can actually assign them a status. Some examples:
https://pulsearch.princeton.edu/catalog/9167195
https://pulsearch.princeton.edu/catalog/9292387

**Comment by tampakis** [comment]
@joycebcat what should we do with records that don't have approval for purchase? https://pulsearch.princeton.edu/catalog/9468676
Should they be in the catalog at all?
Voyager includes "In the Pre-Order process" for records with a line_item_status of 0.

**Comment by joycebcat** [comment]
@tampakis "In the Pre-Order process" should be treated just like "on order" (once we decide how those should be treated).

**Comment by tampakis** [comment]
@joycebcat - I ran a report trying to log all of the bibs that return "Unknown" as its status. The query I wrote ran too slowly and after 24 hours of processing only got through 10% of all the records. I'm attaching the results here so maybe we can find some common patterns. After processing about 750,000 bib Ids it found 14,000 unknowns. https://www.dropbox.com/s/z853k7n40fk5nbh/unknown_mfhds_1.txt?dl=0

**Comment by mzelesky** [comment]
I think we can develop a couple of queries to find them in Oracle. I'll work on that. First, I'll find all bibs with holdings in open locations with no attached item records. Then, from there, I'll see which of those do not have order records attached to them. What is the list of non-open locations?

**Comment by tampakis** [comment]
I match it against all of the "always_requestable" locations here: https://bibdata.princeton.edu/locations/holding_locations

**Comment by joycebcat** [comment]
Thanks Nikitas and Mark.  I think from this initial list patterns will start to show up.  I can't remote into my new computer right now so I don't think I'll get to check this out until tomorrow.

**Comment by mzelesky** [comment]
I did an Oracle query on this and I will post a full file tomorrow. There are a lot more than I expected.

**Comment by mzelesky** [comment]
I have attached an Excel spreadsheet that shows the extent of 'unknown' status bibs. The SQL Query is included, but I will also provide it below. There were a total of 454,672 bibs and 459,492 MFHDs.
[unknownstatusbibs.xlsx](https://github.com/pulibrary/marc_liberation/files/109878/unknownstatusbibs.xlsx)


WITH Step1 AS (
SELECT BIB_TEXT.BIB_ID, MFHD_MASTER.MFHD_ID, MFHD_MASTER.LOCATION_ID, LOCATION.LOCATION_CODE 
FROM ((((BIB_TEXT INNER JOIN BIB_MFHD ON BIB_TEXT.BIB_ID = BIB_MFHD.BIB_ID) INNER JOIN MFHD_MASTER ON BIB_MFHD.MFHD_ID = MFHD_MASTER.MFHD_ID) INNER JOIN BIB_MASTER ON BIB_TEXT.BIB_ID = BIB_MASTER.BIB_ID) INNER JOIN LOCATION ON MFHD_MASTER.LOCATION_ID = LOCATION.LOCATION_ID) LEFT JOIN MFHD_ITEM ON MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID
WHERE BIB_MASTER.SUPPRESS_IN_OPAC = 'N' AND MFHD_MASTER.SUPPRESS_IN_OPAC = 'N' AND LOCATION.LOCATION_CODE NOT IN (
'beac', 'cook', 'crare', 'ctsn', 'ctsnrf', 'ed', 'elf', 'elf1', 'elf2', 'elf3', 'elf4', 'ex', 'exb', 'exc', 'exca', 'exf', 'exho', 'exi', 'exka', 'exki', 'exl', 'exme', 'exov', 'expa', 'exrc', 'exrl', 'extr', 'extsf', 'exv', 'exw', 'ga', 'garf', 'gax', 'gestrare', 'hsvc', 'hsve', 'hsvg', 'hsvm', 'hsvn', 'hsvp', 'hsvr', 'htn', 'hycrare', 'hyjrare', 'hykrare', 'jrare', 'krare', 'map', 'mss', 'mudd', 'mudf', 'njpg', 'num', 'numrf', 'pb', 'prnc', 'ptt', 'rcppg', 'rcpph', 'rcppz', 'rcpxc', 'rcpxg', 'rcpxm', 'rcpxn', 'rcpxp', 'rcpxr', 'rcpxx', 'rht', 'sa', 'safesrf', 'safi', 'saph', 'sarf', 'sat', 'sax', 'thx', 'thxr', 'vrg', 'w', 'wa', 'whs', 'wit')
AND MFHD_ITEM.ITEM_ID IS NULL)

SELECT Step1.BIB_ID, Step1.MFHD_ID, Step1.LOCATION_ID, Step1.LOCATION_CODE
FROM Step1 LEFT JOIN LINE_ITEM ON Step1.BIB_ID = LINE_ITEM.BIB_ID
WHERE LINE_ITEM.BIB_ID IS NULL;

**Comment by joycebcat** [comment]
@tampakis These are mostly items which aren't barcoded.  We should use a status of available assuming that they will be on the shelf as expected.  Since the list is relatively short, I'm going to see what we can do about investigating more properly and finding out what might actually be lost.

**Comment by kevinreiss** [comment]
What is the outcome we want for something like this bib ID: 77028 

In the current request system we say "ask circulation desk"
http://library.princeton.edu/requests/?bib=77028&loc=f&call_no=(HC300.295.W4%20N4%20)

The main catalog doesn't really provide any information at all:
http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?holdingsinfo?&BBID=77028&pds_handle=

How should we handle no barcode records that show up in open stack locations?

**Comment by joycebcat** [comment]
@kevinreiss  They should say "available".
@tampakis @mzelesky  Whoa, I was looking at 13,000.  Half a million is a different kettle of fish! I won't be investigating them more closely.

**Comment by kevinreiss** [comment]
@joycebcat Is an unbarcoded object in an open stack a common thing to encounter?

**Comment by mzelesky** [comment]
@kevinreiss The spreadsheet I uploaded shows locations where unbarcoded objects with no order status exist. The 2 major locations are Firestone Microfilms and Gov. Docs microform, but there are 250,000 or so such things in other locations.

**Comment by joycebcat** [comment]
@kevinreiss Yes.  Not as much in F any more since we barcoded over half a million monographs in a big project a few years ago.  Mark's report has half a million objects still in it over all locations.  Since Mark provided a full report, Marie and I are going to work on some things which fit a pattern and reduce the number a bit.

**Comment by kevinreiss** [comment]
In terms of what to display for the user should we indicate that these items are "On the Shelf" just like any other open stack item?

**Comment by joycebcat** [comment]
@kevinreiss They should say "available"
