### ISSUE TITLE
Return item data merged with holdings and bib info by bib ID

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#556]
An endpoint similar to

https://bibdata.princeton.edu/bibliographic/{bib_id}/item_info

would be useful, where the 876 and 852 records are formatted like the https://bibdata.princeton.edu/barcode/{barcode} response

**Comment by kevinreiss** [comment]
@mzelesky is there a use case for this feature?

**Comment by kevinreiss** [comment]
@mzelesky closing this. Please re-open if you think it needs more discussion.
