### ISSUE TITLE
Add additional $2 vocab code for si ku subject

### ISSUE THREAD

**Issue by tampakis** [pulibrary/bibdata#579]
There is an additional $2 vocab code that should be matched for the [siku_subject_display](https://github.com/pulibrary/marc_liberation/blob/master/marc_to_solr/lib/traject_config.rb#L749) field. Wait to hear from the East Asian Library to confirm, it's something like `skb`. Since it hasn't been added to any records yet, we won't need to do a reindex in order to activate the indexing

**Comment by sandbergja** [comment]
I wonder if it is the skbb code listed here: https://www.loc.gov/standards/sourcelist/subject.html

**Comment by sandbergja** [comment]
After talking with Martin and Lia in slack, it looks like we will need to index $2skbb into the siku_* solr fields, alongside the $2sk that are being indexed there currently.

We may just need to add some tests and update this method: https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/princeton_marc.rb#L797-L799

Lia shared a good fixture: MMS ID 9918309193506421.  It includes a subject with the sk and skbb vocabulary.  Only sk is displaying currently, but both should display.

There are now records that include skbb, so we will probably need to do a full reindex after we merge this.
