### ISSUE TITLE
Allow access to patron route for developers

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#610]
curl https://bibdata-staging.princeton.edu/patron/cac9 available from the devs boxes

Potentially VPN access

**Comment by carolyncole** [comment]
If we add VPN access this allows anyone on the university access to all the students and historical students. @kevinreiss we may not want to do this, since it allows anyone in the university access to student information that is not widely available.

**Comment by hackartisan** [comment]
closing as wontfix
