### ISSUE TITLE
776 and 787 should not be treated the same as 020 and 022 matches for 'other versions'

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#624]
776 is used for other physical versions of the work being described (like a reproduction of a journal or book vs. the original or the microform vs. the print).

787 is used for related works (like a supplement to a journal).

An 020 exact match means 2 bib records are the same edition of a book.
Same with 022 (or it could be an earlier or later title).

Would it be better to have the 787 and 776 links be handled in a different way than the 020 and 022 links?

**Comment by christinach** [comment]
Find an example for this issue. @mzelesky

**Comment by christinach** [comment]
@mzelesky do we still want to look into this?

**Comment by mzelesky** [comment]
If this has not come up from any other place, I think it's no longer an active concern of mine.

**Comment by kevinreiss** [comment]
Ok, we can close it.
