### ISSUE TITLE
Accommodate "On-order" functionality for Alma

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#630]
Child of #573 

Currently, statutes defined in the `order_statuses` method in `AvailabilityController` reflects custom availability statuses in orangelight when items have been ordered but are not yet received.  This functionality interacts with but does not come from Voyager directly.  Can we accommodate this behavior with data from Alma?

@kevinreiss does this summarize this issue?

Notes on alma were added in #642

**Comment by christinach** [comment]
this is the documentation for the order_status in Alma. https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/020Acquisitions/020Purchasing/030Searching_for_PO_Lines

**Comment by christinach** [comment]
check the Acq API, PO Lines `GET /almaws​/v1​/acq​/po-lines Retrieve PO-Lines`
based on the documentation `PO-Line Status. Optional. Valid values are CLOSED, CANCELLED, ACTIVE, ALL, ALL_WITH_CLOSED. Default: ALL (retrieves all PO lines except CLOSED).`

**Comment by christinach** [comment]
https://github.com/pulibrary/marc_liberation/blob/8e94c719050fde74a6796b3ccf92264eec6e17c6/app/controllers/availability_controller.rb#L126
'Order Received',: **Closed** https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/020Acquisitions/020Purchasing/045Closing%2C_Reopening%2C_and_Relinking_PO_Lines#Closing_PO_Lines
'Pending Order': **Waiting for invoice**
'On-Order': **Ready**
@mzelesky can you confirm if these values are correct?

**Comment by mzelesky** [comment]
Statuses that map to 'Order Received' in liberator:
Waiting for Manual Renewal
Waiting for Renewal
Waiting for Invoice

Statuses that map to 'Pending Order' in liberator:
In Review
Manual Packaging
Auto Packaging
Ready

All other statuses map to 'On-Order'. This is pending further discussion with Acquisitions, but these are the definitions to use for now.

**Comment by christinach** [comment]
We will use this ^ mapping schema.

**Comment by mzelesky** [comment]
Here is a PO Line that should be mapped to 'On-Order'.

POL-8098

The status of the line is 'Sent'.

**Comment by mzelesky** [comment]
The PO Line number can be delivered in General Publishing at the item level.

**Comment by hackartisan** [comment]
Items on order have a work order type of "Acquisition" so we will use that for status. closing in favor of #937
