### ISSUE TITLE
Ensure interoperability with firestone_locator

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#635]
The Firestone Book locator uses the Bibliographic and Holdings APIs in the Bibdata service. These should continue to work once that system is ported on top of Alma’s equivalent APIs. 

Locator code:
* https://github.com/pulibrary/firestone_locator
  * See `includes/bibdata_info.php` for the exact use case.

**Comment by christinach** [comment]
Port the locator app so that it looks the physical availability. #641

**Comment by hackartisan** [comment]
I think this is superseded by https://github.com/pulibrary/orangelight/issues/2348 but I'm not sure how #641 is related. Do you recall @christinach?

**Comment by christinach** [comment]
@hackartisan I can go through #641 next week, I don't remember at the moment.

**Comment by hackartisan** [comment]
covered by another ticket
