### ISSUE TITLE
Get location information from Alma

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#644]
Retrieve holdings locations from Alma using the API, replacing static functionality for maintaining locations information currently set in `marc_to_solr/lib/location_extract.rb`.

Alma API documentation for locations here:
* https://developers.exlibrisgroup.com/alma/apis/conf/

Example API call for locations:
* https://api-na.hosted.exlibrisgroup.com/almaws/v1/conf/libraries?apikey=$API_KEY

**Comment by christinach** [comment]
This how the Locations Object looks like https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_locations.xsd/?tags=GET

**Comment by christinach** [comment]
we cannot configure yet the locations in Alma according to @mzelesky and @kevinreiss

**Comment by mzelesky** [comment]
Here are the locations we are going to use for the purposes of testing:

Firestone
Library code: MAIN
Location code: main

Rcppa
Library code: MAIN
Location code: offsite

Mendel
Library code: MUS
Location code: music

Rare book on-site [corresponds to ex]
Library code: MAIN
Location code: RARE

Rcpxr
Library code: GRAD
Location code: grad

Reference
Library code: MAIN
Location code: reference

Marquand
Library code: LAW
Location code: LAWRR

Reserves
Library code: MAIN
Location code: RESERVES

Periodicals
Library code: MAIN
Location code: per-room

Dixon
Library code: MAIN
Location code: new

**Comment by hackartisan** [comment]
We have code getting location info from Alma.
