### ISSUE TITLE
Full reset of Staging (Database/Dumps/Index/Files)

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#648]
the last event was on :
2020-04-05  2:30:10am | 2020-04-05  2:33:03am

Tasks:

- [ ] Delete all the data
- [ ] Run a full dump

**Comment by christinach** [comment]
all the changed records dump files are corrupted.

**Comment by hackmastera** [comment]
Staging was reset with production data, but the files aren't there so it's still broken.

Document how a reset should work.
