### ISSUE TITLE
Document how the hathi overlap file and the full hathi file will be received 

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#672]
- We received the hathi overlap by email. Is this the how we will move forward.
- Download or wget through the rake task the hathi_full file from https://www.hathitrust.org/how-to-add-etas-records-to-your-catalog#HathiFiles

**Comment by carolyncole** [comment]
How we get the overlap file
* You submit a report to them, that get uploaded into box.
* We get an email with a link to the overlap file.

**Comment by christinach** [comment]
we dont need this anymore. we removed hathi
