### ISSUE TITLE
[Bibdata] Zlib::GzipFile::Error: not in gzip format

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#682]
## Backtrace

    line 47 of [PROJECT_ROOT]/marc_to_solr/lib/index_functions.rb: initialize
    line 47 of [PROJECT_ROOT]/marc_to_solr/lib/index_functions.rb: open
    line 47 of [PROJECT_ROOT]/marc_to_solr/lib/index_functions.rb: unzip_mrc

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/54804967)

**Comment by christinach** [comment]
This happened twice today on bibdata-worker2 eventhough there was a gz file format.

**Comment by kevinreiss** [comment]
We haven't seen this issue recently, closing.
