### ISSUE TITLE
SCSB full dump refactor

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#684]
In the process_records:

https://github.com/pulibrary/marc_liberation/blob/356503c58ab51eb7dcf53f79b190dd7cb01f05de/app/models/concerns/scsb_partner_updates.rb#L116

1. Remove all 876 that have a subfield x value of 'Private'.
2. Remove all 852 that have no corresponding 876 fields (linked by subfield 0).
3. Remove the record if there are no remaining 852 fields.

**Comment by christinach** [comment]
In order to import the latest scsb dump we need to follow the steps @mzelesky listed to exclude private records.

**Comment by kevinreiss** [comment]
@mzelesky @christinach HTC generated a full dump of CUL records in the current UAT release (scheduled for deployment on 3/22/2021) and it included only shared and open items. So I think 1. on the list above can be crossed off. How would one check for the other two?

**Comment by christinach** [comment]
We will have to update the code https://github.com/pulibrary/marc_liberation/blob/356503c58ab51eb7dcf53f79b190dd7cb01f05de/app/models/concerns/scsb_partner_updates.rb#L116.

**Comment by christinach** [comment]
I can look into this next Monday (maintenance Monday).

**Comment by christinach** [comment]
@kevinreiss where can I find the last full dump of CUL? Is it in the S3 bucket?

**Comment by christinach** [comment]
@mzelesky confirmed that we can request a full dump with NO private records. 
We will do this through the api https://scsb.recaplib.org:9093/swagger-ui.html#/data-dump-rest-controller/exportDataDump or on demand (ad hoc) as we have been doing all this time, at least until Alma goes live.

**Comment by christinach** [comment]
@kevinreiss I'm sorry I forgot to tag you. ^^
