### ISSUE TITLE
Implement holdings param in bibliographic#bib 

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#712]
Allow records to be returned with or without holdings data depending on an option set in the bib retrieval methods requested in #709. 

The primary use case is to power the staff view in orangelight, but it's also used by catalogers for various work flows. We'd like to encourage catalogers to use the alma publication jobs instead, to reduce load on the Alma API.

For the cataloger use case they may want the record without holdings data so they can update it and re-load it.

Implementation:
* If it's easier we can remove the holdings fields before returning the record  instead of changing the Alma API invocation

**Comment by christinach** [comment]
https://bibdata.princeton.edu/bibliographic/922720?holdings=false
https://bibdata.princeton.edu/bibliographic/922720?holdings=true

**Comment by tpendragon** [comment]
I'm not seeing many requests for this in datadog. I think we can lower the priority here. What is this used for @christinach ?

**Comment by tpendragon** [comment]
@mzelesky Do you know if we have any services that use `holdings=true/false`?

**Comment by hackartisan** [comment]
Per conversation with @mzelesky - There is a cataloger use case for this. We should move forward.

Implementation:
- For holdings = false
  - Request the bib without the alma API parameters for p_avail and e_avail
- For holdings = true (current implementation, this should remain the default)
  - Request the bib with the alma API parameters for p_avail and e_avail

**Comment by tpendragon** [comment]
Closing this is an Orangelight ticket. I've created a test in Bibdata to ensure Bibliographic#bibs shows the AVA fields, it's just that the MARC view in OL only displays fields (0...999). I'll create a PR for the bibdata test shortly.

**Comment by hackartisan** [comment]
@mzelesky is it sufficient to ensure that the holdings data comes through? Do we need to accept a flag turning it off? It seems like consumer can just ignore those fields.

@tpendragon if that's the plan, should we delete https://github.com/pulibrary/bibdata/blob/26a21f36629906417a7a195fe6503bd426d8360d/app/controllers/bibliographic_controller.rb#L25-L28 and the opts argument at https://github.com/pulibrary/bibdata/blob/8d505697ae90aa91b06a0662830f73e846535933/app/adapters/alma_adapter/bib.rb#L11

**Comment by hackartisan** [comment]
Reopening and moving to inbox for clarification since we're not actually using the param.
