### ISSUE TITLE
List pieces of information from the alma record that we want to include in the bibdata call

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#721]
There are pieces of information in the alma record that are separate from the marc record. 
`<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><bibs total_record_count=\"1\"><bib><mms_id>991227850000541</mms_id><record_format>marc21</record_format><linked_record_id/><title>Welliver /</title><author>Goodyear, Frank Henry,</author><isbn>0847805972 :</isbn><network_numbers><network_number>263059</network_number><network_number>(CStRLIN)NJPG85-B14944</network_number><network_number>(OCoLC)11814035</network_number></network_numbers><place_of_publication>New York :</place_of_publication><date_of_publication>1985.</date_of_publication><publisher_const>Rizzoli,</publisher_const><holdings link=\"https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/991227850000541/holdings\"/><created_by>import</created_by><created_date>2011-12-17Z</created_date><last_modified_by>System</last_modified_by><last_modified_date>2020-06-01Z</last_modified_date><suppress_from_publishing>false</suppress_from_publishing><suppress_from_external_search>false</suppress_from_external_search><sync_with_oclc>NONE</sync_with_oclc><sync_with_libraries_australia>NONE</sync_with_libraries_australia><originating_system>OTHER</originating_system><originating_system_id>34744-train20072_c2db</originating_system_id><record>recordRemoved
</record><requests>0</requests></bib></bibs>`

**Comment by hackartisan** [comment]
We worked to ensure APIs only returned fields that clients needed.
