### ISSUE TITLE
bib_items method returns nonsensical data when there are no Firestone items

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/bibdata#724]
https://github.com/pulibrary/marc_liberation/blob/73a88ecc1c421245a8ca5a7f4a3ee125de65ba91/app/controllers/bibliographic_controller.rb#L96

See https://bibdata.princeton.edu/bibliographic/4105260/items:
```
{
rcppl: [
{
holding_id: 4384522,
call_number: "2875/4041",
items: [
{
id: 7194690,
on_reserve: "N",
copy_number: 1,
item_sequence_number: 1,
temp_location: null,
perm_location: "rcppl",
circ_group_id: 1,
pickup_location_code: "fcirc",
pickup_location_id: 299,
enum: null,
chron: null,
barcode: "32101087241137",
item_type: "Closed",
due_date: null,
patron_group_charged: null,
status: [
"Not Charged"
]
}
]
}
],
f: [
"ea",
"eb",
"ec",
"ed",
"ei",
"em",
"es",
"fa",
"fb",
"fc",
"fd",
"fi",
"fm",
"fs"
]
}
```

**Comment by hackartisan** [comment]
What is the data that is nonsensical in the example?

I'm cutting / pasting the response into the description so that if/when the response changes we'll know what this issue was talking about.
