### ISSUE TITLE
Fix leaders on records from alma publishing job

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#731]
We need a normalization rule in marc_liberation to normalize data from the alma publishing job. 
I our recent publishing job there were `leaders` with errors. @mzelesky @pmgreen @pdiskin could provide more feedback. 

Could normalization happen in alma before the publishing job runs?

Consequences:
- MARC21 records aren't reliable until this is fixed.

**Comment by christinach** [comment]
@mzelesky question to alma:

My team has noticed that some MARC records included in the general publishing job we ran from Alma have invalid structure. I will use the following MMS ID as an example: 991364420000541

The version in our general publishing job (set to output as MARC21 binary) has a Unicode character in position 18 of the leader made up of the following three bytes: \xEF\xBF\xBD (the Unicode replacement character U+FFFD). As a result, the directory structure is invalid, due to the Leader being 2 bytes longer than it should be. When retrieving the bib in MARCXML via the Bib API, the Unicode replacement character is still in the leader, but because MARCXML doesn't have positionally-defined data, it doesn't corrupt the rest of the record.

This was not a widespread issue; there were fewer than 10 records in the entire sandbox. But I wanted to bring it to your attention. It seems that records are not served in MARC21 binary 100% accurately. As a workaround, we can use the MARCXML standard for our publishing jobs. It is a larger format that is somewhat slower to process, but it should suffice.

**Comment by hackartisan** [comment]
These did not happen during migration; they should be handled with local cleanup.

**Comment by hackartisan** [comment]
Revisit if we decide to try using marc21.
