### ISSUE TITLE
MARC 856 Subfield X should not display.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/bibdata#745]
Reported by Jenn Baxmeyer, subfield X is for a non-public note.

## Example

https://catalog.princeton.edu/catalog/12036988 should just show the link under "Available online", not say "Open access"

## Technical Implementation Notes

I think we can just remove `|| s_field.code == 'x'`, but I don't know where this is tested. @christinach ?

https://github.com/pulibrary/marc_liberation/blob/202d9e3ad58b178c88358c6d04ffd08eb1d83c9e/marc_to_solr/lib/electronic_access_link_factory.rb#L18

**Comment by christinach** [comment]
- This decision was made back in 2017 https://github.com/pulibrary/marc_liberation/pull/272/files#diff-77f233861b3ad74611f04587906bb5beR321. 
- We refactored as https://github.com/pulibrary/marc_liberation/commit/7b3a6cf7b360c624aa27a255d36fd9aba5bb64d6.
- Tested in: https://github.com/pulibrary/marc_liberation/blob/73a88ecc1c421245a8ca5a7f4a3ee125de65ba91/marc_to_solr/spec/lib/princeton_marc_spec.rb#L151

**Comment by christinach** [comment]
closed by #1462
