### ISSUE TITLE
Availability gap analysis

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#749]
- [ ] What information are we looking currently for ILS data. 1.availability https://github.com/pulibrary/marc_liberation/issues/750 2.rest of the apps based on what calls are we doing to Voyager. 
- [ ] What do we get from the publishing job and the APIs.see https://github.com/pulibrary/marc_liberation/issues/714
- [ ] What is missing? What are the differences.
- [ ] Do we want work arounds or we don't care about the missing pieces?

**Comment by christinach** [comment]
@kelynch will start a google spreadsheet

**Comment by kelynch** [comment]
Here's a sheet with the profile mappings - https://docs.google.com/spreadsheets/d/1xWA7lmICLp5sT2yROPyeKz_AbOsBa_nNhjNCDGDE2O8/edit#gid=0

**Comment by christinach** [comment]
Thanks @kelynch !
