### ISSUE TITLE
Move Hathi Deny items to new temporary location in Voyager

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/bibdata#755]
This will prevent patrons from checking out these items. 

Full List of Accept/Deny: https://drive.google.com/file/d/13EOsp6HbiLOw397YNteTGbG3zg0EDYFa/view

There are some rake tasks that exist which may be useful as reference. The code that splits out DENY from ALLOW should be added to Marc Liberation.

Existing rake tasks: https://github.com/pulibrary/marc_liberation/blob/master/lib/tasks/hathi.rake#L15

Some of these items may be charged to the CDL user. What will happen when we attempt to move them to a non-circulating location? The answer to this question will impact the implementation of https://github.com/pulibrary/orangelight/issues/2185

**Comment by kevinreiss** [comment]
a new "etas" holding location has been created and added to bibdata. We have two example items under this location in Voyager. 

Firestone Item: https://catalog.princeton.edu/catalog/162632
Recap Item: https://catalog.princeton.edu/catalog/162629

**Comment by kevinreiss** [comment]
The request form on these does now go to our default behavior, the "Help Me Get It" button. Some wonkiness in the display which I will ticket in the requests repo.

**Comment by christinach** [comment]
We are moving to alma. We will not use ETAS any more. The location has been removed.
