### ISSUE TITLE
Download the latest HATHI full dump

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/bibdata#768]
For example: https://www.hathitrust.org/sites/www.hathitrust.org/files/hathifiles/hathi_full_20200701.txt.gz . The date changes based on the current month `YYYYMM01.txt.gz` . These files are sometimes not available until the middle of the month. For reference there's a list of files at https://www.hathitrust.org/hathifiles.

refs #760
refs #769

**Comment by tpendragon** [comment]
Rather than a new table can you just do it all in a transaction?

**Comment by hackmastera** [comment]
A transaction will work considering we will abandon the find_or_create logic. I'll update the description!

**Comment by hackmastera** [comment]
Moved data load / transaction info to #769.

Other question: Should this be a rake task scheduled via cron? Given that the exact time of publishing may be unpredictable, should it run every night and only check for a download if the file in isn't yet in our destination location? Should #769 then build on this to immediate start the data load once download is complete?

**Comment by christinach** [comment]
We removed hathi from the codebase.
