### ISSUE TITLE
Figgy ARK overrides shouldn't replace the 856 label with "Digital content" if it's not a link

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/bibdata#770]
https://catalog.princeton.edu/catalog/3852474 should still say "Selected images"

https://github.com/pulibrary/marc_liberation/blob/b056f4c65bc116d0dec827fb812e7597fcf26f4c/marc_to_solr/lib/princeton_marc.rb#L392 is probably what we'd have to change.

**Comment by kelynch** [comment]
This is a request from Tom V. and Martin.

**Comment by tpendragon** [comment]
Tested and not fixed for the case of Figgy links - it's another branch.

**Comment by christinach** [comment]
Resolved it displays Selected images https://catalog.princeton.edu/catalog/9938524743506421
