### ISSUE TITLE
Hard-code on_reserve field to 'n' in bibliographic/:id/holdings/:id/availability

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#846]
Update: Hard-code this as "n". Print reserves are currently not in use, and their reintroduction is not guaranteed.

child of #573 

In voyager this is a "y" if the item is on reserve.

An item is on reserve if it's on a course reserve list.

this field is used by the requests app.

**Comment by christinach** [comment]
blocked by #844

**Comment by hackartisan** [comment]
blocked by #931
