### ISSUE TITLE
Remove pickup_location_id and pickup_location_code fields from bibliographic/:id/holdings/:id/availability

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#848]
child of #573 

Alma doesn't use these.

example of previous values:
```
pickup_location_code: "fcirc",
pickup_location_id: 299,
```
Current mapping from voyager is in voyager_helpers https://github.com/pulibrary/voyager_helpers/blob/0ae062a25177187fb6b47ae19e29b45ea469acb0/lib/voyager_helpers/liberator.rb#L1325

https://github.com/pulibrary/requests/blob/91dfc63ae297183f478589c7764de67acf1519c4/app/models/requests/requestable/item.rb#L3

https://github.com/pulibrary/requests/blob/175199ffbfe321ee1de86bce21f11bc78fd827dd/app/models/concerns/requests/voyager.rb#L66

**Comment by christinach** [comment]
blocked by #844

**Comment by hackartisan** [comment]
Blocked by locations discussion.

**Comment by hackartisan** [comment]
@mzelesky This value powers the new pickup service implemented for covid. Can you help us figure out how this service will be impelmented in Alma?

**Comment by hackartisan** [comment]
These values are now in use!

**Comment by jrgriffiniii** [comment]
@kevinreiss has confirmed that this has been resolved by previous work undertaken by @hectorcorrea

**Comment by hectorcorrea** [comment]
See https://github.com/pulibrary/bibdata/issues/1378
