### ISSUE TITLE
Clean up dump files on sftp server

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#855]
We'll need a job that cleans up the full and incremental publishing job dump files on the ftp server to keep it from growing out of control.

these files are in /alma/publishing

We can delete anything older than 1 month. (note the files are stored longer in bibdata; see https://github.com/pulibrary/bibdata/blob/50b293cd5fcdb02ff8716984c6f953c6a24ecc14/lib/tasks/marc_liberation.rake)

**Comment by tpendragon** [comment]
Normally the way this would get handled is a cron job on `lib-sftp` that just does `find /alma/* -mtime +30 -exec rm {} \;`, but it doesn't look like lib-sftp is handled by ansible. @kayiwa should we add an ansible role that only does that somehow? Or maybe we should just add this to that box?

**Comment by hackartisan** [comment]
We should enter the cron manually and document it in pul-the-hard-way. Put the cron job on the user who owns the files.
