### ISSUE TITLE
Estimate how many times we hit the alma api.

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#871]
We want to see how many times the alma api is hit in marc_liberation for any given job. 
It would be good to see how many times the marc_liberation queries voyager based on the various endpoints and drive an estimate from that.

Once we get a week's worth of stats, use them in combination with the number of (anticipated) API calls per controller action to produce an estimate. Compare with the API limits.

**Comment by tpendragon** [comment]
We can track hits to our API with this: https://app.datadoghq.com/logs/analytics?agg_q=%40controller%2C%40action%2C%40format&cols=host%2Cservice%2C%40http.url_details.queryString.q%2C%40action%2C%40format&from_ts=1604271119706&index=&live=true&messageDisplay=inline&query=source%3Aruby+service%3Abibdata+-%40controller%3A%22Locations%3A%3AHoldingLocationsController%22+-%40controller%3A%22Locations%3A%3ADeliveryLocationsController%22+-%40controller%3A%22HighVoltage%3A%3APagesController%22++-%40controller%3A%22Users%3A%3AOmniauthCallbacksController%22&stream_sort=desc&to_ts=1606863119706&top_n=10&viz=query_table

**Comment by christinach** [comment]
I'm not sure how this will work now that we have removed the voyager helpers in the alma branch. My first thought was to merge this in the main branch to track the voyager calls but since we rebase the alma branch with the main branch this will error because it will no longer have the voyager helpers connection.

**Comment by tpendragon** [comment]
We need to figure out the Alma API limits and compare them to datadog limits in that timeframe and see if we have a problem.

**Comment by mzelesky** [comment]
The current limit is 300,000 per day.

**Comment by hackartisan** [comment]
We may also need to make a datadog report for OL endpoints which use voyager directoy for patron account interactions.

**Comment by christinach** [comment]
I followed @tpendragon solution and made a start with https://app.datadoghq.com/logs/analytics?agg_m=count&agg_q=%40controller%2C%40action%2C%40format&agg_t=count&analyticsOptions=%5B%22bars%22%2C%22cool%22%2Cnull%2Cnull%2C%22value%22%5D&from_ts=1610402629076&index=&live=true&query=service%3Abibdata+host%3Abibdata-alma-staging1++-controller%3A%22HighVoltage%3A%3APagesController%22&to_ts=1610403529076&top_n=10&top_o=top&viz=query_table

**Comment by hectorcorrea** [comment]
ExLibris documentation of the limits: https://developers.exlibrisgroup.com/alma/apis/#threshold

**Comment by hackartisan** [comment]
Work on this issue is happening in https://docs.google.com/spreadsheets/d/1LmwK6s2IK6L98-DY3JIHHohUQcqYYa7qupZIJHv7Pu8/edit#gid=0
