### ISSUE TITLE
Add 852 subfield k to holdings location indexed data

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#873]
SC has requested we pass this value into the Aeon system as a "SubLocation" parameter. Currently only the call number is available only as a single concatenated value. See for more details and example records. 

https://github.com/pulibrary/requests/issues/782 

## Implementation notes
We want to create a new field called "sub_location" in holdings1_display where we index 852$k. Then this will be used in Aeon and will be mapped to the SubLocation parameter.

**Comment by christinach** [comment]
@regineheberlein will check on this.

**Comment by regineheberlein** [comment]
From my previous Slack conversation with DT about this, this should actually be the 852k--it was 852$c in Voyager but is 852$k in Alma. I'll confirm.

**Comment by regineheberlein** [comment]
Confirmed--it's now the 852$k and should be indexed and sent to Aeon. It's deemed "essential". It's needed for Aeon.

**Comment by christinach** [comment]
We want to create a new field in holdings1_display where we index `852$k`. Then this will be used in Aeon and will be mapped to the `SubLocation` parameter.

**Comment by kevinreiss** [comment]
We will need to update the solr document to Aeon mapping in OL/Requests once this is indexed.
