### ISSUE TITLE
As a selector, I would like to review the non-Reserves CDL items so I can decide whether or not to reshelve them

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#895]
Since having an item on CDL makes it unavailable for checkout or in-Library use, selectors would like to be able to decide whether to reshelve items. For reserves items, we already have a process for doing that at the end of the semester, but for non-Reserves items, they will remain on CDL indefinitely unless we have a mechanism to review and reshelve items.

**Comment by hackartisan** [comment]
That's true I forgot they are added to the CDL collection. But that isn't kept in sync with their voyager status. Something could be checked-in from the CDL user in voyager and still be in figgy's CDL collection.

**Comment by kevinreiss** [comment]
Is this still a useful feature given our current use of CDL? Check with resource sharing staff.
