### ISSUE TITLE
Move indexing documentation into this repository

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#897]
@kayiwa I would like to move the indexing documentation (Steps to create a new full index) in this repository? Do you see any sensitive information in the documentation https://docs.google.com/document/d/1bHvgfgyUmDXV7ROqEZFaRxJFEYhSSUbeQoQT883GMWg/edit#heading=h.52h6kcl0n8c4 that would prevent me to do so?

**Comment by kayiwa** [comment]
nothing in there can't be public @christinach

**Comment by christinach** [comment]
Thank you @kayiwa !

**Comment by christinach** [comment]
In our Monday meeting we decided to add this documentation in a separate markdown document --@carolyncole @kmcelwee  @kelynch thank you for your input-- so that we can track any changes, and link it in the readme. @jrgriffiniii also suggested that we can use https://pandoc.org/ to transform the markdown to a different format.

**Comment by christinach** [comment]
closed by  #1519
