### ISSUE TITLE
Reader Friendly Version of Patron Route

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#898]
Create a HTML version of the data displayed in the patron route JSON. Library staff will use this route to look up user information as the they troubleshoot access questions. Display:

- [ ] Patron's campus authorization state
- [ ] LDAP information (currently access by adding ldap=true to the existing route)
- [ ] Voyager account status (including if the ID passed does not have a voyager account)

**Comment by christinach** [comment]
@kevinreiss can we close this?

**Comment by kevinreiss** [comment]
Yes, this was something that was for our pandemic operations that we just never got to.
