### ISSUE TITLE
Manage SCSB Update/Delete files via S3

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#909]
The contractor hosting SCSB is moving away from using a SFTP server and will utilize an S3 bucket to make this daily changelog data (and other reports/logs generated by SSCSB) available to us. Will have more details on this soon. Will update the ticket when they are available. 

- [x] Download Daily Partner Updates/Adds
   * `bundle exec rake marc_liberation:partner_update`
- [x] Download Daily Partner Deletes
    * done via https://github.com/pulibrary/marc_liberation/blob/356503c58ab51eb7dcf53f79b190dd7cb01f05de/app/models/concerns/scsb_partner_updates.rb#L23. (run through the list of all barcodes update for the day)
- [ ] Upload Daily Princeton Update Records (SCSB's "SubmitCollection" API)
  * https://github.com/pulibrary/marc_liberation/blob/090e90bf02cdbd80564c14bd9e8b01952f4a8a64/app/jobs/recap_dump_job.rb
       * `bundle exec rake marc_liberation:recap_dump`
       * https://github.com/pulibrary/marc_liberation/blob/356503c58ab51eb7dcf53f79b190dd7cb01f05de/app/jobs/recap_dump_job.rb#L19
- [ ] All files submitted to the SCSB server via submitCollection or transfer API need to prefixed with the string "scsb_" with the rest of the filename unchanged.

**Comment by carolyncole** [comment]
I put the environment variable out on staging.
Here is some example code for accessing a file (there is only data in the test bucket).  Assumes `aws-sdk-s3` gem is installed
``` 
credentials = Aws::Credentials.new(ENV['SCSB_S3_ACCESS_KEY'], ENV['SCSB_S3_SECRET_ACCESS_KEY'])
s3 = Aws::S3::Client.new(region: 'us-east-1', credentials: credentials)
resp = s3.get_object(bucket: ENV['SCSB_S3_BUCKET_NAME'], key:'data-feed/submitcollections/PUL/cgd_protection/')
string_io = resp.body
```

**Comment by mzelesky** [comment]
Current path for incremental partner updates: /scsb-test/data-exports/PUL/MarcXML/Incremental
Current path for incremental partner deletes: /scsb-test/data-exports/PUL/Json/Incremental
Current path for full partner updates: /scsb-test/data-exports/PUL/MarcXML/Full

**Comment by hackartisan** [comment]
@kevinreiss Is this change rolling out at the same time as alma? Or is it on its own timeline?

**Comment by christinach** [comment]
If we want to update this now on main we first need to fix https://github.com/pulibrary/voyager_helpers/issues/120#issue-718133894.

**Comment by hackartisan** [comment]
From conversation with Mark: deadlines here have shifted, but they're deploying their new code in March so presumably we won't be able to retrieve the files in their current location anymore at that point.

**Comment by kevinreiss** [comment]
There is a meeting on Monday that will discuss the release cycle for the
next SCSB deployment to production, we should know the planned date then.

**Comment by hackartisan** [comment]
@kevinreiss are files available in both locations for some period of time? It would be helpful to know what that window looks like.

**Comment by carolyncole** [comment]
This used to work with SFTP, but at the end of March we need to move to using the S3 buckets.
We need to confirm that we can use the data by the end of February.

Upload Daily Princeton Update Records:
  * You can submit as many files as you want in a day in a chunk.
  * You put the files into the S3 bucket and then then scsb will pick them up automatically.
Download Daily Partner Updates/Adds:
  * Current path for incremental partner updates: /scsb-test/data-exports/PUL/MarcXML/Incremental
  * Current path for incremental partner deletes: /scsb-test/data-exports/PUL/Json/Incremental
  * Current path for full partner updates: /scsb-test/data-exports/PUL/MarcXML/Full

**Comment by christinach** [comment]
`Upload Daily Princeton Update Records: (SFTP is currently broken)`

The princeton updates are paused. @mzelesky added a fix in voyager helpers but we haven't created a new release of the gem to update mar_liberation. To resume the job, we first need to test if @mzelesky's new fix in voyager helpers uploads the valid princeton marc records to scsb.

**Comment by carolyncole** [comment]
@christinach is this ticketed?

> `Upload Daily Princeton Update Records: (SFTP is currently broken)`
> 
> The princeton updates are paused. @mzelesky added a fix in voyager helpers but we haven't created a new release of the gem to update marc_liberation. To resume the job, we first need to test that @mzelesky's new fix in voyager helpers uploads the valid Princeton marc records to scsb.

**Comment by christinach** [comment]
@carolyncole I did a quick look. No it is not. It was added only in comments. Feel free to open a ticket.

**Comment by kevinreiss** [comment]
The planned end for SFTP to be used in production is March 19th at the moment. The SFTP server will remain around for approximately a month as any archive but any new partner record updates/reports will only be posted on S3 and any updates we want to submit about our own records should go there.

**Comment by kevinreiss** [comment]
Per @christinach for submitCollection we still have to the following

1 Setting up the S3 connection in the RecapDump job
2. run the job with a timestamp going back to February 17th
3. resume the daily cron job.

**Comment by christinach** [comment]
@kevinreiss I'm referencing https://github.com/pulibrary/bibdata/issues/1049#issue-801651985 because I describe it in the comment. `The cron job is currently paused and can be resumed to upload from current production Princeton records to SCSB when the AWS connection to SCSB is set and tested (#909 Third checkbox 'Upload Daily Princeton Update Records (SCSB's "SubmitCollection" API)'). As of today 03-10-2021, data were last updated manually by @mzelesky on February 17th; with that said, the job should also run with a timestamp of 02-17-2021 to upload the Princeton records starting 02-17-2021 until the time we resume the job again.`

**Comment by carolyncole** [comment]
The new files need to be named "scsb_*"

**Comment by christinach** [comment]
Today we uploaded our Princeton records since 2021-02-17.
