### ISSUE TITLE
Finalize indexing infrastructure

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#924]
Finalize rules and implementation for full and incremental indexes. Ensure jobs are scheduled and running. Ensure documentation is complete.

Make sure we close https://github.com/pulibrary/pul_solr/issues/261 as part of this work.

**Comment by hectorcorrea** [comment]
Some notes regarding the caching of Figgy data during the indexing: https://docs.google.com/document/d/1Y_L13hcVnabcUHtiIpEkISFvHJ8zRzeOxBAlI2ErmBE/edit#

**Comment by hackartisan** [comment]
closed by:
- https://github.com/pulibrary/bibdata/pull/1493
- https://github.com/pulibrary/bibdata/pull/1497
- https://github.com/pulibrary/bibdata/pull/1502
- https://github.com/pulibrary/bibdata/pull/1526
- https://github.com/pulibrary/bibdata/pull/1527
- https://github.com/pulibrary/bibdata/pull/1532
