### ISSUE TITLE
reindex single record: catalog_date field

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#925]
**Single Record**
Child of https://github.com/pulibrary/marc_liberation/issues/748 -- see implementation notes there!

1. Get a single alma record with `p_avail` and `e_avail` parameters: https://developers.exlibrisgroup.com/console/?url=/wp-content/uploads/alma/openapi/bibs.json#/Catalog/get%2Falmaws%2Fv1%2Fbibs%2F%7Bmms_id%7D

2. If it has any `AVA` fields that correspond to `p_avail` (physical availability), get the list of items to get the `<creation_date>` . Get the earliest `creation_date` from the <items> list.

3. If there are no `AVA` fields that correspond to `p_avail`, look for `AVE` fields that correspond to `e_avail`. Each `AVE` field has a portfolio id included. For each `AVE` field in the API response, you must retrieve the portfolio information. Use the oldest `<portfolio><activation_date>` from the attached portfolios. See https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_portfolio.xsd/

4. If there is no `p_avail` or `e_avail`, use `<bib><created_date>`.

**Comment by hectorcorrea** [comment]
Note that ([as indicated in the code](https://github.com/pulibrary/marc_liberation/pull/1112/files#diff-a745970613fff65d649c1b2335778c06c3b69a6581d752d62059619b6806e12aR66-R90)) we are not implementing the logic for the AVE fields yet. We'll add this later once ExLibris provides an API to get all portfolios for a bib record from a single call.

**Comment by hackartisan** [comment]
@hectorcorrea should we create a new ticket to track the follow up that we'll need once exlibris makes the change?

**Comment by hackartisan** [comment]
The bulk of this work was done in https://github.com/pulibrary/bibdata/pull/1112, it's just not yet integrated into the controller.

**Comment by hackartisan** [comment]
closing in favor of #1478
