### ISSUE TITLE
Update the 773w field in the Alma records

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#950]
The 773w in the alma records has the voyagerID. We should update the alma data so that the 773w includes the almaID and not the voyagerID. @mzelesky @pmgreen @pdiskin 
example from the current catalog: https://catalog.princeton.edu/catalog/5992267

alma record: `<record><leader>00733cas a22001695a 4500</leader><controlfield tag='005'>20200723145309.0</controlfield><controlfield tag='008'>091119d194419uugr ||         0    0gre d</controlfield><controlfield tag='001'>99224859506421</controlfield><datafield ind1=' ' ind2=' ' tag='040'><subfield code='a'>NjP</subfield><subfield code='c'>NjP</subfield></datafield><datafield ind1=' ' ind2=' ' tag='043'><subfield code='a'>e-gr---</subfield></datafield><datafield ind1='0' ind2='0' tag='245'><subfield code='a'>Rizospastikē ēchō :</subfield><subfield code='b'>kathēmerinē ephēmeris. Organon tēs Rizospastikēs Organōseōs.</subfield></datafield><datafield ind1=' ' ind2=' ' tag='260'><subfield code='a'>Athēnai :</subfield><subfield code='b'>[s.n.]</subfield></datafield><datafield ind1=' ' ind2='7' tag='655'><subfield code='a'>Newspapers</subfield><subfield code='z'>Greece</subfield><subfield code='2'>rbgenr</subfield></datafield><datafield ind1='0' ind2=' ' tag='773'><subfield code='t'>Collection of Greek newspapers</subfield><subfield code='w'>3675106</subfield></datafield><datafield ind1='0' ind2=' ' tag='852'><subfield code='0'>6052069</subfield><subfield code='b'>rcpxr</subfield><subfield code='h'>DF853</subfield><subfield code='i'>.C66q Box 8</subfield></datafield><datafield ind1=' ' ind2='0' tag='866'><subfield code='0'>6052069</subfield><subfield code='a'>etos 3.: 4 Okt. 1944; 8 Okt. 1944; 12 Okt. 1944; undated issue (phyll. 45); 15-22 Okt. 1944; 24-26 Okt. 1944</subfield></datafield><datafield ind1=' ' ind2=' ' tag='902'><subfield code='a'>kba</subfield><subfield code='b'>o</subfield><subfield code='6'>a</subfield><subfield code='7'>s</subfield><subfield code='d'>v</subfield><subfield code='f'>0</subfield><subfield code='e'>20091119</subfield></datafield><datafield ind1=' ' ind2=' ' tag='950'><subfield code='c'>2020-07-23 14:53:09 US/Eastern</subfield><subfield code='b'>2020-06-01 15:49:10 US/Eastern</subfield><subfield code='a'>false</subfield></datafield><datafield ind1='0' ind2=' ' tag='852'><subfield code='b'>GRAD</subfield><subfield code='c'>grad</subfield><subfield code='8'>2282991920006421</subfield></datafield><datafield ind1=' ' ind2=' ' tag='952'><subfield code='d'>2020-06-01 19:49:26</subfield><subfield code='8'>2282991920006421</subfield><subfield code='a'>2020-06-01 19:49:26</subfield><subfield code='b'>Graduate Library</subfield><subfield code='c'>Stacks</subfield><subfield code='e'>false</subfield></datafield><datafield ind1=' ' ind2=' ' tag='876'><subfield code='0'>2282991920006421</subfield><subfield code='a'>2382991890006421</subfield><subfield code='j'>1</subfield><subfield code='i'>0</subfield><subfield code='d'>2020-06-01 19:49:27</subfield><subfield code='p'>A15222</subfield></datafield></record>
`

**Comment by mzelesky** [comment]
Sample records can be looked up after we receive the new Alma environment on January 4th.

**Comment by hackartisan** [comment]
done
