### ISSUE TITLE
reindex single record: call_number_browse and call_number_display

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#967]
Child of #748 -- see implementation notes there!

1. 

Doing a bibs api call will return an AVA tag with a subfield 'd' for the call number (in this example Eng 20Q 6819)
https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs?apikey=<apikey>&expand=p_avail%2Ce_avail%2Cd_avail%2Crequests&mms_id= 9957270023506421 

`<datafield ind1=" " ind2=" " tag="AVA">
                <subfield code="0">9957270023506421</subfield>
                <subfield code="8">22262209280006421</subfield>
                <subfield code="a">01PRI_INST</subfield>
                <subfield code="b">rare</subfield>
                <subfield code="c">Cotsen Children's Library (CTSN)</subfield>
                <subfield code="d">Eng 20Q 6819</subfield>
                <subfield code="e">available</subfield>
                <subfield code="f">1</subfield>
                <subfield code="g">0</subfield>
                <subfield code="j">ctsn</subfield>
                <subfield code="k">8</subfield>
                <subfield code="p">1</subfield>
                <subfield code="q">Rare Books and Special Collections</subfield>
            </datafield>`

2. 

Looking further in an api call to get the holding for this mms_id: https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/9957270023506421/holdings/22262209280006421?apikey=apikey will return :
`{
  "holding_id": "22262209280006421",
  "created_by": "import",
  "created_date": "2020-12-03Z",
  "originating_system": "ILS",
  "originating_system_id": "4982703-princetondb",
  "suppress_from_publishing": "false",
  "anies": [
    "<?xml version=\"1.0\" encoding=\"UTF-16\"?><record>\n    <leader>00176cx  a22000851  4500</leader>\n    <controlfield tag=\"001\">4982703</controlfield>\n    <controlfield tag=\"004\">5727002</controlfield>\n    <controlfield tag=\"005\">20090406123852.0</controlfield>\n    <controlfield tag=\"008\">0606020u||||8|||4001uu|||0000000</controlfield>\n    <datafield ind1=\"8\" ind2=\" \" tag=\"852\">\n      <subfield code=\"b\">rare</subfield>\n      <subfield code=\"c\">ctsn</subfield>\n      <subfield code=\"h\">6819</subfield>\n      <subfield code=\"k\">Eng 20Q</subfield>\n    </datafield>\n  </record>"
  ]
}` The holding api cal will return the 852 field with the subfields h and k for the call number.

When we force reindex a bib we can use the bibs api call (1) to check if there is a holding in the AVA tag. Then we can use the holdings api call (2) to read the call number subfields from the 852 field to index the call_number_browse and call_number_display. This workflow is based on the decision that the subfield k is desired to be at the end of the call_number see https://github.com/pulibrary/marc_liberation/issues/947#issuecomment-756254273

**Comment by hackartisan** [comment]
closing in favor of #1478
