### ISSUE TITLE
Redirect links with voyager IDs to their equivalent alma id endpoint

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#992]
Identify links pointing to existing source systems () that are migrated, so that they can be removed or updated, if necessary.  
Once a resource is migrated to Alma, the links should be updated to point to Alma. 
(will add more information)

**Comment by mzelesky** [comment]
Essentially, it is unknown how many external sites (like professor's blogs, LibGuides, etc.) use direct links to Blacklight bib records, so there needs to be a redirect in place to take a user from a Voyager bib ID to the new Alma MMS ID.

**Comment by hackartisan** [comment]
Do we want to inspect the ID? or do we want to just try a rewrite if the page isn't found?

A voyager bib id will always be numeric. There is no maximum length, but we could get the last id used in voyager (13million would be the highest). The minimum length of an alma id would be the prefix and suffix with 1 in between.

**Comment by tpendragon** [comment]
@hackartisan Is this meant to be an Orangelight ticket?

**Comment by hackartisan** [comment]
@tpendragon it must be; I can't think of how it would make sense in the bibdata context, and I don't see a different one for orangelight. I'll move it. Thanks!

**Comment by hackartisan** [comment]
Issue moved to [pulibrary/orangelight #2400](https://github.com/pulibrary/orangelight/issues/2400) via [**ZenHub**](https://www.zenhub.com/)
